Name:		node
Version:	v0.8.18
Release:	1%{?dist}
Summary:	nodejs

Group:		Hisoku
License:	No
URL:		http://hisoku.ronny.tw/
Source0:	node-v0.8.18.tar.gz
BuildRoot:	%(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

%description


%prep
%setup -q

%build
./configure 
make %{?_smp_mflags}


%install
rm -rf %{buildroot}
make install DESTDIR=%{buildroot}


%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc
/usr/local/bin/node
/usr/local/bin/node-waf
/usr/local/bin/npm
/usr/local/include/node/ares.h
/usr/local/include/node/ares_version.h
/usr/local/include/node/eio-emul.h
/usr/local/include/node/ev-emul.h
/usr/local/include/node/node.h
/usr/local/include/node/node_buffer.h
/usr/local/include/node/node_object_wrap.h
/usr/local/include/node/node_version.h
/usr/local/include/node/uv-private/eio.h
/usr/local/include/node/uv-private/ev.h
/usr/local/include/node/uv-private/ngx-queue.h
/usr/local/include/node/uv-private/tree.h
/usr/local/include/node/uv-private/uv-unix.h
/usr/local/include/node/uv-private/uv-win.h
/usr/local/include/node/uv.h
/usr/local/include/node/v8-debug.h
/usr/local/include/node/v8-preparser.h
/usr/local/include/node/v8-profiler.h
/usr/local/include/node/v8-testing.h
/usr/local/include/node/v8.h
/usr/local/include/node/v8stdint.h
/usr/local/lib/dtrace/node.d
/usr/local/lib/node/wafadmin/Build.py
/usr/local/lib/node/wafadmin/Configure.py
/usr/local/lib/node/wafadmin/Constants.py
/usr/local/lib/node/wafadmin/Environment.py
/usr/local/lib/node/wafadmin/Logs.py
/usr/local/lib/node/wafadmin/Node.py
/usr/local/lib/node/wafadmin/Options.py
/usr/local/lib/node/wafadmin/Runner.py
/usr/local/lib/node/wafadmin/Scripting.py
/usr/local/lib/node/wafadmin/Task.py
/usr/local/lib/node/wafadmin/TaskGen.py
/usr/local/lib/node/wafadmin/Tools/__init__.py
/usr/local/lib/node/wafadmin/Tools/ar.py
/usr/local/lib/node/wafadmin/Tools/cc.py
/usr/local/lib/node/wafadmin/Tools/ccroot.py
/usr/local/lib/node/wafadmin/Tools/compiler_cc.py
/usr/local/lib/node/wafadmin/Tools/compiler_cxx.py
/usr/local/lib/node/wafadmin/Tools/compiler_d.py
/usr/local/lib/node/wafadmin/Tools/config_c.py
/usr/local/lib/node/wafadmin/Tools/cxx.py
/usr/local/lib/node/wafadmin/Tools/d.py
/usr/local/lib/node/wafadmin/Tools/dmd.py
/usr/local/lib/node/wafadmin/Tools/gas.py
/usr/local/lib/node/wafadmin/Tools/gcc.py
/usr/local/lib/node/wafadmin/Tools/gdc.py
/usr/local/lib/node/wafadmin/Tools/gnu_dirs.py
/usr/local/lib/node/wafadmin/Tools/gob2.py
/usr/local/lib/node/wafadmin/Tools/gxx.py
/usr/local/lib/node/wafadmin/Tools/icc.py
/usr/local/lib/node/wafadmin/Tools/icpc.py
/usr/local/lib/node/wafadmin/Tools/intltool.py
/usr/local/lib/node/wafadmin/Tools/libtool.py
/usr/local/lib/node/wafadmin/Tools/misc.py
/usr/local/lib/node/wafadmin/Tools/nasm.py
/usr/local/lib/node/wafadmin/Tools/node_addon.py
/usr/local/lib/node/wafadmin/Tools/osx.py
/usr/local/lib/node/wafadmin/Tools/preproc.py
/usr/local/lib/node/wafadmin/Tools/python.py
/usr/local/lib/node/wafadmin/Tools/suncc.py
/usr/local/lib/node/wafadmin/Tools/suncxx.py
/usr/local/lib/node/wafadmin/Tools/unittestw.py
/usr/local/lib/node/wafadmin/Tools/winres.py
/usr/local/lib/node/wafadmin/Tools/xlc.py
/usr/local/lib/node/wafadmin/Tools/xlcxx.py
/usr/local/lib/node/wafadmin/Utils.py
/usr/local/lib/node/wafadmin/__init__.py
/usr/local/lib/node/wafadmin/ansiterm.py
/usr/local/lib/node/wafadmin/pproc.py
/usr/local/lib/node/wafadmin/py3kfixes.py
/usr/local/lib/node_modules/npm/.npmignore
/usr/local/lib/node_modules/npm/AUTHORS
/usr/local/lib/node_modules/npm/LICENSE
/usr/local/lib/node_modules/npm/Makefile
/usr/local/lib/node_modules/npm/README.md
/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp
/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp.cmd
/usr/local/lib/node_modules/npm/bin/npm
/usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/lib/node_modules/npm/bin/npm.cmd
/usr/local/lib/node_modules/npm/bin/read-package-json.js
/usr/local/lib/node_modules/npm/cli.js
/usr/local/lib/node_modules/npm/configure
/usr/local/lib/node_modules/npm/doc/api/bin.md
/usr/local/lib/node_modules/npm/doc/api/bugs.md
/usr/local/lib/node_modules/npm/doc/api/commands.md
/usr/local/lib/node_modules/npm/doc/api/config.md
/usr/local/lib/node_modules/npm/doc/api/deprecate.md
/usr/local/lib/node_modules/npm/doc/api/docs.md
/usr/local/lib/node_modules/npm/doc/api/edit.md
/usr/local/lib/node_modules/npm/doc/api/explore.md
/usr/local/lib/node_modules/npm/doc/api/help-search.md
/usr/local/lib/node_modules/npm/doc/api/init.md
/usr/local/lib/node_modules/npm/doc/api/install.md
/usr/local/lib/node_modules/npm/doc/api/link.md
/usr/local/lib/node_modules/npm/doc/api/load.md
/usr/local/lib/node_modules/npm/doc/api/ls.md
/usr/local/lib/node_modules/npm/doc/api/npm.md
/usr/local/lib/node_modules/npm/doc/api/outdated.md
/usr/local/lib/node_modules/npm/doc/api/owner.md
/usr/local/lib/node_modules/npm/doc/api/pack.md
/usr/local/lib/node_modules/npm/doc/api/prefix.md
/usr/local/lib/node_modules/npm/doc/api/prune.md
/usr/local/lib/node_modules/npm/doc/api/publish.md
/usr/local/lib/node_modules/npm/doc/api/rebuild.md
/usr/local/lib/node_modules/npm/doc/api/restart.md
/usr/local/lib/node_modules/npm/doc/api/root.md
/usr/local/lib/node_modules/npm/doc/api/run-script.md
/usr/local/lib/node_modules/npm/doc/api/search.md
/usr/local/lib/node_modules/npm/doc/api/shrinkwrap.md
/usr/local/lib/node_modules/npm/doc/api/start.md
/usr/local/lib/node_modules/npm/doc/api/stop.md
/usr/local/lib/node_modules/npm/doc/api/submodule.md
/usr/local/lib/node_modules/npm/doc/api/tag.md
/usr/local/lib/node_modules/npm/doc/api/test.md
/usr/local/lib/node_modules/npm/doc/api/uninstall.md
/usr/local/lib/node_modules/npm/doc/api/unpublish.md
/usr/local/lib/node_modules/npm/doc/api/update.md
/usr/local/lib/node_modules/npm/doc/api/version.md
/usr/local/lib/node_modules/npm/doc/api/view.md
/usr/local/lib/node_modules/npm/doc/api/whoami.md
/usr/local/lib/node_modules/npm/doc/cli/adduser.md
/usr/local/lib/node_modules/npm/doc/cli/bin.md
/usr/local/lib/node_modules/npm/doc/cli/bugs.md
/usr/local/lib/node_modules/npm/doc/cli/build.md
/usr/local/lib/node_modules/npm/doc/cli/bundle.md
/usr/local/lib/node_modules/npm/doc/cli/cache.md
/usr/local/lib/node_modules/npm/doc/cli/changelog.md
/usr/local/lib/node_modules/npm/doc/cli/coding-style.md
/usr/local/lib/node_modules/npm/doc/cli/completion.md
/usr/local/lib/node_modules/npm/doc/cli/config.md
/usr/local/lib/node_modules/npm/doc/cli/dedupe.md
/usr/local/lib/node_modules/npm/doc/cli/deprecate.md
/usr/local/lib/node_modules/npm/doc/cli/developers.md
/usr/local/lib/node_modules/npm/doc/cli/disputes.md
/usr/local/lib/node_modules/npm/doc/cli/docs.md
/usr/local/lib/node_modules/npm/doc/cli/edit.md
/usr/local/lib/node_modules/npm/doc/cli/explore.md
/usr/local/lib/node_modules/npm/doc/cli/faq.md
/usr/local/lib/node_modules/npm/doc/cli/folders.md
/usr/local/lib/node_modules/npm/doc/cli/help-search.md
/usr/local/lib/node_modules/npm/doc/cli/help.md
/usr/local/lib/node_modules/npm/doc/cli/index.md
/usr/local/lib/node_modules/npm/doc/cli/init.md
/usr/local/lib/node_modules/npm/doc/cli/install.md
/usr/local/lib/node_modules/npm/doc/cli/json.md
/usr/local/lib/node_modules/npm/doc/cli/link.md
/usr/local/lib/node_modules/npm/doc/cli/ls.md
/usr/local/lib/node_modules/npm/doc/cli/npm.md
/usr/local/lib/node_modules/npm/doc/cli/outdated.md
/usr/local/lib/node_modules/npm/doc/cli/owner.md
/usr/local/lib/node_modules/npm/doc/cli/pack.md
/usr/local/lib/node_modules/npm/doc/cli/prefix.md
/usr/local/lib/node_modules/npm/doc/cli/prune.md
/usr/local/lib/node_modules/npm/doc/cli/publish.md
/usr/local/lib/node_modules/npm/doc/cli/rebuild.md
/usr/local/lib/node_modules/npm/doc/cli/registry.md
/usr/local/lib/node_modules/npm/doc/cli/removing-npm.md
/usr/local/lib/node_modules/npm/doc/cli/restart.md
/usr/local/lib/node_modules/npm/doc/cli/root.md
/usr/local/lib/node_modules/npm/doc/cli/run-script.md
/usr/local/lib/node_modules/npm/doc/cli/scripts.md
/usr/local/lib/node_modules/npm/doc/cli/search.md
/usr/local/lib/node_modules/npm/doc/cli/semver.md
/usr/local/lib/node_modules/npm/doc/cli/shrinkwrap.md
/usr/local/lib/node_modules/npm/doc/cli/star.md
/usr/local/lib/node_modules/npm/doc/cli/start.md
/usr/local/lib/node_modules/npm/doc/cli/stop.md
/usr/local/lib/node_modules/npm/doc/cli/submodule.md
/usr/local/lib/node_modules/npm/doc/cli/tag.md
/usr/local/lib/node_modules/npm/doc/cli/test.md
/usr/local/lib/node_modules/npm/doc/cli/uninstall.md
/usr/local/lib/node_modules/npm/doc/cli/unpublish.md
/usr/local/lib/node_modules/npm/doc/cli/update.md
/usr/local/lib/node_modules/npm/doc/cli/version.md
/usr/local/lib/node_modules/npm/doc/cli/view.md
/usr/local/lib/node_modules/npm/doc/cli/whoami.md
/usr/local/lib/node_modules/npm/html/api/bin.html
/usr/local/lib/node_modules/npm/html/api/bugs.html
/usr/local/lib/node_modules/npm/html/api/commands.html
/usr/local/lib/node_modules/npm/html/api/config.html
/usr/local/lib/node_modules/npm/html/api/deprecate.html
/usr/local/lib/node_modules/npm/html/api/docs.html
/usr/local/lib/node_modules/npm/html/api/edit.html
/usr/local/lib/node_modules/npm/html/api/explore.html
/usr/local/lib/node_modules/npm/html/api/help-search.html
/usr/local/lib/node_modules/npm/html/api/init.html
/usr/local/lib/node_modules/npm/html/api/install.html
/usr/local/lib/node_modules/npm/html/api/link.html
/usr/local/lib/node_modules/npm/html/api/load.html
/usr/local/lib/node_modules/npm/html/api/ls.html
/usr/local/lib/node_modules/npm/html/api/npm.html
/usr/local/lib/node_modules/npm/html/api/outdated.html
/usr/local/lib/node_modules/npm/html/api/owner.html
/usr/local/lib/node_modules/npm/html/api/pack.html
/usr/local/lib/node_modules/npm/html/api/prefix.html
/usr/local/lib/node_modules/npm/html/api/prune.html
/usr/local/lib/node_modules/npm/html/api/publish.html
/usr/local/lib/node_modules/npm/html/api/rebuild.html
/usr/local/lib/node_modules/npm/html/api/restart.html
/usr/local/lib/node_modules/npm/html/api/root.html
/usr/local/lib/node_modules/npm/html/api/run-script.html
/usr/local/lib/node_modules/npm/html/api/search.html
/usr/local/lib/node_modules/npm/html/api/shrinkwrap.html
/usr/local/lib/node_modules/npm/html/api/start.html
/usr/local/lib/node_modules/npm/html/api/stop.html
/usr/local/lib/node_modules/npm/html/api/submodule.html
/usr/local/lib/node_modules/npm/html/api/tag.html
/usr/local/lib/node_modules/npm/html/api/test.html
/usr/local/lib/node_modules/npm/html/api/uninstall.html
/usr/local/lib/node_modules/npm/html/api/unpublish.html
/usr/local/lib/node_modules/npm/html/api/update.html
/usr/local/lib/node_modules/npm/html/api/version.html
/usr/local/lib/node_modules/npm/html/api/view.html
/usr/local/lib/node_modules/npm/html/api/whoami.html
/usr/local/lib/node_modules/npm/html/doc/README.html
/usr/local/lib/node_modules/npm/html/doc/adduser.html
/usr/local/lib/node_modules/npm/html/doc/bin.html
/usr/local/lib/node_modules/npm/html/doc/bugs.html
/usr/local/lib/node_modules/npm/html/doc/build.html
/usr/local/lib/node_modules/npm/html/doc/bundle.html
/usr/local/lib/node_modules/npm/html/doc/cache.html
/usr/local/lib/node_modules/npm/html/doc/changelog.html
/usr/local/lib/node_modules/npm/html/doc/coding-style.html
/usr/local/lib/node_modules/npm/html/doc/completion.html
/usr/local/lib/node_modules/npm/html/doc/config.html
/usr/local/lib/node_modules/npm/html/doc/dedupe.html
/usr/local/lib/node_modules/npm/html/doc/deprecate.html
/usr/local/lib/node_modules/npm/html/doc/developers.html
/usr/local/lib/node_modules/npm/html/doc/disputes.html
/usr/local/lib/node_modules/npm/html/doc/docs.html
/usr/local/lib/node_modules/npm/html/doc/edit.html
/usr/local/lib/node_modules/npm/html/doc/explore.html
/usr/local/lib/node_modules/npm/html/doc/faq.html
/usr/local/lib/node_modules/npm/html/doc/folders.html
/usr/local/lib/node_modules/npm/html/doc/help-search.html
/usr/local/lib/node_modules/npm/html/doc/help.html
/usr/local/lib/node_modules/npm/html/doc/index.html
/usr/local/lib/node_modules/npm/html/doc/init.html
/usr/local/lib/node_modules/npm/html/doc/install.html
/usr/local/lib/node_modules/npm/html/doc/json.html
/usr/local/lib/node_modules/npm/html/doc/link.html
/usr/local/lib/node_modules/npm/html/doc/list.html
/usr/local/lib/node_modules/npm/html/doc/ls.html
/usr/local/lib/node_modules/npm/html/doc/npm.html
/usr/local/lib/node_modules/npm/html/doc/outdated.html
/usr/local/lib/node_modules/npm/html/doc/owner.html
/usr/local/lib/node_modules/npm/html/doc/pack.html
/usr/local/lib/node_modules/npm/html/doc/prefix.html
/usr/local/lib/node_modules/npm/html/doc/prune.html
/usr/local/lib/node_modules/npm/html/doc/publish.html
/usr/local/lib/node_modules/npm/html/doc/rebuild.html
/usr/local/lib/node_modules/npm/html/doc/registry.html
/usr/local/lib/node_modules/npm/html/doc/removing-npm.html
/usr/local/lib/node_modules/npm/html/doc/restart.html
/usr/local/lib/node_modules/npm/html/doc/root.html
/usr/local/lib/node_modules/npm/html/doc/run-script.html
/usr/local/lib/node_modules/npm/html/doc/scripts.html
/usr/local/lib/node_modules/npm/html/doc/search.html
/usr/local/lib/node_modules/npm/html/doc/semver.html
/usr/local/lib/node_modules/npm/html/doc/shrinkwrap.html
/usr/local/lib/node_modules/npm/html/doc/star.html
/usr/local/lib/node_modules/npm/html/doc/start.html
/usr/local/lib/node_modules/npm/html/doc/stop.html
/usr/local/lib/node_modules/npm/html/doc/submodule.html
/usr/local/lib/node_modules/npm/html/doc/tag.html
/usr/local/lib/node_modules/npm/html/doc/test.html
/usr/local/lib/node_modules/npm/html/doc/uninstall.html
/usr/local/lib/node_modules/npm/html/doc/unpublish.html
/usr/local/lib/node_modules/npm/html/doc/update.html
/usr/local/lib/node_modules/npm/html/doc/version.html
/usr/local/lib/node_modules/npm/html/doc/view.html
/usr/local/lib/node_modules/npm/html/doc/whoami.html
/usr/local/lib/node_modules/npm/html/docfoot.html
/usr/local/lib/node_modules/npm/html/dochead.html
/usr/local/lib/node_modules/npm/html/favicon.ico
/usr/local/lib/node_modules/npm/html/index.html
/usr/local/lib/node_modules/npm/html/static/style.css
/usr/local/lib/node_modules/npm/html/static/webfonts/23242D_3_0.eot
/usr/local/lib/node_modules/npm/html/static/webfonts/23242D_3_0.ttf
/usr/local/lib/node_modules/npm/html/static/webfonts/23242D_3_0.woff
/usr/local/lib/node_modules/npm/lib/adduser.js
/usr/local/lib/node_modules/npm/lib/bin.js
/usr/local/lib/node_modules/npm/lib/bugs.js
/usr/local/lib/node_modules/npm/lib/build.js
/usr/local/lib/node_modules/npm/lib/cache.js
/usr/local/lib/node_modules/npm/lib/completion.js
/usr/local/lib/node_modules/npm/lib/config.js
/usr/local/lib/node_modules/npm/lib/dedupe.js
/usr/local/lib/node_modules/npm/lib/deprecate.js
/usr/local/lib/node_modules/npm/lib/docs.js
/usr/local/lib/node_modules/npm/lib/edit.js
/usr/local/lib/node_modules/npm/lib/explore.js
/usr/local/lib/node_modules/npm/lib/faq.js
/usr/local/lib/node_modules/npm/lib/get.js
/usr/local/lib/node_modules/npm/lib/help-search.js
/usr/local/lib/node_modules/npm/lib/help.js
/usr/local/lib/node_modules/npm/lib/init.js
/usr/local/lib/node_modules/npm/lib/install.js
/usr/local/lib/node_modules/npm/lib/link.js
/usr/local/lib/node_modules/npm/lib/ls.js
/usr/local/lib/node_modules/npm/lib/npm.js
/usr/local/lib/node_modules/npm/lib/outdated.js
/usr/local/lib/node_modules/npm/lib/owner.js
/usr/local/lib/node_modules/npm/lib/pack.js
/usr/local/lib/node_modules/npm/lib/prefix.js
/usr/local/lib/node_modules/npm/lib/prune.js
/usr/local/lib/node_modules/npm/lib/publish.js
/usr/local/lib/node_modules/npm/lib/rebuild.js
/usr/local/lib/node_modules/npm/lib/restart.js
/usr/local/lib/node_modules/npm/lib/root.js
/usr/local/lib/node_modules/npm/lib/run-script.js
/usr/local/lib/node_modules/npm/lib/search.js
/usr/local/lib/node_modules/npm/lib/set.js
/usr/local/lib/node_modules/npm/lib/shrinkwrap.js
/usr/local/lib/node_modules/npm/lib/star.js
/usr/local/lib/node_modules/npm/lib/start.js
/usr/local/lib/node_modules/npm/lib/stop.js
/usr/local/lib/node_modules/npm/lib/submodule.js
/usr/local/lib/node_modules/npm/lib/substack.js
/usr/local/lib/node_modules/npm/lib/tag.js
/usr/local/lib/node_modules/npm/lib/test.js
/usr/local/lib/node_modules/npm/lib/unbuild.js
/usr/local/lib/node_modules/npm/lib/uninstall.js
/usr/local/lib/node_modules/npm/lib/unpublish.js
/usr/local/lib/node_modules/npm/lib/update.js
/usr/local/lib/node_modules/npm/lib/utils/cmd-shim.js
/usr/local/lib/node_modules/npm/lib/utils/completion.sh
/usr/local/lib/node_modules/npm/lib/utils/completion/file-completion.js
/usr/local/lib/node_modules/npm/lib/utils/completion/installed-deep.js
/usr/local/lib/node_modules/npm/lib/utils/completion/installed-shallow.js
/usr/local/lib/node_modules/npm/lib/utils/completion/remote-packages.js
/usr/local/lib/node_modules/npm/lib/utils/completion/users.js
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js
/usr/local/lib/node_modules/npm/lib/utils/exec.js
/usr/local/lib/node_modules/npm/lib/utils/fetch.js
/usr/local/lib/node_modules/npm/lib/utils/find-prefix.js
/usr/local/lib/node_modules/npm/lib/utils/gently-rm.js
/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js
/usr/local/lib/node_modules/npm/lib/utils/link.js
/usr/local/lib/node_modules/npm/lib/utils/sha.js
/usr/local/lib/node_modules/npm/lib/utils/tar.js
/usr/local/lib/node_modules/npm/lib/version.js
/usr/local/lib/node_modules/npm/lib/view.js
/usr/local/lib/node_modules/npm/lib/whoami.js
/usr/local/lib/node_modules/npm/lib/xmas.js
/usr/local/lib/node_modules/npm/man/man1/README.1
/usr/local/lib/node_modules/npm/man/man1/adduser.1
/usr/local/lib/node_modules/npm/man/man1/author.1
/usr/local/lib/node_modules/npm/man/man1/bin.1
/usr/local/lib/node_modules/npm/man/man1/bugs.1
/usr/local/lib/node_modules/npm/man/man1/build.1
/usr/local/lib/node_modules/npm/man/man1/bundle.1
/usr/local/lib/node_modules/npm/man/man1/cache.1
/usr/local/lib/node_modules/npm/man/man1/changelog.1
/usr/local/lib/node_modules/npm/man/man1/coding-style.1
/usr/local/lib/node_modules/npm/man/man1/completion.1
/usr/local/lib/node_modules/npm/man/man1/config.1
/usr/local/lib/node_modules/npm/man/man1/dedupe.1
/usr/local/lib/node_modules/npm/man/man1/deprecate.1
/usr/local/lib/node_modules/npm/man/man1/developers.1
/usr/local/lib/node_modules/npm/man/man1/disputes.1
/usr/local/lib/node_modules/npm/man/man1/docs.1
/usr/local/lib/node_modules/npm/man/man1/edit.1
/usr/local/lib/node_modules/npm/man/man1/explore.1
/usr/local/lib/node_modules/npm/man/man1/faq.1
/usr/local/lib/node_modules/npm/man/man1/find.1
/usr/local/lib/node_modules/npm/man/man1/folders.1
/usr/local/lib/node_modules/npm/man/man1/get.1
/usr/local/lib/node_modules/npm/man/man1/global.1
/usr/local/lib/node_modules/npm/man/man1/help-search.1
/usr/local/lib/node_modules/npm/man/man1/help.1
/usr/local/lib/node_modules/npm/man/man1/home.1
/usr/local/lib/node_modules/npm/man/man1/index.1
/usr/local/lib/node_modules/npm/man/man1/init.1
/usr/local/lib/node_modules/npm/man/man1/install.1
/usr/local/lib/node_modules/npm/man/man1/json.1
/usr/local/lib/node_modules/npm/man/man1/link.1
/usr/local/lib/node_modules/npm/man/man1/list.1
/usr/local/lib/node_modules/npm/man/man1/ln.1
/usr/local/lib/node_modules/npm/man/man1/ls.1
/usr/local/lib/node_modules/npm/man/man1/npm.1
/usr/local/lib/node_modules/npm/man/man1/outdated.1
/usr/local/lib/node_modules/npm/man/man1/owner.1
/usr/local/lib/node_modules/npm/man/man1/pack.1
/usr/local/lib/node_modules/npm/man/man1/prefix.1
/usr/local/lib/node_modules/npm/man/man1/prune.1
/usr/local/lib/node_modules/npm/man/man1/publish.1
/usr/local/lib/node_modules/npm/man/man1/rebuild.1
/usr/local/lib/node_modules/npm/man/man1/registry.1
/usr/local/lib/node_modules/npm/man/man1/removing-npm.1
/usr/local/lib/node_modules/npm/man/man1/restart.1
/usr/local/lib/node_modules/npm/man/man1/rm.1
/usr/local/lib/node_modules/npm/man/man1/root.1
/usr/local/lib/node_modules/npm/man/man1/run-script.1
/usr/local/lib/node_modules/npm/man/man1/scripts.1
/usr/local/lib/node_modules/npm/man/man1/search.1
/usr/local/lib/node_modules/npm/man/man1/semver.1
/usr/local/lib/node_modules/npm/man/man1/set.1
/usr/local/lib/node_modules/npm/man/man1/shrinkwrap.1
/usr/local/lib/node_modules/npm/man/man1/star.1
/usr/local/lib/node_modules/npm/man/man1/start.1
/usr/local/lib/node_modules/npm/man/man1/stop.1
/usr/local/lib/node_modules/npm/man/man1/submodule.1
/usr/local/lib/node_modules/npm/man/man1/tag.1
/usr/local/lib/node_modules/npm/man/man1/test.1
/usr/local/lib/node_modules/npm/man/man1/uninstall.1
/usr/local/lib/node_modules/npm/man/man1/unpublish.1
/usr/local/lib/node_modules/npm/man/man1/update.1
/usr/local/lib/node_modules/npm/man/man1/version.1
/usr/local/lib/node_modules/npm/man/man1/view.1
/usr/local/lib/node_modules/npm/man/man1/whoami.1
/usr/local/lib/node_modules/npm/man/man3/author.3
/usr/local/lib/node_modules/npm/man/man3/bin.3
/usr/local/lib/node_modules/npm/man/man3/bugs.3
/usr/local/lib/node_modules/npm/man/man3/commands.3
/usr/local/lib/node_modules/npm/man/man3/config.3
/usr/local/lib/node_modules/npm/man/man3/deprecate.3
/usr/local/lib/node_modules/npm/man/man3/docs.3
/usr/local/lib/node_modules/npm/man/man3/edit.3
/usr/local/lib/node_modules/npm/man/man3/explore.3
/usr/local/lib/node_modules/npm/man/man3/find.3
/usr/local/lib/node_modules/npm/man/man3/get.3
/usr/local/lib/node_modules/npm/man/man3/help-search.3
/usr/local/lib/node_modules/npm/man/man3/home.3
/usr/local/lib/node_modules/npm/man/man3/init.3
/usr/local/lib/node_modules/npm/man/man3/install.3
/usr/local/lib/node_modules/npm/man/man3/link.3
/usr/local/lib/node_modules/npm/man/man3/list.3
/usr/local/lib/node_modules/npm/man/man3/ln.3
/usr/local/lib/node_modules/npm/man/man3/load.3
/usr/local/lib/node_modules/npm/man/man3/ls.3
/usr/local/lib/node_modules/npm/man/man3/npm.3
/usr/local/lib/node_modules/npm/man/man3/outdated.3
/usr/local/lib/node_modules/npm/man/man3/owner.3
/usr/local/lib/node_modules/npm/man/man3/pack.3
/usr/local/lib/node_modules/npm/man/man3/prefix.3
/usr/local/lib/node_modules/npm/man/man3/prune.3
/usr/local/lib/node_modules/npm/man/man3/publish.3
/usr/local/lib/node_modules/npm/man/man3/rebuild.3
/usr/local/lib/node_modules/npm/man/man3/restart.3
/usr/local/lib/node_modules/npm/man/man3/rm.3
/usr/local/lib/node_modules/npm/man/man3/root.3
/usr/local/lib/node_modules/npm/man/man3/run-script.3
/usr/local/lib/node_modules/npm/man/man3/search.3
/usr/local/lib/node_modules/npm/man/man3/set.3
/usr/local/lib/node_modules/npm/man/man3/shrinkwrap.3
/usr/local/lib/node_modules/npm/man/man3/start.3
/usr/local/lib/node_modules/npm/man/man3/stop.3
/usr/local/lib/node_modules/npm/man/man3/submodule.3
/usr/local/lib/node_modules/npm/man/man3/tag.3
/usr/local/lib/node_modules/npm/man/man3/test.3
/usr/local/lib/node_modules/npm/man/man3/uninstall.3
/usr/local/lib/node_modules/npm/man/man3/unpublish.3
/usr/local/lib/node_modules/npm/man/man3/update.3
/usr/local/lib/node_modules/npm/man/man3/version.3
/usr/local/lib/node_modules/npm/man/man3/view.3
/usr/local/lib/node_modules/npm/man/man3/whoami.3
/usr/local/lib/node_modules/npm/node_modules/abbrev/LICENSE
/usr/local/lib/node_modules/npm/node_modules/abbrev/README.md
/usr/local/lib/node_modules/npm/node_modules/abbrev/lib/abbrev.js
/usr/local/lib/node_modules/npm/node_modules/abbrev/package.json
/usr/local/lib/node_modules/npm/node_modules/ansi/.npmignore
/usr/local/lib/node_modules/npm/node_modules/ansi/README.md
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/beep/index.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/clear/index.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/cursorPosition.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/imgcat/index.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/imgcat/yoshi.png
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/progress/index.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/starwars.js
/usr/local/lib/node_modules/npm/node_modules/ansi/lib/ansi.js
/usr/local/lib/node_modules/npm/node_modules/ansi/lib/newlines.js
/usr/local/lib/node_modules/npm/node_modules/ansi/package.json
/usr/local/lib/node_modules/npm/node_modules/archy/README.markdown
/usr/local/lib/node_modules/npm/node_modules/archy/index.js
/usr/local/lib/node_modules/npm/node_modules/archy/package.json
/usr/local/lib/node_modules/npm/node_modules/block-stream/LICENCE
/usr/local/lib/node_modules/npm/node_modules/block-stream/README.md
/usr/local/lib/node_modules/npm/node_modules/block-stream/bench/block-stream-pause.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/bench/block-stream.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/bench/dropper-pause.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/bench/dropper.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/package.json
/usr/local/lib/node_modules/npm/node_modules/chownr/LICENCE
/usr/local/lib/node_modules/npm/node_modules/chownr/README.md
/usr/local/lib/node_modules/npm/node_modules/chownr/chownr.js
/usr/local/lib/node_modules/npm/node_modules/chownr/package.json
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/.npmignore
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/LICENCE
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/README.md
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/bundle.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/dir-tar.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/dir.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/example.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/ig-tar.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/tar.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/.npmignore
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/LICENSE
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/README.md
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/example/basic.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/package.json
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/package.json
/usr/local/lib/node_modules/npm/node_modules/fstream/.npmignore
/usr/local/lib/node_modules/npm/node_modules/fstream/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/fstream/LICENSE
/usr/local/lib/node_modules/npm/node_modules/fstream/README.md
/usr/local/lib/node_modules/npm/node_modules/fstream/examples/filter-pipe.js
/usr/local/lib/node_modules/npm/node_modules/fstream/examples/pipe.js
/usr/local/lib/node_modules/npm/node_modules/fstream/examples/reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/examples/symlink-write.js
/usr/local/lib/node_modules/npm/node_modules/fstream/fstream.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/abstract.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/collect.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/file-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/file-writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/get-type.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/link-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/link-writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/proxy-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/proxy-writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/socket-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/package.json
/usr/local/lib/node_modules/npm/node_modules/glob/.npmignore
/usr/local/lib/node_modules/npm/node_modules/glob/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/glob/LICENSE
/usr/local/lib/node_modules/npm/node_modules/glob/README.md
/usr/local/lib/node_modules/npm/node_modules/glob/examples/g.js
/usr/local/lib/node_modules/npm/node_modules/glob/examples/usr-local.js
/usr/local/lib/node_modules/npm/node_modules/glob/glob.js
/usr/local/lib/node_modules/npm/node_modules/glob/package.json
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/.npmignore
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/LICENSE
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/README.md
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/package.json
/usr/local/lib/node_modules/npm/node_modules/inherits/LICENSE
/usr/local/lib/node_modules/npm/node_modules/inherits/README.md
/usr/local/lib/node_modules/npm/node_modules/inherits/inherits-old.js
/usr/local/lib/node_modules/npm/node_modules/inherits/inherits.js
/usr/local/lib/node_modules/npm/node_modules/inherits/package.json
/usr/local/lib/node_modules/npm/node_modules/ini/LICENSE
/usr/local/lib/node_modules/npm/node_modules/ini/README.md
/usr/local/lib/node_modules/npm/node_modules/ini/ini.js
/usr/local/lib/node_modules/npm/node_modules/ini/package.json
/usr/local/lib/node_modules/npm/node_modules/init-package-json/README.md
/usr/local/lib/node_modules/npm/node_modules/init-package-json/default-input.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/example.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/init-package-json.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/.npmignore
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/README.md
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/index.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/npm-init/README.md
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/npm-init/init-input.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/npm-init/init.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/npm-init/package.json
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/substack-input.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/package.json
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/package.json
/usr/local/lib/node_modules/npm/node_modules/lockfile/LICENSE
/usr/local/lib/node_modules/npm/node_modules/lockfile/README.md
/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js
/usr/local/lib/node_modules/npm/node_modules/lockfile/package.json
/usr/local/lib/node_modules/npm/node_modules/lru-cache/.npmignore
/usr/local/lib/node_modules/npm/node_modules/lru-cache/AUTHORS
/usr/local/lib/node_modules/npm/node_modules/lru-cache/LICENSE
/usr/local/lib/node_modules/npm/node_modules/lru-cache/README.md
/usr/local/lib/node_modules/npm/node_modules/lru-cache/lib/lru-cache.js
/usr/local/lib/node_modules/npm/node_modules/lru-cache/package.json
/usr/local/lib/node_modules/npm/node_modules/minimatch/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/minimatch/LICENSE
/usr/local/lib/node_modules/npm/node_modules/minimatch/README.md
/usr/local/lib/node_modules/npm/node_modules/minimatch/minimatch.js
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/LICENSE
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/README.md
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/bench.js
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/package.json
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/sigmund.js
/usr/local/lib/node_modules/npm/node_modules/minimatch/package.json
/usr/local/lib/node_modules/npm/node_modules/mkdirp/.npmignore
/usr/local/lib/node_modules/npm/node_modules/mkdirp/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/mkdirp/LICENSE
/usr/local/lib/node_modules/npm/node_modules/mkdirp/README.markdown
/usr/local/lib/node_modules/npm/node_modules/mkdirp/examples/pow.js
/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js
/usr/local/lib/node_modules/npm/node_modules/mkdirp/package.json
/usr/local/lib/node_modules/npm/node_modules/node-gyp/.jshintrc
/usr/local/lib/node_modules/npm/node_modules/node-gyp/.npmignore
/usr/local/lib/node_modules/npm/node_modules/node-gyp/LICENSE
/usr/local/lib/node_modules/npm/node_modules/node-gyp/README.md
/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi
/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/.npmignore
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/AUTHORS
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/DEPS
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/LICENSE
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/MANIFEST
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/OWNERS
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/PRESUBMIT.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/buildbot/buildbot_run.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/codereview.settings
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp.bat
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_dummy.c
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyptest.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSNew.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSProject.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSToolFile.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSUserFile.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSVersion.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/SCons.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/easy_xml.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/easy_xml_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/__init__.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/android.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/dump_dependency_json.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/eclipse.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/gypd.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/gypsh.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/scons.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/mac_tool.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/msvs_emulation.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/ninja_syntax.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/sun_tool.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/win_tool.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xml_fix.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylintrc
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/samples/samples
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/samples/samples.bat
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/setup.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/README
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/Xcode/README
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/Xcode/Specifications/gyp.pbfilespec
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/Xcode/Specifications/gyp.xclangspec
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/README
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/gyp-tests.el
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/gyp.el
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/run-unit-tests.sh
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/testdata/media.gyp
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/testdata/media.gyp.fontified
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/graphviz.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_gyp.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_sln.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_vcproj.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/legacy/common.gypi
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/clean.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/list.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/rebuild.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/remove.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/package.json
/usr/local/lib/node_modules/npm/node_modules/nopt/.npmignore
/usr/local/lib/node_modules/npm/node_modules/nopt/LICENSE
/usr/local/lib/node_modules/npm/node_modules/nopt/README.md
/usr/local/lib/node_modules/npm/node_modules/nopt/bin/nopt.js
/usr/local/lib/node_modules/npm/node_modules/nopt/examples/my-program.js
/usr/local/lib/node_modules/npm/node_modules/nopt/lib/nopt.js
/usr/local/lib/node_modules/npm/node_modules/nopt/package.json
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/README.md
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/index.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/star.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/tag.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/unpublish.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/upload.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/README.md
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/couch-login.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/package.json
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/package.json
/usr/local/lib/node_modules/npm/node_modules/npmconf/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npmconf/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npmconf/README.md
/usr/local/lib/node_modules/npm/node_modules/npmconf/config-defs.js
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/LICENCE
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/index.js
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/node_modules/proto-list/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/node_modules/proto-list/README.md
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/node_modules/proto-list/package.json
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/node_modules/proto-list/proto-list.js
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/package.json
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/readme.markdown
/usr/local/lib/node_modules/npm/node_modules/npmconf/npmconf.js
/usr/local/lib/node_modules/npm/node_modules/npmconf/package.json
/usr/local/lib/node_modules/npm/node_modules/npmlog/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npmlog/README.md
/usr/local/lib/node_modules/npm/node_modules/npmlog/example.js
/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js
/usr/local/lib/node_modules/npm/node_modules/npmlog/package.json
/usr/local/lib/node_modules/npm/node_modules/once/LICENSE
/usr/local/lib/node_modules/npm/node_modules/once/README.md
/usr/local/lib/node_modules/npm/node_modules/once/once.js
/usr/local/lib/node_modules/npm/node_modules/once/package.json
/usr/local/lib/node_modules/npm/node_modules/opener/LICENSE.txt
/usr/local/lib/node_modules/npm/node_modules/opener/README.md
/usr/local/lib/node_modules/npm/node_modules/opener/opener.js
/usr/local/lib/node_modules/npm/node_modules/opener/package.json
/usr/local/lib/node_modules/npm/node_modules/osenv/LICENSE
/usr/local/lib/node_modules/npm/node_modules/osenv/README.md
/usr/local/lib/node_modules/npm/node_modules/osenv/osenv.js
/usr/local/lib/node_modules/npm/node_modules/osenv/package.json
/usr/local/lib/node_modules/npm/node_modules/read-installed/LICENSE
/usr/local/lib/node_modules/npm/node_modules/read-installed/README.md
/usr/local/lib/node_modules/npm/node_modules/read-installed/package.json
/usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js
/usr/local/lib/node_modules/npm/node_modules/read-package-json/LICENSE
/usr/local/lib/node_modules/npm/node_modules/read-package-json/README.md
/usr/local/lib/node_modules/npm/node_modules/read-package-json/package.json
/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js
/usr/local/lib/node_modules/npm/node_modules/read/.npmignore
/usr/local/lib/node_modules/npm/node_modules/read/LICENCE
/usr/local/lib/node_modules/npm/node_modules/read/README.md
/usr/local/lib/node_modules/npm/node_modules/read/example/example.js
/usr/local/lib/node_modules/npm/node_modules/read/lib/read.js
/usr/local/lib/node_modules/npm/node_modules/read/node_modules/mute-stream/LICENSE
/usr/local/lib/node_modules/npm/node_modules/read/node_modules/mute-stream/README.md
/usr/local/lib/node_modules/npm/node_modules/read/node_modules/mute-stream/mute.js
/usr/local/lib/node_modules/npm/node_modules/read/node_modules/mute-stream/package.json
/usr/local/lib/node_modules/npm/node_modules/read/package.json
/usr/local/lib/node_modules/npm/node_modules/request/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/README.md
/usr/local/lib/node_modules/npm/node_modules/request/aws.js
/usr/local/lib/node_modules/npm/node_modules/request/forever.js
/usr/local/lib/node_modules/npm/node_modules/request/main.js
/usr/local/lib/node_modules/npm/node_modules/request/mimetypes.js
/usr/local/lib/node_modules/npm/node_modules/request/oauth.js
/usr/local/lib/node_modules/npm/node_modules/request/package.json
/usr/local/lib/node_modules/npm/node_modules/request/tests/googledoodle.png
/usr/local/lib/node_modules/npm/node_modules/request/tests/run.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/server.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/squid.conf
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.cnf
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.crl
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.crt
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.csr
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.key
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.srl
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.cnf
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.crt
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.csr
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.key
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/npm-ca.crt
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/test.crt
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/test.key
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-body.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-cookie.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-cookiejar.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-defaults.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-errors.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-follow-all-303.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-follow-all.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-headers.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-httpModule.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-https-strict.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-https.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-oauth.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-params.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-pipes.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-pool.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-protocol-changing-redirect.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-proxy.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-qs.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-redirect.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-timeout.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-toJSON.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-tunnel.js
/usr/local/lib/node_modules/npm/node_modules/request/tunnel.js
/usr/local/lib/node_modules/npm/node_modules/request/uuid.js
/usr/local/lib/node_modules/npm/node_modules/request/vendor/cookie/index.js
/usr/local/lib/node_modules/npm/node_modules/request/vendor/cookie/jar.js
/usr/local/lib/node_modules/npm/node_modules/retry/.npmignore
/usr/local/lib/node_modules/npm/node_modules/retry/License
/usr/local/lib/node_modules/npm/node_modules/retry/Makefile
/usr/local/lib/node_modules/npm/node_modules/retry/Readme.md
/usr/local/lib/node_modules/npm/node_modules/retry/equation.gif
/usr/local/lib/node_modules/npm/node_modules/retry/example/dns.js
/usr/local/lib/node_modules/npm/node_modules/retry/index.js
/usr/local/lib/node_modules/npm/node_modules/retry/lib/retry.js
/usr/local/lib/node_modules/npm/node_modules/retry/lib/retry_operation.js
/usr/local/lib/node_modules/npm/node_modules/retry/package.json
/usr/local/lib/node_modules/npm/node_modules/rimraf/AUTHORS
/usr/local/lib/node_modules/npm/node_modules/rimraf/LICENSE
/usr/local/lib/node_modules/npm/node_modules/rimraf/README.md
/usr/local/lib/node_modules/npm/node_modules/rimraf/package.json
/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js
/usr/local/lib/node_modules/npm/node_modules/semver/LICENSE
/usr/local/lib/node_modules/npm/node_modules/semver/README.md
/usr/local/lib/node_modules/npm/node_modules/semver/bin/semver
/usr/local/lib/node_modules/npm/node_modules/semver/package.json
/usr/local/lib/node_modules/npm/node_modules/semver/semver.js
/usr/local/lib/node_modules/npm/node_modules/semver/test.js
/usr/local/lib/node_modules/npm/node_modules/slide/.npmignore
/usr/local/lib/node_modules/npm/node_modules/slide/LICENSE
/usr/local/lib/node_modules/npm/node_modules/slide/README.md
/usr/local/lib/node_modules/npm/node_modules/slide/index.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map-ordered.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/slide.js
/usr/local/lib/node_modules/npm/node_modules/slide/package.json
/usr/local/lib/node_modules/npm/node_modules/tar/.npmignore
/usr/local/lib/node_modules/npm/node_modules/tar/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/tar/LICENCE
/usr/local/lib/node_modules/npm/node_modules/tar/README.md
/usr/local/lib/node_modules/npm/node_modules/tar/examples/extracter.js
/usr/local/lib/node_modules/npm/node_modules/tar/examples/reader.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/buffer-entry.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/entry-writer.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/entry.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/extract.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/global-header-writer.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/header.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/pack.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js
/usr/local/lib/node_modules/npm/node_modules/tar/package.json
/usr/local/lib/node_modules/npm/node_modules/tar/tar.js
/usr/local/lib/node_modules/npm/node_modules/uid-number/LICENCE
/usr/local/lib/node_modules/npm/node_modules/uid-number/README.md
/usr/local/lib/node_modules/npm/node_modules/uid-number/get-uid-gid.js
/usr/local/lib/node_modules/npm/node_modules/uid-number/package.json
/usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js
/usr/local/lib/node_modules/npm/node_modules/which/LICENSE
/usr/local/lib/node_modules/npm/node_modules/which/README.md
/usr/local/lib/node_modules/npm/node_modules/which/bin/which
/usr/local/lib/node_modules/npm/node_modules/which/package.json
/usr/local/lib/node_modules/npm/node_modules/which/which.js
/usr/local/lib/node_modules/npm/package.json
/usr/local/lib/node_modules/npm/scripts/clean-old.sh
/usr/local/lib/node_modules/npm/scripts/doc-build.sh
/usr/local/lib/node_modules/npm/scripts/index-build.js
/usr/local/lib/node_modules/npm/scripts/install.sh
/usr/local/lib/node_modules/npm/scripts/release.sh
/usr/local/lib/node_modules/npm/scripts/relocate.sh
/usr/local/share/man/man1/node.1

%changelog

