<?php
$this->title = $this->project->name . (($note = $this->project->getEAV('note')) ? "({$note})" : '') . ' :: ';
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<h2><?= $this->escape($this->project->name) ?></h2>
<form method="post" action="/project/editnote/<?= $this->project->name ?>">
    <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
    Note: <input type="text" name="note" value="<?= $this->escape($this->project->getEAV('note')) ?>">
    <button type="submit">SAVE</button>
</form>
<form method="post" action="/project/edittemplate/<?= $this->project->name ?>">
    <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
    Template: <select name="template">
        <?php foreach (Project::getTemplates() as $template => $template_desc) { ?>
        <option value="<?= $template ?>"<?= $template == $this->project->getTemplate() ? ' selected="selected"' : '' ?>><?= $this->escape($template_desc) ?></option>
        <?php } ?>
    </select>
    <button type="submit">SAVE</button>
</form>
<h3>deployment:</h3>
<ul>
    <li><code>git remote add middle2 git@<?= GIT_SERVER ?>:<?= $this->project->name ?></code></li>
    <li> or <code>git clone git@<?= GIT_SERVER ?>:<?= $this->project->name ?></code></li>
    <li><code>git push middle2 master</code></li>
</ul>
<hr>
<h3>Custom domains: </h3>
CNAME to <?= $this->project->name ?><?= USER_DOMAIN ?>
<ul>
    <?php foreach ($this->project->custom_domains as $custom_domain) { ?>
    <li>
    <?= $this->escape($custom_domain->domain) ?>
    <a href="/project/deletedomain/<?= $this->project->name ?>?domain=<?= urlencode($custom_domain->domain) ?>" class="post-link confirm" data-confirm="Are you sure delete <?= $this->escape($custom_domain->domain) ?> key">Delete</a>
    </li>
    <?php } ?>
    <li>
    <form method="post" action="/project/adddomain/<?= $this->project->name ?>">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        Add domain: <input type="text" name="domain">
        <input type="submit">
    </form>
    </li>
</ul>
<hr>
<?= $this->partial('/project/cronjob.phtml', array('project' => $this->project)) ?>
<hr>
<h3>Variable: </h3>
<ul>
    <?php foreach ($this->project->variables as $variable) { ?>
    <li>
    <form method="post" action="/project/editvariable/<?= $this->project->name ?>/<?= urlencode($variable->key) ?>"<?= ($variable->is_magic_value) ? ' disabled="disabled"' : '' ?>>
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        <?= $this->escape($variable->key) ?>
        <?php if ($variable->is_magic_value) { ?>
        <input type="text" name="value" value="<?= $this->escape($variable->getValue()) ?>" readonly="readonly">(本數值不能修改只能刪除)
        <?php } else { ?>
        <input type="text" name="value" value="<?= $this->escape($variable->getValue()) ?>">
        <button type="submit">EDIT</button>
        <?php } ?>
    </form>
    <a href="/project/deletevariable/<?= $this->project->name ?>/<?= urlencode($variable->key) ?>" class="post-link confirm" data-confirm="Are you sure delete <?= $this->escape($variable->key) ?> variable">Delete</a>
    </li>
    <?php } ?>
    <li>
    <form method="post" action="/project/addvariable/<?= $this->project->name ?>">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        Variable key: <input type="text" name="key"><br>
        Variable value: <input type="text" name="value">
        <input type="submit">
    </form>
    </li>
</ul>
<textarea readonly="readonly" class="span12">
<?php foreach ($this->project->variables as $variable) { ?>
putenv('<?= $this->escape($variable->key) ?>=<?= $this->escape($variable->getValue()) ?>');
<?php } ?>
</textarea>
<hr>
<h3>Addon: </h3>
<ol>
    <li>
    Add: <button class="post-link" href="/project/addmysqladdon/<?= $this->project->name ?>">MySQL</button>
    <button class="post-link" href="/project/addpgsqladdon/<?= $this->project->name ?>">PgSQL</button>
    </li>
</ol>
<hr>
<h3>Members: </h3>
<ol>
    <?php $is_admin = $this->project->isAdmin($this->user); ?>
    <?php $admin_count = $this->project->members->search(array('is_admin' => 1))->count(); ?>
    <?php foreach ($this->project->members as $project_member) { ?>
    <?php if (!$user = $project_member->user) { continue; } ?>
    <li>
    <?= $this->escape($user->name) ?>
    <?php if ($project_member->is_admin) { ?>[Admin]<?php } ?>
    <?php if ($is_admin and (!$project_member->is_admin or $admin_count != 1)) { ?>
    <a href="/project/deletemember/<?= $this->project->name ?>?account=<?= urlencode($user->name) ?>" class="post-link confirm" data-confirm="Are you sure delete <?= $this->escape($user->name) ?> member">Delete</a>
    <?php } ?>
    </li>
    <?php } ?>

    <?php if ($this->project->isAdmin($this->user)) { ?>
    <form method="post" action="/project/addmember/<?= $this->project->name ?>">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        add member: <input type="text" name="account">
        <input type="submit">
    </form>
    <?php } ?>
</ol>
<hr>
<h3>Node Status</h3>
<table class="table">
    <thead>
        <tr>
            <td>status</td>
            <td>start at</td>
            <td>access at</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach (WebNode::search(array('project_id' => $this->project->id)) as $node) { ?>
    <tr>
        <td><?= $this->escape($node->getStatusWord()) ?></td>
        <td>
            <?= $this->partial('helper/counttime.phtml', array('time' => $node->start_at)) ?>
        </td>
        <td>
            <?= $this->partial('helper/counttime.phtml', array('time' => $node->getAccessAt())) ?>
        </td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<hr>
<h3>Access Log</h3>
<button class="older-button" data-log="access-log">Older</button>
<button class="newer-button" data-log="access-log">Newer</button>
<table class="table log-table" id="access-log" data-url="/project/getlog/<?= $this->project->name ?>"></table>
<hr>
<h3>Error Log</h3>
<button class="older-button" data-log="error-log">Older</button>
<button class="newer-button" data-log="error-log">Newer</button>
<table class="table log-table" id="error-log" data-url="/project/getlog/<?= $this->project->name ?>/error"></table>
<script>
$('.log-table').each(function(){
    var $this = $(this);
    $.get($this.attr('data-url'), function(ret){
        for (var i = 0; i < ret[0].length; i ++) {
            $this.append($('<tr></tr>').html($('<td></td>').text(ret[0][i])).addClass('info'));
        }
        $this.data('cursor-start', ret[1]['cursor-start']);
        $this.data('cursor-end', ret[1]['cursor-end']);
    }, 'json');
});

$('.older-button').click(function(e){
    var $this = $('#' + $(this).attr('data-log'));
    e.preventDefault();
    $.get($this.attr('data-url') + '?before=' + $this.data('cursor-start').join(','), function(ret){
        $this.children('tr').removeClass('info');
        for (var i = ret[0].length - 1; i > 0; i --) {
            $this.prepend($('<tr></tr>').html($('<td></td>').text(ret[0][i])).addClass('info'));
        }
        $this.data('cursor-start', ret[1]['cursor-start']);
    }, 'json');
});

$('.newer-button').click(function(e){
    var $this = $('#' + $(this).attr('data-log'));
    e.preventDefault();
    $.get($this.attr('data-url') + '?after=' + $this.data('cursor-end').join(','), function(ret){
        $this.children('tr').removeClass('info');
        for (var i = 0; i < ret[0].length; i ++) {
            $this.append($('<tr></tr>').html($('<td></td>').text(ret[0][i])).addClass('info'));
        }
        $this.data('cursor-end', ret[1]['cursor-end']);
    }, 'json');
});
</script>
<?= $this->partial('/common/footer.phtml', $this) ?>
