<?= $this->partial('/common/header.phtml', $this) ?>
<h2><?= $this->escape($this->project->name) ?></h2>
<form method="post" action="/project/editnote/<?= $this->project->name ?>">
    <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
    Note: <input type="text" name="note" value="<?= $this->escape($this->project->getEAV('note')) ?>">
    <button type="submit">SAVE</button>
</form>
<form method="post" action="/project/edittemplate/<?= $this->project->name ?>">
    <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
    Template: <select name="template">
        <?php foreach (Project::getTemplates() as $template) { ?>
        <option value="<?= $template ?>"<?= $template == $this->project->getTemplate() ? ' selected="selected"' : '' ?>><?= $template ?></option>
        <?php } ?>
    </select>
    <button type="submit">SAVE</button>
</form>
<h3>deployment:</h3>
<ul>
    <li><code>git remote add middle2 git@<?= GIT_SERVER ?>:<?= $this->project->name ?></code></li>
    <li> or <code>git clone git@<?= GIT_SERVER ?>:<?= $this->project->name ?></code></li>
    <li><code>git push middle2 master</code></li>
</ul>
<hr>
<h3>Custom domains: </h3>
CNAME to <?= $this->project->name ?><?= USER_DOMAIN ?>
<ul>
    <?php foreach ($this->project->custom_domains as $custom_domain) { ?>
    <li>
    <?= $this->escape($custom_domain->domain) ?>
    <a href="/project/deletedomain/<?= $this->project->name ?>?domain=<?= urlencode($custom_domain->domain) ?>" class="post-link confirm" data-confirm="Are you sure delete <?= $this->escape($custom_domain->domain) ?> key">Delete</a>
    </li>
    <?php } ?>
    <li>
    <form method="post" action="/project/adddomain/<?= $this->project->name ?>">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        Add domain: <input type="text" name="domain">
        <input type="submit">
    </form>
    </li>
</ul>
<hr>
<?= $this->partial('/project/cronjob.phtml', array('project' => $this->project)) ?>
<hr>
<h3>Variable: </h3>
<ul>
    <?php foreach ($this->project->variables as $variable) { ?>
    <li>
    <form method="post" action="/project/editvariable/<?= $this->project->name ?>/<?= urlencode($variable->key) ?>">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        <?= $this->escape($variable->key) ?>
        <input type="text" name="value" value="<?= $this->escape($variable->value) ?>">
        <button type="submit">EDIT</button>
    </form>
    <a href="/project/deletevariable/<?= $this->project->name ?>/<?= urlencode($variable->key) ?>" class="post-link confirm" data-confirm="Are you sure delete <?= $this->escape($variable->key) ?> variable">Delete</a>
    </li>
    <?php } ?>
    <li>
    <form method="post" action="/project/addvariable/<?= $this->project->name ?>">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        Variable key: <input type="text" name="key"><br>
        Variable value: <input type="text" name="value">
        <input type="submit">
    </form>
    </li>
</ul>
<textarea readonly="readonly" class="span12">
<?php foreach ($this->project->variables as $variable) { ?>
putenv('<?= $this->escape($variable->key) ?>=<?= $this->escape($variable->value) ?>');
<?php } ?>
</textarea>
<hr>
<h3>Addon: </h3>
<ol>
    <li>
    Add: <button class="post-link" href="/project/addmysqladdon/<?= $this->project->name ?>">MySQL</button>
    <button class="post-link" href="/project/addpgsqladdon/<?= $this->project->name ?>">PgSQL</button>
    </li>
</ol>
<hr>
<h3>Members: </h3>
<ol>
    <?php $is_admin = $this->project->isAdmin($this->user); ?>
    <?php $admin_count = $this->project->members->search(array('is_admin' => 1))->count(); ?>
    <?php foreach ($this->project->members as $project_member) { ?>
    <?php if (!$user = $project_member->user) { continue; } ?>
    <li>
    <?= $this->escape($user->name) ?>
    <?php if ($project_member->is_admin) { ?>[Admin]<?php } ?>
    <?php if ($is_admin and (!$project_member->is_admin or $admin_count != 1)) { ?>
    <a href="/project/deletemember/<?= $this->project->name ?>?account=<?= urlencode($user->name) ?>" class="post-link confirm" data-confirm="Are you sure delete <?= $this->escape($user->name) ?> member">Delete</a>
    <?php } ?>
    </li>
    <?php } ?>

    <?php if ($this->project->isAdmin($this->user)) { ?>
    <form method="post" action="/project/addmember/<?= $this->project->name ?>">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        add member: <input type="text" name="account">
        <input type="submit">
    </form>
    <?php } ?>
</ol>
Log
<pre>
<?php
$cmd = "tail -n 100 /srv/logs/scribed/app-" . $this->project->name . "/app-" . $this->project->name . '_current';
echo `$cmd`;
?>
</pre>
<?= $this->partial('/common/footer.phtml', $this) ?>
