<?= $this->partial('/common/header.phtml', $this) ?>
<h2>Projects</h2>
<ul>
    <?php foreach ($this->user->project_members as $project_member) { ?>
    <?php if (!$project = $project_member->project) { continue; } ?>
    <li>
    <a href="/project/detail/<?= $project->name ?>"><?= $this->escape($project->name) ?></a>
    <?= $this->escape($project->getEAV('note')) ?>
    <a href="http://<?= $project->getFirstDomain() ?>" target="_blank">[new window]</a>
    </li>
    <?php } ?>
    <li>
    <form method="post" action="/user/addproject">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        Add project: <input type="text" name="name" placeholder="Project note(optioanl)">
        <input type="submit">
    </form>
    </li>
</ul>
<hr>
<h2>SSH Keys</h2>
<ul>
    <?php foreach ($this->user->keys as $key) { ?>
    <li title="<?= $this->escape($key->key_body) ?>">
        <?= $this->escape($key->getKeyUser()) ?>: <?= trim(chunk_split($key->key_fingerprint, 2, ':'), ':') ?>
        <a href="/user/deletekey/<?= $key->id ?>" class="post-link confirm" data-confirm="Are you sure delete <?= $this->escape($key->getKeyUser()) ?> key">Delete</a>
    </li>
    <?php } ?>
    <li>
    <form method="post" action="/user/addkey">
        Add key:
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        <input type="text" name="key" placeholder="add ssh public key body here...">
        <input type="submit">
    </form>
    </li>
</ul>

<?= $this->partial('/common/footer.phtml', $this) ?>
