<?= $this->partial('/common/header.phtml', $this) ?>
<h2>Projects</h2>
<?php if ($this->try_mode) { ?>
<div style="color:lightcoral;margin-bottom:15px;">目前為試用模式，project 數量上限為 <?= $this->project_limit ?></div>
<?php $disabled = $this->project_count >= $this->project_limit ? ' disabled="disabled"' : '' ?>
<?php } ?>
<ul>
    <?php foreach ($this->user->project_members as $project_member) { ?>
    <?php if (!$project = $project_member->project) { continue; } ?>
    <li>
    <a href="/project/detail/<?= $project->name ?>"><?= $this->escape($project->name) ?></a>
    <?= $this->escape($project->getEAV('note')) ?>
    <a href="http://<?= $project->getFirstDomain() ?>" target="_blank">[new window]</a>
    <?php $owner = User::find($project_member->project->created_by) ?>
    <?php  if ($owner->id != $this->user->id ) { ?>
    <?= "Admin: " . $owner->name ?>
    <?php } ?>
    </li>
    <?php } ?>
    <li>
    <form method="post" action="/user/addproject">
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        Add project: <input type="text" name="name" placeholder="Project note(optioanl)"<?= $disabled ?>>
        <input type="submit"<?= $disabled ?>>
    </form>
    </li>
</ul>
<hr>
<h2>SSH Keys</h2>
<ul>
    <?php foreach ($this->user->keys as $key) { ?>
    <li title="<?= $this->escape($key->key_body) ?>">
        <?= $this->escape($key->getKeyUser()) ?>: <?= trim(chunk_split($key->key_fingerprint, 2, ':'), ':') ?>
        <a href="/user/deletekey/<?= $key->id ?>" class="post-link confirm" data-confirm="Are you sure delete <?= $this->escape($key->getKeyUser()) ?> key">Delete</a>
    </li>
    <?php } ?>
    <li>
    <form method="post" action="/user/addkey">
        Add key:
        <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
        <input type="text" name="key" placeholder="add ssh public key body here...">
        <input type="submit">
    </form>
    </li>
</ul>
<hr>
<h2>Change Password</h2>
<form method="post" action="/user/changepassword">
    <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
    Old Password: <input type="password" name="oldpassword"><br>
    New Password: <input type="password" name="newpassword"><br>
    Again: <input type="password" name="newpassword2"><br>
    <input type="submit">
</form>
<?= $this->partial('/common/footer.phtml', $this) ?>
