Name:		httpd

Version:	2.2.24
Release:	1%{?dist}
Summary:	httpd

Group:		Hisoku
License:	No
URL:		http://hisoku.ronny.tw/
Source0:	httpd-2.2.24.tar.gz
BuildRoot:	%(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

%description


%prep
%setup -q


%build
%configure --enable-rewrite --enable-deflate --with-included-apr --with-mpm=worker --sysconfdir=/etc/httpd
make %{?_smp_mflags}
cd modules/fastcgi
make top_dir=../../
cd ../../
cd modules/mod_rpaf
make
cd ../../

%install
rm -rf %{buildroot}
make install DESTDIR=%{buildroot}
mkdir %{buildroot}/modules/
cp modules/fastcgi/.libs/mod_fastcgi.so %{buildroot}/modules/
cp modules/mod_rpaf/.libs/mod_rpaf.so %{buildroot}/modules/

%clean
rm -rf %{buildroot}


%files
%defattr(-,root,root,-)
%doc
/etc/httpd/extra/httpd-autoindex.conf
/etc/httpd/extra/httpd-dav.conf
/etc/httpd/extra/httpd-default.conf
/etc/httpd/extra/httpd-info.conf
/etc/httpd/extra/httpd-languages.conf
/etc/httpd/extra/httpd-manual.conf
/etc/httpd/extra/httpd-mpm.conf
/etc/httpd/extra/httpd-multilang-errordoc.conf
/etc/httpd/extra/httpd-ssl.conf
/etc/httpd/extra/httpd-userdir.conf
/etc/httpd/extra/httpd-vhosts.conf
/etc/httpd/httpd.conf
/etc/httpd/magic
/etc/httpd/mime.types
/etc/httpd/original/extra/httpd-autoindex.conf
/etc/httpd/original/extra/httpd-dav.conf
/etc/httpd/original/extra/httpd-default.conf
/etc/httpd/original/extra/httpd-info.conf
/etc/httpd/original/extra/httpd-languages.conf
/etc/httpd/original/extra/httpd-manual.conf
/etc/httpd/original/extra/httpd-mpm.conf
/etc/httpd/original/extra/httpd-multilang-errordoc.conf
/etc/httpd/original/extra/httpd-ssl.conf
/etc/httpd/original/extra/httpd-userdir.conf
/etc/httpd/original/extra/httpd-vhosts.conf
/etc/httpd/original/httpd.conf
/modules/mod_fastcgi.so
/modules/mod_rpaf.so
/usr/bin/apr-1-config
/usr/bin/apu-1-config
/usr/include/ap_compat.h
/usr/include/ap_config.h
/usr/include/ap_config_auto.h
/usr/include/ap_config_layout.h
/usr/include/ap_listen.h
/usr/include/ap_mmn.h
/usr/include/ap_mpm.h
/usr/include/ap_provider.h
/usr/include/ap_regex.h
/usr/include/ap_regkey.h
/usr/include/ap_release.h
/usr/include/apr.h
/usr/include/apr_allocator.h
/usr/include/apr_anylock.h
/usr/include/apr_atomic.h
/usr/include/apr_base64.h
/usr/include/apr_buckets.h
/usr/include/apr_crypto.h
/usr/include/apr_date.h
/usr/include/apr_dbd.h
/usr/include/apr_dbm.h
/usr/include/apr_dso.h
/usr/include/apr_env.h
/usr/include/apr_errno.h
/usr/include/apr_file_info.h
/usr/include/apr_file_io.h
/usr/include/apr_fnmatch.h
/usr/include/apr_general.h
/usr/include/apr_getopt.h
/usr/include/apr_global_mutex.h
/usr/include/apr_hash.h
/usr/include/apr_hooks.h
/usr/include/apr_inherit.h
/usr/include/apr_ldap.h
/usr/include/apr_ldap_init.h
/usr/include/apr_ldap_option.h
/usr/include/apr_ldap_rebind.h
/usr/include/apr_ldap_url.h
/usr/include/apr_lib.h
/usr/include/apr_md4.h
/usr/include/apr_md5.h
/usr/include/apr_memcache.h
/usr/include/apr_mmap.h
/usr/include/apr_network_io.h
/usr/include/apr_optional.h
/usr/include/apr_optional_hooks.h
/usr/include/apr_poll.h
/usr/include/apr_pools.h
/usr/include/apr_portable.h
/usr/include/apr_proc_mutex.h
/usr/include/apr_queue.h
/usr/include/apr_random.h
/usr/include/apr_reslist.h
/usr/include/apr_ring.h
/usr/include/apr_rmm.h
/usr/include/apr_sdbm.h
/usr/include/apr_sha1.h
/usr/include/apr_shm.h
/usr/include/apr_signal.h
/usr/include/apr_strings.h
/usr/include/apr_strmatch.h
/usr/include/apr_support.h
/usr/include/apr_tables.h
/usr/include/apr_thread_cond.h
/usr/include/apr_thread_mutex.h
/usr/include/apr_thread_pool.h
/usr/include/apr_thread_proc.h
/usr/include/apr_thread_rwlock.h
/usr/include/apr_time.h
/usr/include/apr_uri.h
/usr/include/apr_user.h
/usr/include/apr_uuid.h
/usr/include/apr_version.h
/usr/include/apr_want.h
/usr/include/apr_xlate.h
/usr/include/apr_xml.h
/usr/include/apu.h
/usr/include/apu_errno.h
/usr/include/apu_version.h
/usr/include/apu_want.h
/usr/include/fdqueue.h
/usr/include/http_config.h
/usr/include/http_connection.h
/usr/include/http_core.h
/usr/include/http_log.h
/usr/include/http_main.h
/usr/include/http_protocol.h
/usr/include/http_request.h
/usr/include/http_vhost.h
/usr/include/httpd.h
/usr/include/mod_auth.h
/usr/include/mod_cgi.h
/usr/include/mod_core.h
/usr/include/mod_dav.h
/usr/include/mod_dbd.h
/usr/include/mod_include.h
/usr/include/mod_log_config.h
/usr/include/mod_proxy.h
/usr/include/mod_rewrite.h
/usr/include/mod_ssl.h
/usr/include/mod_status.h
/usr/include/mpm.h
/usr/include/mpm_common.h
/usr/include/mpm_default.h
/usr/include/os.h
/usr/include/pod.h
/usr/include/scoreboard.h
/usr/include/unixd.h
/usr/include/util_cfgtree.h
/usr/include/util_charset.h
/usr/include/util_ebcdic.h
/usr/include/util_filter.h
/usr/include/util_ldap.h
/usr/include/util_md5.h
/usr/include/util_script.h
/usr/include/util_time.h
/usr/include/util_xml.h
/usr/lib64/apr-util-1/apr_dbd_pgsql-1.so
/usr/lib64/apr-util-1/apr_dbd_pgsql.a
/usr/lib64/apr-util-1/apr_dbd_pgsql.la
/usr/lib64/apr-util-1/apr_dbd_pgsql.so
/usr/lib64/apr-util-1/apr_dbd_sqlite3-1.so
/usr/lib64/apr-util-1/apr_dbd_sqlite3.a
/usr/lib64/apr-util-1/apr_dbd_sqlite3.la
/usr/lib64/apr-util-1/apr_dbd_sqlite3.so
/usr/lib64/apr.exp
/usr/lib64/aprutil.exp
/usr/lib64/libapr-1.a
/usr/lib64/libapr-1.la
/usr/lib64/libapr-1.so
/usr/lib64/libapr-1.so.0
/usr/lib64/libapr-1.so.0.4.6
/usr/lib64/libaprutil-1.a
/usr/lib64/libaprutil-1.la
/usr/lib64/libaprutil-1.so
/usr/lib64/libaprutil-1.so.0
/usr/lib64/libaprutil-1.so.0.4.1
/usr/lib64/pkgconfig/apr-1.pc
/usr/lib64/pkgconfig/apr-util-1.pc
/usr/libexec/httpd.exp
/usr/sbin/ab
/usr/sbin/apachectl
/usr/sbin/apxs
/usr/sbin/checkgid
/usr/sbin/dbmmanage
/usr/sbin/envvars
/usr/sbin/envvars-std
/usr/sbin/htcacheclean
/usr/sbin/htdbm
/usr/sbin/htdigest
/usr/sbin/htpasswd
/usr/sbin/httpd
/usr/sbin/httxt2dbm
/usr/sbin/logresolve
/usr/sbin/rotatelogs
/usr/share/build/apr_rules.mk
/usr/share/build/config.nice
/usr/share/build/config_vars.mk
/usr/share/build/instdso.sh
/usr/share/build/library.mk
/usr/share/build/libtool
/usr/share/build/ltlib.mk
/usr/share/build/make_exports.awk
/usr/share/build/make_var_export.awk
/usr/share/build/mkdir.sh
/usr/share/build/program.mk
/usr/share/build/rules.mk
/usr/share/build/special.mk
/usr/share/cgi-bin/printenv
/usr/share/cgi-bin/test-cgi
/usr/share/error/HTTP_BAD_GATEWAY.html.var
/usr/share/error/HTTP_BAD_REQUEST.html.var
/usr/share/error/HTTP_FORBIDDEN.html.var
/usr/share/error/HTTP_GONE.html.var
/usr/share/error/HTTP_INTERNAL_SERVER_ERROR.html.var
/usr/share/error/HTTP_LENGTH_REQUIRED.html.var
/usr/share/error/HTTP_METHOD_NOT_ALLOWED.html.var
/usr/share/error/HTTP_NOT_FOUND.html.var
/usr/share/error/HTTP_NOT_IMPLEMENTED.html.var
/usr/share/error/HTTP_PRECONDITION_FAILED.html.var
/usr/share/error/HTTP_REQUEST_ENTITY_TOO_LARGE.html.var
/usr/share/error/HTTP_REQUEST_TIME_OUT.html.var
/usr/share/error/HTTP_REQUEST_URI_TOO_LARGE.html.var
/usr/share/error/HTTP_SERVICE_UNAVAILABLE.html.var
/usr/share/error/HTTP_UNAUTHORIZED.html.var
/usr/share/error/HTTP_UNSUPPORTED_MEDIA_TYPE.html.var
/usr/share/error/HTTP_VARIANT_ALSO_VARIES.html.var
/usr/share/error/README
/usr/share/error/contact.html.var
/usr/share/error/include/bottom.html
/usr/share/error/include/spacer.html
/usr/share/error/include/top.html
/usr/share/htdocs/index.html
/usr/share/icons/README
/usr/share/icons/README.html
/usr/share/icons/a.gif
/usr/share/icons/a.png
/usr/share/icons/alert.black.gif
/usr/share/icons/alert.black.png
/usr/share/icons/alert.red.gif
/usr/share/icons/alert.red.png
/usr/share/icons/apache_pb.gif
/usr/share/icons/apache_pb.png
/usr/share/icons/apache_pb2.gif
/usr/share/icons/apache_pb2.png
/usr/share/icons/apache_pb2_ani.gif
/usr/share/icons/back.gif
/usr/share/icons/back.png
/usr/share/icons/ball.gray.gif
/usr/share/icons/ball.gray.png
/usr/share/icons/ball.red.gif
/usr/share/icons/ball.red.png
/usr/share/icons/binary.gif
/usr/share/icons/binary.png
/usr/share/icons/binhex.gif
/usr/share/icons/binhex.png
/usr/share/icons/blank.gif
/usr/share/icons/blank.png
/usr/share/icons/bomb.gif
/usr/share/icons/bomb.png
/usr/share/icons/box1.gif
/usr/share/icons/box1.png
/usr/share/icons/box2.gif
/usr/share/icons/box2.png
/usr/share/icons/broken.gif
/usr/share/icons/broken.png
/usr/share/icons/burst.gif
/usr/share/icons/burst.png
/usr/share/icons/c.gif
/usr/share/icons/c.png
/usr/share/icons/comp.blue.gif
/usr/share/icons/comp.blue.png
/usr/share/icons/comp.gray.gif
/usr/share/icons/comp.gray.png
/usr/share/icons/compressed.gif
/usr/share/icons/compressed.png
/usr/share/icons/continued.gif
/usr/share/icons/continued.png
/usr/share/icons/dir.gif
/usr/share/icons/dir.png
/usr/share/icons/diskimg.gif
/usr/share/icons/diskimg.png
/usr/share/icons/down.gif
/usr/share/icons/down.png
/usr/share/icons/dvi.gif
/usr/share/icons/dvi.png
/usr/share/icons/f.gif
/usr/share/icons/f.png
/usr/share/icons/folder.gif
/usr/share/icons/folder.open.gif
/usr/share/icons/folder.open.png
/usr/share/icons/folder.png
/usr/share/icons/folder.sec.gif
/usr/share/icons/folder.sec.png
/usr/share/icons/forward.gif
/usr/share/icons/forward.png
/usr/share/icons/generic.gif
/usr/share/icons/generic.png
/usr/share/icons/generic.red.gif
/usr/share/icons/generic.red.png
/usr/share/icons/generic.sec.gif
/usr/share/icons/generic.sec.png
/usr/share/icons/hand.right.gif
/usr/share/icons/hand.right.png
/usr/share/icons/hand.up.gif
/usr/share/icons/hand.up.png
/usr/share/icons/icon.sheet.gif
/usr/share/icons/icon.sheet.png
/usr/share/icons/image1.gif
/usr/share/icons/image1.png
/usr/share/icons/image2.gif
/usr/share/icons/image2.png
/usr/share/icons/image3.gif
/usr/share/icons/image3.png
/usr/share/icons/index.gif
/usr/share/icons/index.png
/usr/share/icons/layout.gif
/usr/share/icons/layout.png
/usr/share/icons/left.gif
/usr/share/icons/left.png
/usr/share/icons/link.gif
/usr/share/icons/link.png
/usr/share/icons/movie.gif
/usr/share/icons/movie.png
/usr/share/icons/p.gif
/usr/share/icons/p.png
/usr/share/icons/patch.gif
/usr/share/icons/patch.png
/usr/share/icons/pdf.gif
/usr/share/icons/pdf.png
/usr/share/icons/pie0.gif
/usr/share/icons/pie0.png
/usr/share/icons/pie1.gif
/usr/share/icons/pie1.png
/usr/share/icons/pie2.gif
/usr/share/icons/pie2.png
/usr/share/icons/pie3.gif
/usr/share/icons/pie3.png
/usr/share/icons/pie4.gif
/usr/share/icons/pie4.png
/usr/share/icons/pie5.gif
/usr/share/icons/pie5.png
/usr/share/icons/pie6.gif
/usr/share/icons/pie6.png
/usr/share/icons/pie7.gif
/usr/share/icons/pie7.png
/usr/share/icons/pie8.gif
/usr/share/icons/pie8.png
/usr/share/icons/portal.gif
/usr/share/icons/portal.png
/usr/share/icons/ps.gif
/usr/share/icons/ps.png
/usr/share/icons/quill.gif
/usr/share/icons/quill.png
/usr/share/icons/right.gif
/usr/share/icons/right.png
/usr/share/icons/screw1.gif
/usr/share/icons/screw1.png
/usr/share/icons/screw2.gif
/usr/share/icons/screw2.png
/usr/share/icons/script.gif
/usr/share/icons/script.png
/usr/share/icons/small/back.gif
/usr/share/icons/small/back.png
/usr/share/icons/small/binary.gif
/usr/share/icons/small/binary.png
/usr/share/icons/small/binhex.gif
/usr/share/icons/small/binhex.png
/usr/share/icons/small/blank.gif
/usr/share/icons/small/blank.png
/usr/share/icons/small/broken.gif
/usr/share/icons/small/broken.png
/usr/share/icons/small/burst.gif
/usr/share/icons/small/burst.png
/usr/share/icons/small/comp1.gif
/usr/share/icons/small/comp1.png
/usr/share/icons/small/comp2.gif
/usr/share/icons/small/comp2.png
/usr/share/icons/small/compressed.gif
/usr/share/icons/small/compressed.png
/usr/share/icons/small/continued.gif
/usr/share/icons/small/continued.png
/usr/share/icons/small/dir.gif
/usr/share/icons/small/dir.png
/usr/share/icons/small/dir2.gif
/usr/share/icons/small/dir2.png
/usr/share/icons/small/doc.gif
/usr/share/icons/small/doc.png
/usr/share/icons/small/forward.gif
/usr/share/icons/small/forward.png
/usr/share/icons/small/generic.gif
/usr/share/icons/small/generic.png
/usr/share/icons/small/generic2.gif
/usr/share/icons/small/generic2.png
/usr/share/icons/small/generic3.gif
/usr/share/icons/small/generic3.png
/usr/share/icons/small/image.gif
/usr/share/icons/small/image.png
/usr/share/icons/small/image2.gif
/usr/share/icons/small/image2.png
/usr/share/icons/small/index.gif
/usr/share/icons/small/index.png
/usr/share/icons/small/key.gif
/usr/share/icons/small/key.png
/usr/share/icons/small/movie.gif
/usr/share/icons/small/movie.png
/usr/share/icons/small/patch.gif
/usr/share/icons/small/patch.png
/usr/share/icons/small/ps.gif
/usr/share/icons/small/ps.png
/usr/share/icons/small/rainbow.gif
/usr/share/icons/small/rainbow.png
/usr/share/icons/small/sound.gif
/usr/share/icons/small/sound.png
/usr/share/icons/small/sound2.gif
/usr/share/icons/small/sound2.png
/usr/share/icons/small/tar.gif
/usr/share/icons/small/tar.png
/usr/share/icons/small/text.gif
/usr/share/icons/small/text.png
/usr/share/icons/small/transfer.gif
/usr/share/icons/small/transfer.png
/usr/share/icons/small/unknown.gif
/usr/share/icons/small/unknown.png
/usr/share/icons/small/uu.gif
/usr/share/icons/small/uu.png
/usr/share/icons/sound1.gif
/usr/share/icons/sound1.png
/usr/share/icons/sound2.gif
/usr/share/icons/sound2.png
/usr/share/icons/sphere1.gif
/usr/share/icons/sphere1.png
/usr/share/icons/sphere2.gif
/usr/share/icons/sphere2.png
/usr/share/icons/tar.gif
/usr/share/icons/tar.png
/usr/share/icons/tex.gif
/usr/share/icons/tex.png
/usr/share/icons/text.gif
/usr/share/icons/text.png
/usr/share/icons/transfer.gif
/usr/share/icons/transfer.png
/usr/share/icons/unknown.gif
/usr/share/icons/unknown.png
/usr/share/icons/up.gif
/usr/share/icons/up.png
/usr/share/icons/uu.gif
/usr/share/icons/uu.png
/usr/share/icons/uuencoded.gif
/usr/share/icons/uuencoded.png
/usr/share/icons/world1.gif
/usr/share/icons/world1.png
/usr/share/icons/world2.gif
/usr/share/icons/world2.png
/usr/share/man/man1/dbmmanage.1.gz
/usr/share/man/man1/htdbm.1.gz
/usr/share/man/man1/htdigest.1.gz
/usr/share/man/man1/htpasswd.1.gz
/usr/share/man/man1/httxt2dbm.1.gz
/usr/share/man/man8/ab.8.gz
/usr/share/man/man8/apachectl.8.gz
/usr/share/man/man8/apxs.8.gz
/usr/share/man/man8/htcacheclean.8.gz
/usr/share/man/man8/httpd.8.gz
/usr/share/man/man8/logresolve.8.gz
/usr/share/man/man8/rotatelogs.8.gz
/usr/share/man/man8/suexec.8.gz
/usr/share/manual/LICENSE
/usr/share/manual/bind.html
/usr/share/manual/bind.html.de
/usr/share/manual/bind.html.en
/usr/share/manual/bind.html.fr
/usr/share/manual/bind.html.ja.utf8
/usr/share/manual/bind.html.ko.euc-kr
/usr/share/manual/bind.html.tr.utf8
/usr/share/manual/caching.html
/usr/share/manual/caching.html.en
/usr/share/manual/caching.html.fr
/usr/share/manual/caching.html.tr.utf8
/usr/share/manual/configuring.html
/usr/share/manual/configuring.html.de
/usr/share/manual/configuring.html.en
/usr/share/manual/configuring.html.fr
/usr/share/manual/configuring.html.ja.utf8
/usr/share/manual/configuring.html.ko.euc-kr
/usr/share/manual/configuring.html.tr.utf8
/usr/share/manual/content-negotiation.html
/usr/share/manual/content-negotiation.html.en
/usr/share/manual/content-negotiation.html.fr
/usr/share/manual/content-negotiation.html.ja.utf8
/usr/share/manual/content-negotiation.html.ko.euc-kr
/usr/share/manual/content-negotiation.html.tr.utf8
/usr/share/manual/convenience.map
/usr/share/manual/custom-error.html
/usr/share/manual/custom-error.html.en
/usr/share/manual/custom-error.html.es
/usr/share/manual/custom-error.html.ja.utf8
/usr/share/manual/custom-error.html.ko.euc-kr
/usr/share/manual/custom-error.html.tr.utf8
/usr/share/manual/developer/API.html
/usr/share/manual/developer/API.html.en
/usr/share/manual/developer/debugging.html
/usr/share/manual/developer/debugging.html.en
/usr/share/manual/developer/documenting.html
/usr/share/manual/developer/documenting.html.en
/usr/share/manual/developer/documenting.html.zh-cn
/usr/share/manual/developer/filters.html
/usr/share/manual/developer/filters.html.en
/usr/share/manual/developer/hooks.html
/usr/share/manual/developer/hooks.html.en
/usr/share/manual/developer/index.html
/usr/share/manual/developer/index.html.en
/usr/share/manual/developer/index.html.zh-cn
/usr/share/manual/developer/modules.html
/usr/share/manual/developer/modules.html.en
/usr/share/manual/developer/modules.html.ja.utf8
/usr/share/manual/developer/request.html
/usr/share/manual/developer/request.html.en
/usr/share/manual/developer/thread_safety.html
/usr/share/manual/developer/thread_safety.html.en
/usr/share/manual/dns-caveats.html
/usr/share/manual/dns-caveats.html.en
/usr/share/manual/dns-caveats.html.ja.utf8
/usr/share/manual/dns-caveats.html.ko.euc-kr
/usr/share/manual/dns-caveats.html.tr.utf8
/usr/share/manual/dso.html
/usr/share/manual/dso.html.en
/usr/share/manual/dso.html.ja.utf8
/usr/share/manual/dso.html.ko.euc-kr
/usr/share/manual/dso.html.tr.utf8
/usr/share/manual/env.html
/usr/share/manual/env.html.en
/usr/share/manual/env.html.ja.utf8
/usr/share/manual/env.html.ko.euc-kr
/usr/share/manual/env.html.tr.utf8
/usr/share/manual/faq/index.html
/usr/share/manual/faq/index.html.en
/usr/share/manual/faq/index.html.tr.utf8
/usr/share/manual/faq/index.html.zh-cn
/usr/share/manual/filter.html
/usr/share/manual/filter.html.en
/usr/share/manual/filter.html.es
/usr/share/manual/filter.html.fr
/usr/share/manual/filter.html.ja.utf8
/usr/share/manual/filter.html.ko.euc-kr
/usr/share/manual/filter.html.tr.utf8
/usr/share/manual/glossary.html
/usr/share/manual/glossary.html.de
/usr/share/manual/glossary.html.en
/usr/share/manual/glossary.html.es
/usr/share/manual/glossary.html.fr
/usr/share/manual/glossary.html.ja.utf8
/usr/share/manual/glossary.html.ko.euc-kr
/usr/share/manual/glossary.html.tr.utf8
/usr/share/manual/handler.html
/usr/share/manual/handler.html.en
/usr/share/manual/handler.html.es
/usr/share/manual/handler.html.fr
/usr/share/manual/handler.html.ja.utf8
/usr/share/manual/handler.html.ko.euc-kr
/usr/share/manual/handler.html.ru.koi8-r
/usr/share/manual/handler.html.tr.utf8
/usr/share/manual/handler.html.zh-cn
/usr/share/manual/howto/access.html
/usr/share/manual/howto/access.html.en
/usr/share/manual/howto/auth.html
/usr/share/manual/howto/auth.html.en
/usr/share/manual/howto/auth.html.fr
/usr/share/manual/howto/auth.html.ja.utf8
/usr/share/manual/howto/auth.html.ko.euc-kr
/usr/share/manual/howto/auth.html.tr.utf8
/usr/share/manual/howto/cgi.html
/usr/share/manual/howto/cgi.html.en
/usr/share/manual/howto/cgi.html.ja.utf8
/usr/share/manual/howto/cgi.html.ko.euc-kr
/usr/share/manual/howto/htaccess.html
/usr/share/manual/howto/htaccess.html.en
/usr/share/manual/howto/htaccess.html.fr
/usr/share/manual/howto/htaccess.html.ja.utf8
/usr/share/manual/howto/htaccess.html.ko.euc-kr
/usr/share/manual/howto/htaccess.html.pt-br
/usr/share/manual/howto/index.html
/usr/share/manual/howto/index.html.en
/usr/share/manual/howto/index.html.ja.utf8
/usr/share/manual/howto/index.html.ko.euc-kr
/usr/share/manual/howto/index.html.zh-cn
/usr/share/manual/howto/public_html.html
/usr/share/manual/howto/public_html.html.en
/usr/share/manual/howto/public_html.html.ja.utf8
/usr/share/manual/howto/public_html.html.ko.euc-kr
/usr/share/manual/howto/public_html.html.tr.utf8
/usr/share/manual/howto/ssi.html
/usr/share/manual/howto/ssi.html.en
/usr/share/manual/howto/ssi.html.ja.utf8
/usr/share/manual/howto/ssi.html.ko.euc-kr
/usr/share/manual/images/apache_header.gif
/usr/share/manual/images/caching_fig1.gif
/usr/share/manual/images/caching_fig1.png
/usr/share/manual/images/caching_fig1.tr.png
/usr/share/manual/images/custom_errordocs.png
/usr/share/manual/images/down.gif
/usr/share/manual/images/favicon.ico
/usr/share/manual/images/feather.gif
/usr/share/manual/images/feather.png
/usr/share/manual/images/filter_arch.png
/usr/share/manual/images/filter_arch.tr.png
/usr/share/manual/images/home.gif
/usr/share/manual/images/index.gif
/usr/share/manual/images/left.gif
/usr/share/manual/images/mod_filter_new.gif
/usr/share/manual/images/mod_filter_new.png
/usr/share/manual/images/mod_filter_new.tr.png
/usr/share/manual/images/mod_filter_old.gif
/usr/share/manual/images/mod_rewrite_fig1.gif
/usr/share/manual/images/mod_rewrite_fig1.png
/usr/share/manual/images/mod_rewrite_fig2.gif
/usr/share/manual/images/mod_rewrite_fig2.png
/usr/share/manual/images/pixel.gif
/usr/share/manual/images/rewrite_backreferences.png
/usr/share/manual/images/rewrite_rule_flow.png
/usr/share/manual/images/right.gif
/usr/share/manual/images/ssl_intro_fig1.gif
/usr/share/manual/images/ssl_intro_fig1.png
/usr/share/manual/images/ssl_intro_fig2.gif
/usr/share/manual/images/ssl_intro_fig2.png
/usr/share/manual/images/ssl_intro_fig3.gif
/usr/share/manual/images/ssl_intro_fig3.png
/usr/share/manual/images/sub.gif
/usr/share/manual/images/syntax_rewritecond.png
/usr/share/manual/images/syntax_rewriterule.png
/usr/share/manual/images/up.gif
/usr/share/manual/index.html
/usr/share/manual/index.html.de
/usr/share/manual/index.html.en
/usr/share/manual/index.html.es
/usr/share/manual/index.html.fr
/usr/share/manual/index.html.ja.utf8
/usr/share/manual/index.html.ko.euc-kr
/usr/share/manual/index.html.pt-br
/usr/share/manual/index.html.tr.utf8
/usr/share/manual/index.html.zh-cn
/usr/share/manual/install.html
/usr/share/manual/install.html.de
/usr/share/manual/install.html.en
/usr/share/manual/install.html.es
/usr/share/manual/install.html.fr
/usr/share/manual/install.html.ja.utf8
/usr/share/manual/install.html.ko.euc-kr
/usr/share/manual/install.html.tr.utf8
/usr/share/manual/invoking.html
/usr/share/manual/invoking.html.de
/usr/share/manual/invoking.html.en
/usr/share/manual/invoking.html.es
/usr/share/manual/invoking.html.fr
/usr/share/manual/invoking.html.ja.utf8
/usr/share/manual/invoking.html.ko.euc-kr
/usr/share/manual/invoking.html.ru.koi8-r
/usr/share/manual/invoking.html.tr.utf8
/usr/share/manual/license.html
/usr/share/manual/license.html.en
/usr/share/manual/logs.html
/usr/share/manual/logs.html.en
/usr/share/manual/logs.html.fr
/usr/share/manual/logs.html.ja.utf8
/usr/share/manual/logs.html.ko.euc-kr
/usr/share/manual/logs.html.tr.utf8
/usr/share/manual/misc/index.html
/usr/share/manual/misc/index.html.en
/usr/share/manual/misc/index.html.ko.euc-kr
/usr/share/manual/misc/index.html.tr.utf8
/usr/share/manual/misc/index.html.zh-cn
/usr/share/manual/misc/password_encryptions.html
/usr/share/manual/misc/password_encryptions.html.en
/usr/share/manual/misc/perf-tuning.html
/usr/share/manual/misc/perf-tuning.html.en
/usr/share/manual/misc/perf-tuning.html.ko.euc-kr
/usr/share/manual/misc/perf-tuning.html.tr.utf8
/usr/share/manual/misc/relevant_standards.html
/usr/share/manual/misc/relevant_standards.html.en
/usr/share/manual/misc/relevant_standards.html.ko.euc-kr
/usr/share/manual/misc/rewriteguide.html
/usr/share/manual/misc/rewriteguide.html.en
/usr/share/manual/misc/rewriteguide.html.ko.euc-kr
/usr/share/manual/misc/security_tips.html
/usr/share/manual/misc/security_tips.html.en
/usr/share/manual/misc/security_tips.html.ko.euc-kr
/usr/share/manual/misc/security_tips.html.tr.utf8
/usr/share/manual/mod/beos.html
/usr/share/manual/mod/beos.html.de
/usr/share/manual/mod/beos.html.en
/usr/share/manual/mod/beos.html.es
/usr/share/manual/mod/beos.html.ko.euc-kr
/usr/share/manual/mod/core.html
/usr/share/manual/mod/core.html.de
/usr/share/manual/mod/core.html.en
/usr/share/manual/mod/core.html.fr
/usr/share/manual/mod/core.html.ja.utf8
/usr/share/manual/mod/core.html.tr.utf8
/usr/share/manual/mod/directive-dict.html
/usr/share/manual/mod/directive-dict.html.en
/usr/share/manual/mod/directive-dict.html.ja.utf8
/usr/share/manual/mod/directive-dict.html.ko.euc-kr
/usr/share/manual/mod/directive-dict.html.tr.utf8
/usr/share/manual/mod/directives.html
/usr/share/manual/mod/directives.html.de
/usr/share/manual/mod/directives.html.en
/usr/share/manual/mod/directives.html.es
/usr/share/manual/mod/directives.html.ja.utf8
/usr/share/manual/mod/directives.html.ko.euc-kr
/usr/share/manual/mod/directives.html.ru.koi8-r
/usr/share/manual/mod/directives.html.tr.utf8
/usr/share/manual/mod/directives.html.zh-cn
/usr/share/manual/mod/event.html
/usr/share/manual/mod/event.html.en
/usr/share/manual/mod/index.html
/usr/share/manual/mod/index.html.de
/usr/share/manual/mod/index.html.en
/usr/share/manual/mod/index.html.es
/usr/share/manual/mod/index.html.ja.utf8
/usr/share/manual/mod/index.html.ko.euc-kr
/usr/share/manual/mod/index.html.tr.utf8
/usr/share/manual/mod/index.html.zh-cn
/usr/share/manual/mod/mod_actions.html
/usr/share/manual/mod/mod_actions.html.de
/usr/share/manual/mod/mod_actions.html.en
/usr/share/manual/mod/mod_actions.html.ja.utf8
/usr/share/manual/mod/mod_actions.html.ko.euc-kr
/usr/share/manual/mod/mod_alias.html
/usr/share/manual/mod/mod_alias.html.en
/usr/share/manual/mod/mod_alias.html.ja.utf8
/usr/share/manual/mod/mod_alias.html.ko.euc-kr
/usr/share/manual/mod/mod_alias.html.tr.utf8
/usr/share/manual/mod/mod_asis.html
/usr/share/manual/mod/mod_asis.html.en
/usr/share/manual/mod/mod_asis.html.ja.utf8
/usr/share/manual/mod/mod_asis.html.ko.euc-kr
/usr/share/manual/mod/mod_auth_basic.html
/usr/share/manual/mod/mod_auth_basic.html.en
/usr/share/manual/mod/mod_auth_basic.html.fr
/usr/share/manual/mod/mod_auth_basic.html.ja.utf8
/usr/share/manual/mod/mod_auth_basic.html.ko.euc-kr
/usr/share/manual/mod/mod_auth_digest.html
/usr/share/manual/mod/mod_auth_digest.html.en
/usr/share/manual/mod/mod_auth_digest.html.fr
/usr/share/manual/mod/mod_auth_digest.html.ko.euc-kr
/usr/share/manual/mod/mod_authn_alias.html
/usr/share/manual/mod/mod_authn_alias.html.en
/usr/share/manual/mod/mod_authn_alias.html.fr
/usr/share/manual/mod/mod_authn_anon.html
/usr/share/manual/mod/mod_authn_anon.html.en
/usr/share/manual/mod/mod_authn_anon.html.ja.utf8
/usr/share/manual/mod/mod_authn_anon.html.ko.euc-kr
/usr/share/manual/mod/mod_authn_dbd.html
/usr/share/manual/mod/mod_authn_dbd.html.en
/usr/share/manual/mod/mod_authn_dbm.html
/usr/share/manual/mod/mod_authn_dbm.html.en
/usr/share/manual/mod/mod_authn_dbm.html.ja.utf8
/usr/share/manual/mod/mod_authn_dbm.html.ko.euc-kr
/usr/share/manual/mod/mod_authn_default.html
/usr/share/manual/mod/mod_authn_default.html.en
/usr/share/manual/mod/mod_authn_default.html.ja.utf8
/usr/share/manual/mod/mod_authn_default.html.ko.euc-kr
/usr/share/manual/mod/mod_authn_file.html
/usr/share/manual/mod/mod_authn_file.html.en
/usr/share/manual/mod/mod_authn_file.html.fr
/usr/share/manual/mod/mod_authn_file.html.ja.utf8
/usr/share/manual/mod/mod_authn_file.html.ko.euc-kr
/usr/share/manual/mod/mod_authnz_ldap.html
/usr/share/manual/mod/mod_authnz_ldap.html.en
/usr/share/manual/mod/mod_authnz_ldap.html.fr
/usr/share/manual/mod/mod_authz_dbm.html
/usr/share/manual/mod/mod_authz_dbm.html.en
/usr/share/manual/mod/mod_authz_dbm.html.ko.euc-kr
/usr/share/manual/mod/mod_authz_default.html
/usr/share/manual/mod/mod_authz_default.html.en
/usr/share/manual/mod/mod_authz_default.html.ja.utf8
/usr/share/manual/mod/mod_authz_default.html.ko.euc-kr
/usr/share/manual/mod/mod_authz_groupfile.html
/usr/share/manual/mod/mod_authz_groupfile.html.en
/usr/share/manual/mod/mod_authz_groupfile.html.ja.utf8
/usr/share/manual/mod/mod_authz_groupfile.html.ko.euc-kr
/usr/share/manual/mod/mod_authz_host.html
/usr/share/manual/mod/mod_authz_host.html.en
/usr/share/manual/mod/mod_authz_host.html.fr
/usr/share/manual/mod/mod_authz_host.html.ja.utf8
/usr/share/manual/mod/mod_authz_host.html.ko.euc-kr
/usr/share/manual/mod/mod_authz_owner.html
/usr/share/manual/mod/mod_authz_owner.html.en
/usr/share/manual/mod/mod_authz_owner.html.ja.utf8
/usr/share/manual/mod/mod_authz_owner.html.ko.euc-kr
/usr/share/manual/mod/mod_authz_user.html
/usr/share/manual/mod/mod_authz_user.html.en
/usr/share/manual/mod/mod_authz_user.html.ja.utf8
/usr/share/manual/mod/mod_authz_user.html.ko.euc-kr
/usr/share/manual/mod/mod_autoindex.html
/usr/share/manual/mod/mod_autoindex.html.en
/usr/share/manual/mod/mod_autoindex.html.fr
/usr/share/manual/mod/mod_autoindex.html.ja.utf8
/usr/share/manual/mod/mod_autoindex.html.ko.euc-kr
/usr/share/manual/mod/mod_autoindex.html.tr.utf8
/usr/share/manual/mod/mod_cache.html
/usr/share/manual/mod/mod_cache.html.en
/usr/share/manual/mod/mod_cache.html.ja.utf8
/usr/share/manual/mod/mod_cache.html.ko.euc-kr
/usr/share/manual/mod/mod_cern_meta.html
/usr/share/manual/mod/mod_cern_meta.html.en
/usr/share/manual/mod/mod_cern_meta.html.ko.euc-kr
/usr/share/manual/mod/mod_cgi.html
/usr/share/manual/mod/mod_cgi.html.en
/usr/share/manual/mod/mod_cgi.html.ja.utf8
/usr/share/manual/mod/mod_cgi.html.ko.euc-kr
/usr/share/manual/mod/mod_cgid.html
/usr/share/manual/mod/mod_cgid.html.en
/usr/share/manual/mod/mod_cgid.html.ja.utf8
/usr/share/manual/mod/mod_cgid.html.ko.euc-kr
/usr/share/manual/mod/mod_charset_lite.html
/usr/share/manual/mod/mod_charset_lite.html.en
/usr/share/manual/mod/mod_charset_lite.html.ko.euc-kr
/usr/share/manual/mod/mod_dav.html
/usr/share/manual/mod/mod_dav.html.en
/usr/share/manual/mod/mod_dav.html.ja.utf8
/usr/share/manual/mod/mod_dav.html.ko.euc-kr
/usr/share/manual/mod/mod_dav_fs.html
/usr/share/manual/mod/mod_dav_fs.html.en
/usr/share/manual/mod/mod_dav_fs.html.ja.utf8
/usr/share/manual/mod/mod_dav_fs.html.ko.euc-kr
/usr/share/manual/mod/mod_dav_lock.html
/usr/share/manual/mod/mod_dav_lock.html.en
/usr/share/manual/mod/mod_dav_lock.html.ja.utf8
/usr/share/manual/mod/mod_dbd.html
/usr/share/manual/mod/mod_dbd.html.en
/usr/share/manual/mod/mod_deflate.html
/usr/share/manual/mod/mod_deflate.html.en
/usr/share/manual/mod/mod_deflate.html.ja.utf8
/usr/share/manual/mod/mod_deflate.html.ko.euc-kr
/usr/share/manual/mod/mod_dir.html
/usr/share/manual/mod/mod_dir.html.en
/usr/share/manual/mod/mod_dir.html.ja.utf8
/usr/share/manual/mod/mod_dir.html.ko.euc-kr
/usr/share/manual/mod/mod_dir.html.tr.utf8
/usr/share/manual/mod/mod_disk_cache.html
/usr/share/manual/mod/mod_disk_cache.html.en
/usr/share/manual/mod/mod_disk_cache.html.ja.utf8
/usr/share/manual/mod/mod_disk_cache.html.ko.euc-kr
/usr/share/manual/mod/mod_dumpio.html
/usr/share/manual/mod/mod_dumpio.html.en
/usr/share/manual/mod/mod_dumpio.html.ja.utf8
/usr/share/manual/mod/mod_echo.html
/usr/share/manual/mod/mod_echo.html.en
/usr/share/manual/mod/mod_echo.html.ja.utf8
/usr/share/manual/mod/mod_echo.html.ko.euc-kr
/usr/share/manual/mod/mod_env.html
/usr/share/manual/mod/mod_env.html.en
/usr/share/manual/mod/mod_env.html.ja.utf8
/usr/share/manual/mod/mod_env.html.ko.euc-kr
/usr/share/manual/mod/mod_env.html.tr.utf8
/usr/share/manual/mod/mod_example.html
/usr/share/manual/mod/mod_example.html.en
/usr/share/manual/mod/mod_example.html.ko.euc-kr
/usr/share/manual/mod/mod_expires.html
/usr/share/manual/mod/mod_expires.html.en
/usr/share/manual/mod/mod_expires.html.ja.utf8
/usr/share/manual/mod/mod_expires.html.ko.euc-kr
/usr/share/manual/mod/mod_ext_filter.html
/usr/share/manual/mod/mod_ext_filter.html.en
/usr/share/manual/mod/mod_ext_filter.html.ja.utf8
/usr/share/manual/mod/mod_ext_filter.html.ko.euc-kr
/usr/share/manual/mod/mod_file_cache.html
/usr/share/manual/mod/mod_file_cache.html.en
/usr/share/manual/mod/mod_file_cache.html.ko.euc-kr
/usr/share/manual/mod/mod_filter.html
/usr/share/manual/mod/mod_filter.html.en
/usr/share/manual/mod/mod_headers.html
/usr/share/manual/mod/mod_headers.html.en
/usr/share/manual/mod/mod_headers.html.ja.utf8
/usr/share/manual/mod/mod_headers.html.ko.euc-kr
/usr/share/manual/mod/mod_ident.html
/usr/share/manual/mod/mod_ident.html.en
/usr/share/manual/mod/mod_ident.html.ja.utf8
/usr/share/manual/mod/mod_ident.html.ko.euc-kr
/usr/share/manual/mod/mod_imagemap.html
/usr/share/manual/mod/mod_imagemap.html.en
/usr/share/manual/mod/mod_imagemap.html.ko.euc-kr
/usr/share/manual/mod/mod_include.html
/usr/share/manual/mod/mod_include.html.en
/usr/share/manual/mod/mod_include.html.ja.utf8
/usr/share/manual/mod/mod_info.html
/usr/share/manual/mod/mod_info.html.en
/usr/share/manual/mod/mod_info.html.ja.utf8
/usr/share/manual/mod/mod_info.html.ko.euc-kr
/usr/share/manual/mod/mod_isapi.html
/usr/share/manual/mod/mod_isapi.html.en
/usr/share/manual/mod/mod_isapi.html.ko.euc-kr
/usr/share/manual/mod/mod_ldap.html
/usr/share/manual/mod/mod_ldap.html.en
/usr/share/manual/mod/mod_log_config.html
/usr/share/manual/mod/mod_log_config.html.en
/usr/share/manual/mod/mod_log_config.html.ja.utf8
/usr/share/manual/mod/mod_log_config.html.ko.euc-kr
/usr/share/manual/mod/mod_log_config.html.tr.utf8
/usr/share/manual/mod/mod_log_forensic.html
/usr/share/manual/mod/mod_log_forensic.html.en
/usr/share/manual/mod/mod_log_forensic.html.ja.utf8
/usr/share/manual/mod/mod_log_forensic.html.tr.utf8
/usr/share/manual/mod/mod_logio.html
/usr/share/manual/mod/mod_logio.html.en
/usr/share/manual/mod/mod_logio.html.ja.utf8
/usr/share/manual/mod/mod_logio.html.ko.euc-kr
/usr/share/manual/mod/mod_logio.html.tr.utf8
/usr/share/manual/mod/mod_mem_cache.html
/usr/share/manual/mod/mod_mem_cache.html.en
/usr/share/manual/mod/mod_mem_cache.html.ja.utf8
/usr/share/manual/mod/mod_mem_cache.html.ko.euc-kr
/usr/share/manual/mod/mod_mime.html
/usr/share/manual/mod/mod_mime.html.en
/usr/share/manual/mod/mod_mime.html.ja.utf8
/usr/share/manual/mod/mod_mime_magic.html
/usr/share/manual/mod/mod_mime_magic.html.en
/usr/share/manual/mod/mod_negotiation.html
/usr/share/manual/mod/mod_negotiation.html.en
/usr/share/manual/mod/mod_negotiation.html.ja.utf8
/usr/share/manual/mod/mod_nw_ssl.html
/usr/share/manual/mod/mod_nw_ssl.html.en
/usr/share/manual/mod/mod_proxy.html
/usr/share/manual/mod/mod_proxy.html.en
/usr/share/manual/mod/mod_proxy.html.fr
/usr/share/manual/mod/mod_proxy.html.ja.utf8
/usr/share/manual/mod/mod_proxy_ajp.html
/usr/share/manual/mod/mod_proxy_ajp.html.en
/usr/share/manual/mod/mod_proxy_ajp.html.ja.utf8
/usr/share/manual/mod/mod_proxy_balancer.html
/usr/share/manual/mod/mod_proxy_balancer.html.en
/usr/share/manual/mod/mod_proxy_balancer.html.ja.utf8
/usr/share/manual/mod/mod_proxy_connect.html
/usr/share/manual/mod/mod_proxy_connect.html.en
/usr/share/manual/mod/mod_proxy_connect.html.ja.utf8
/usr/share/manual/mod/mod_proxy_ftp.html
/usr/share/manual/mod/mod_proxy_ftp.html.en
/usr/share/manual/mod/mod_proxy_ftp.html.ja.utf8
/usr/share/manual/mod/mod_proxy_http.html
/usr/share/manual/mod/mod_proxy_http.html.en
/usr/share/manual/mod/mod_proxy_http.html.fr
/usr/share/manual/mod/mod_proxy_http.html.ja.utf8
/usr/share/manual/mod/mod_proxy_scgi.html
/usr/share/manual/mod/mod_proxy_scgi.html.en
/usr/share/manual/mod/mod_proxy_scgi.html.ja.utf8
/usr/share/manual/mod/mod_reqtimeout.html
/usr/share/manual/mod/mod_reqtimeout.html.en
/usr/share/manual/mod/mod_rewrite.html
/usr/share/manual/mod/mod_rewrite.html.en
/usr/share/manual/mod/mod_rewrite.html.fr
/usr/share/manual/mod/mod_setenvif.html
/usr/share/manual/mod/mod_setenvif.html.en
/usr/share/manual/mod/mod_setenvif.html.ja.utf8
/usr/share/manual/mod/mod_setenvif.html.ko.euc-kr
/usr/share/manual/mod/mod_setenvif.html.tr.utf8
/usr/share/manual/mod/mod_so.html
/usr/share/manual/mod/mod_so.html.en
/usr/share/manual/mod/mod_so.html.ja.utf8
/usr/share/manual/mod/mod_so.html.ko.euc-kr
/usr/share/manual/mod/mod_so.html.tr.utf8
/usr/share/manual/mod/mod_speling.html
/usr/share/manual/mod/mod_speling.html.en
/usr/share/manual/mod/mod_speling.html.ja.utf8
/usr/share/manual/mod/mod_speling.html.ko.euc-kr
/usr/share/manual/mod/mod_ssl.html
/usr/share/manual/mod/mod_ssl.html.en
/usr/share/manual/mod/mod_status.html
/usr/share/manual/mod/mod_status.html.en
/usr/share/manual/mod/mod_status.html.ja.utf8
/usr/share/manual/mod/mod_status.html.ko.euc-kr
/usr/share/manual/mod/mod_status.html.tr.utf8
/usr/share/manual/mod/mod_substitute.html
/usr/share/manual/mod/mod_substitute.html.en
/usr/share/manual/mod/mod_suexec.html
/usr/share/manual/mod/mod_suexec.html.en
/usr/share/manual/mod/mod_suexec.html.fr
/usr/share/manual/mod/mod_suexec.html.ja.utf8
/usr/share/manual/mod/mod_suexec.html.ko.euc-kr
/usr/share/manual/mod/mod_suexec.html.tr.utf8
/usr/share/manual/mod/mod_unique_id.html
/usr/share/manual/mod/mod_unique_id.html.en
/usr/share/manual/mod/mod_unique_id.html.ja.utf8
/usr/share/manual/mod/mod_unique_id.html.ko.euc-kr
/usr/share/manual/mod/mod_userdir.html
/usr/share/manual/mod/mod_userdir.html.en
/usr/share/manual/mod/mod_userdir.html.ja.utf8
/usr/share/manual/mod/mod_userdir.html.ko.euc-kr
/usr/share/manual/mod/mod_userdir.html.tr.utf8
/usr/share/manual/mod/mod_usertrack.html
/usr/share/manual/mod/mod_usertrack.html.en
/usr/share/manual/mod/mod_version.html
/usr/share/manual/mod/mod_version.html.en
/usr/share/manual/mod/mod_version.html.ja.utf8
/usr/share/manual/mod/mod_version.html.ko.euc-kr
/usr/share/manual/mod/mod_vhost_alias.html
/usr/share/manual/mod/mod_vhost_alias.html.en
/usr/share/manual/mod/mod_vhost_alias.html.tr.utf8
/usr/share/manual/mod/module-dict.html
/usr/share/manual/mod/module-dict.html.en
/usr/share/manual/mod/module-dict.html.ja.utf8
/usr/share/manual/mod/module-dict.html.ko.euc-kr
/usr/share/manual/mod/module-dict.html.tr.utf8
/usr/share/manual/mod/mpm_common.html
/usr/share/manual/mod/mpm_common.html.de
/usr/share/manual/mod/mpm_common.html.en
/usr/share/manual/mod/mpm_common.html.ja.utf8
/usr/share/manual/mod/mpm_common.html.tr.utf8
/usr/share/manual/mod/mpm_netware.html
/usr/share/manual/mod/mpm_netware.html.en
/usr/share/manual/mod/mpm_winnt.html
/usr/share/manual/mod/mpm_winnt.html.de
/usr/share/manual/mod/mpm_winnt.html.en
/usr/share/manual/mod/mpm_winnt.html.ja.utf8
/usr/share/manual/mod/mpmt_os2.html
/usr/share/manual/mod/mpmt_os2.html.en
/usr/share/manual/mod/prefork.html
/usr/share/manual/mod/prefork.html.de
/usr/share/manual/mod/prefork.html.en
/usr/share/manual/mod/prefork.html.ja.utf8
/usr/share/manual/mod/prefork.html.tr.utf8
/usr/share/manual/mod/quickreference.html
/usr/share/manual/mod/quickreference.html.de
/usr/share/manual/mod/quickreference.html.en
/usr/share/manual/mod/quickreference.html.es
/usr/share/manual/mod/quickreference.html.ja.utf8
/usr/share/manual/mod/quickreference.html.ko.euc-kr
/usr/share/manual/mod/quickreference.html.ru.koi8-r
/usr/share/manual/mod/quickreference.html.tr.utf8
/usr/share/manual/mod/quickreference.html.zh-cn
/usr/share/manual/mod/worker.html
/usr/share/manual/mod/worker.html.de
/usr/share/manual/mod/worker.html.en
/usr/share/manual/mod/worker.html.ja.utf8
/usr/share/manual/mod/worker.html.tr.utf8
/usr/share/manual/mpm.html
/usr/share/manual/mpm.html.de
/usr/share/manual/mpm.html.en
/usr/share/manual/mpm.html.es
/usr/share/manual/mpm.html.fr
/usr/share/manual/mpm.html.ja.utf8
/usr/share/manual/mpm.html.ko.euc-kr
/usr/share/manual/mpm.html.tr.utf8
/usr/share/manual/mpm.html.zh-cn
/usr/share/manual/new_features_2_0.html
/usr/share/manual/new_features_2_0.html.de
/usr/share/manual/new_features_2_0.html.en
/usr/share/manual/new_features_2_0.html.fr
/usr/share/manual/new_features_2_0.html.ja.utf8
/usr/share/manual/new_features_2_0.html.ko.euc-kr
/usr/share/manual/new_features_2_0.html.pt-br
/usr/share/manual/new_features_2_0.html.ru.koi8-r
/usr/share/manual/new_features_2_0.html.tr.utf8
/usr/share/manual/new_features_2_2.html
/usr/share/manual/new_features_2_2.html.en
/usr/share/manual/new_features_2_2.html.fr
/usr/share/manual/new_features_2_2.html.ja.utf8
/usr/share/manual/new_features_2_2.html.ko.euc-kr
/usr/share/manual/new_features_2_2.html.pt-br
/usr/share/manual/new_features_2_2.html.tr.utf8
/usr/share/manual/platform/ebcdic.html
/usr/share/manual/platform/ebcdic.html.en
/usr/share/manual/platform/ebcdic.html.ko.euc-kr
/usr/share/manual/platform/index.html
/usr/share/manual/platform/index.html.en
/usr/share/manual/platform/index.html.ko.euc-kr
/usr/share/manual/platform/index.html.zh-cn
/usr/share/manual/platform/netware.html
/usr/share/manual/platform/netware.html.en
/usr/share/manual/platform/netware.html.ko.euc-kr
/usr/share/manual/platform/perf-hp.html
/usr/share/manual/platform/perf-hp.html.en
/usr/share/manual/platform/perf-hp.html.ko.euc-kr
/usr/share/manual/platform/win_compiling.html
/usr/share/manual/platform/win_compiling.html.en
/usr/share/manual/platform/win_compiling.html.ko.euc-kr
/usr/share/manual/platform/windows.html
/usr/share/manual/platform/windows.html.en
/usr/share/manual/platform/windows.html.ko.euc-kr
/usr/share/manual/programs/ab.html
/usr/share/manual/programs/ab.html.en
/usr/share/manual/programs/ab.html.ko.euc-kr
/usr/share/manual/programs/ab.html.tr.utf8
/usr/share/manual/programs/apachectl.html
/usr/share/manual/programs/apachectl.html.en
/usr/share/manual/programs/apachectl.html.ko.euc-kr
/usr/share/manual/programs/apachectl.html.tr.utf8
/usr/share/manual/programs/apxs.html
/usr/share/manual/programs/apxs.html.en
/usr/share/manual/programs/apxs.html.ko.euc-kr
/usr/share/manual/programs/apxs.html.tr.utf8
/usr/share/manual/programs/configure.html
/usr/share/manual/programs/configure.html.en
/usr/share/manual/programs/configure.html.ko.euc-kr
/usr/share/manual/programs/configure.html.tr.utf8
/usr/share/manual/programs/dbmmanage.html
/usr/share/manual/programs/dbmmanage.html.en
/usr/share/manual/programs/dbmmanage.html.ko.euc-kr
/usr/share/manual/programs/dbmmanage.html.tr.utf8
/usr/share/manual/programs/htcacheclean.html
/usr/share/manual/programs/htcacheclean.html.en
/usr/share/manual/programs/htcacheclean.html.ko.euc-kr
/usr/share/manual/programs/htcacheclean.html.tr.utf8
/usr/share/manual/programs/htdbm.html
/usr/share/manual/programs/htdbm.html.en
/usr/share/manual/programs/htdbm.html.tr.utf8
/usr/share/manual/programs/htdigest.html
/usr/share/manual/programs/htdigest.html.en
/usr/share/manual/programs/htdigest.html.ko.euc-kr
/usr/share/manual/programs/htdigest.html.tr.utf8
/usr/share/manual/programs/htpasswd.html
/usr/share/manual/programs/htpasswd.html.en
/usr/share/manual/programs/htpasswd.html.ko.euc-kr
/usr/share/manual/programs/htpasswd.html.tr.utf8
/usr/share/manual/programs/httpd.html
/usr/share/manual/programs/httpd.html.en
/usr/share/manual/programs/httpd.html.ko.euc-kr
/usr/share/manual/programs/httpd.html.tr.utf8
/usr/share/manual/programs/httxt2dbm.html
/usr/share/manual/programs/httxt2dbm.html.en
/usr/share/manual/programs/httxt2dbm.html.tr.utf8
/usr/share/manual/programs/index.html
/usr/share/manual/programs/index.html.en
/usr/share/manual/programs/index.html.es
/usr/share/manual/programs/index.html.ja.utf8
/usr/share/manual/programs/index.html.ko.euc-kr
/usr/share/manual/programs/index.html.ru.koi8-r
/usr/share/manual/programs/index.html.tr.utf8
/usr/share/manual/programs/index.html.zh-cn
/usr/share/manual/programs/logresolve.html
/usr/share/manual/programs/logresolve.html.en
/usr/share/manual/programs/logresolve.html.ko.euc-kr
/usr/share/manual/programs/logresolve.html.tr.utf8
/usr/share/manual/programs/other.html
/usr/share/manual/programs/other.html.en
/usr/share/manual/programs/other.html.ko.euc-kr
/usr/share/manual/programs/other.html.tr.utf8
/usr/share/manual/programs/rotatelogs.html
/usr/share/manual/programs/rotatelogs.html.en
/usr/share/manual/programs/rotatelogs.html.ko.euc-kr
/usr/share/manual/programs/rotatelogs.html.tr.utf8
/usr/share/manual/programs/suexec.html
/usr/share/manual/programs/suexec.html.en
/usr/share/manual/programs/suexec.html.ko.euc-kr
/usr/share/manual/programs/suexec.html.tr.utf8
/usr/share/manual/rewrite/access.html
/usr/share/manual/rewrite/access.html.en
/usr/share/manual/rewrite/advanced.html
/usr/share/manual/rewrite/advanced.html.en
/usr/share/manual/rewrite/avoid.html
/usr/share/manual/rewrite/avoid.html.en
/usr/share/manual/rewrite/flags.html
/usr/share/manual/rewrite/flags.html.en
/usr/share/manual/rewrite/flags.html.fr
/usr/share/manual/rewrite/htaccess.html
/usr/share/manual/rewrite/htaccess.html.en
/usr/share/manual/rewrite/index.html
/usr/share/manual/rewrite/index.html.en
/usr/share/manual/rewrite/index.html.fr
/usr/share/manual/rewrite/index.html.tr.utf8
/usr/share/manual/rewrite/index.html.zh-cn
/usr/share/manual/rewrite/intro.html
/usr/share/manual/rewrite/intro.html.en
/usr/share/manual/rewrite/intro.html.fr
/usr/share/manual/rewrite/proxy.html
/usr/share/manual/rewrite/proxy.html.en
/usr/share/manual/rewrite/remapping.html
/usr/share/manual/rewrite/remapping.html.en
/usr/share/manual/rewrite/rewritemap.html
/usr/share/manual/rewrite/rewritemap.html.en
/usr/share/manual/rewrite/tech.html
/usr/share/manual/rewrite/tech.html.en
/usr/share/manual/rewrite/tech.html.fr
/usr/share/manual/rewrite/vhosts.html
/usr/share/manual/rewrite/vhosts.html.en
/usr/share/manual/sections.html
/usr/share/manual/sections.html.en
/usr/share/manual/sections.html.fr
/usr/share/manual/sections.html.ja.utf8
/usr/share/manual/sections.html.ko.euc-kr
/usr/share/manual/sections.html.tr.utf8
/usr/share/manual/server-wide.html
/usr/share/manual/server-wide.html.en
/usr/share/manual/server-wide.html.ja.utf8
/usr/share/manual/server-wide.html.ko.euc-kr
/usr/share/manual/server-wide.html.tr.utf8
/usr/share/manual/sitemap.html
/usr/share/manual/sitemap.html.de
/usr/share/manual/sitemap.html.en
/usr/share/manual/sitemap.html.es
/usr/share/manual/sitemap.html.ja.utf8
/usr/share/manual/sitemap.html.ko.euc-kr
/usr/share/manual/sitemap.html.tr.utf8
/usr/share/manual/sitemap.html.zh-cn
/usr/share/manual/ssl/index.html
/usr/share/manual/ssl/index.html.en
/usr/share/manual/ssl/index.html.ja.utf8
/usr/share/manual/ssl/index.html.tr.utf8
/usr/share/manual/ssl/index.html.zh-cn
/usr/share/manual/ssl/ssl_compat.html
/usr/share/manual/ssl/ssl_compat.html.en
/usr/share/manual/ssl/ssl_faq.html
/usr/share/manual/ssl/ssl_faq.html.en
/usr/share/manual/ssl/ssl_howto.html
/usr/share/manual/ssl/ssl_howto.html.en
/usr/share/manual/ssl/ssl_intro.html
/usr/share/manual/ssl/ssl_intro.html.en
/usr/share/manual/ssl/ssl_intro.html.ja.utf8
/usr/share/manual/stopping.html
/usr/share/manual/stopping.html.de
/usr/share/manual/stopping.html.en
/usr/share/manual/stopping.html.es
/usr/share/manual/stopping.html.fr
/usr/share/manual/stopping.html.ja.utf8
/usr/share/manual/stopping.html.ko.euc-kr
/usr/share/manual/stopping.html.tr.utf8
/usr/share/manual/style/build.properties
/usr/share/manual/style/common.dtd
/usr/share/manual/style/css/manual-chm.css
/usr/share/manual/style/css/manual-loose-100pc.css
/usr/share/manual/style/css/manual-print.css
/usr/share/manual/style/css/manual-zip-100pc.css
/usr/share/manual/style/css/manual-zip.css
/usr/share/manual/style/css/manual.css
/usr/share/manual/style/css/prettify.css
/usr/share/manual/style/faq.dtd
/usr/share/manual/style/lang.dtd
/usr/share/manual/style/latex/atbeginend.sty
/usr/share/manual/style/manualpage.dtd
/usr/share/manual/style/modulesynopsis.dtd
/usr/share/manual/style/scripts/prettify.js
/usr/share/manual/style/sitemap.dtd
/usr/share/manual/style/version.ent
/usr/share/manual/suexec.html
/usr/share/manual/suexec.html.en
/usr/share/manual/suexec.html.fr
/usr/share/manual/suexec.html.ja.utf8
/usr/share/manual/suexec.html.ko.euc-kr
/usr/share/manual/suexec.html.tr.utf8
/usr/share/manual/upgrading.html
/usr/share/manual/upgrading.html.de
/usr/share/manual/upgrading.html.en
/usr/share/manual/upgrading.html.fr
/usr/share/manual/upgrading.html.ja.utf8
/usr/share/manual/urlmapping.html
/usr/share/manual/urlmapping.html.en
/usr/share/manual/urlmapping.html.ja.utf8
/usr/share/manual/urlmapping.html.ko.euc-kr
/usr/share/manual/urlmapping.html.tr.utf8
/usr/share/manual/vhosts/details.html
/usr/share/manual/vhosts/details.html.en
/usr/share/manual/vhosts/details.html.fr
/usr/share/manual/vhosts/details.html.ko.euc-kr
/usr/share/manual/vhosts/details.html.tr.utf8
/usr/share/manual/vhosts/examples.html
/usr/share/manual/vhosts/examples.html.en
/usr/share/manual/vhosts/examples.html.fr
/usr/share/manual/vhosts/examples.html.ja.utf8
/usr/share/manual/vhosts/examples.html.ko.euc-kr
/usr/share/manual/vhosts/examples.html.tr.utf8
/usr/share/manual/vhosts/fd-limits.html
/usr/share/manual/vhosts/fd-limits.html.en
/usr/share/manual/vhosts/fd-limits.html.fr
/usr/share/manual/vhosts/fd-limits.html.ja.utf8
/usr/share/manual/vhosts/fd-limits.html.ko.euc-kr
/usr/share/manual/vhosts/fd-limits.html.tr.utf8
/usr/share/manual/vhosts/index.html
/usr/share/manual/vhosts/index.html.de
/usr/share/manual/vhosts/index.html.en
/usr/share/manual/vhosts/index.html.fr
/usr/share/manual/vhosts/index.html.ja.utf8
/usr/share/manual/vhosts/index.html.ko.euc-kr
/usr/share/manual/vhosts/index.html.ru.koi8-r
/usr/share/manual/vhosts/index.html.tr.utf8
/usr/share/manual/vhosts/index.html.zh-cn
/usr/share/manual/vhosts/ip-based.html
/usr/share/manual/vhosts/ip-based.html.en
/usr/share/manual/vhosts/ip-based.html.fr
/usr/share/manual/vhosts/ip-based.html.ja.utf8
/usr/share/manual/vhosts/ip-based.html.ko.euc-kr
/usr/share/manual/vhosts/ip-based.html.tr.utf8
/usr/share/manual/vhosts/mass.html
/usr/share/manual/vhosts/mass.html.en
/usr/share/manual/vhosts/mass.html.ko.euc-kr
/usr/share/manual/vhosts/mass.html.tr.utf8
/usr/share/manual/vhosts/name-based.html
/usr/share/manual/vhosts/name-based.html.de
/usr/share/manual/vhosts/name-based.html.en
/usr/share/manual/vhosts/name-based.html.fr
/usr/share/manual/vhosts/name-based.html.ja.utf8
/usr/share/manual/vhosts/name-based.html.ko.euc-kr
/usr/share/manual/vhosts/name-based.html.tr.utf8

%changelog
