Name:		httpd

Version:	2.2.24
Release:	1%{?dist}
Summary:	httpd

Group:		Hisoku
License:	No
URL:		http://hisoku.ronny.tw/
Source0:	httpd-2.2.24.tar.gz
BuildRoot:	%(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

%description


%prep
%setup -q


%build
%configure --enable-rewrite --enable-deflate --with-included-apr --with-mpm=worker --sysconfdir=/etc/httpd --enable-vhost-alias
make %{?_smp_mflags}
cd modules/fastcgi
make top_dir=../../
cd ../../
cd modules/mod_rpaf
make
cd ../../

%install
rm -rf %{buildroot}
make install DESTDIR=%{buildroot}
mkdir %{buildroot}/modules/
cp modules/fastcgi/.libs/mod_fastcgi.so %{buildroot}/modules/
cp modules/mod_rpaf/.libs/mod_rpaf.so %{buildroot}/modules/
rm -rf %{buildroot}/usr/share/manual

%clean
rm -rf %{buildroot}


%files
%defattr(-,root,root,-)
%doc
/etc/httpd/extra/httpd-autoindex.conf
/etc/httpd/extra/httpd-dav.conf
/etc/httpd/extra/httpd-default.conf
/etc/httpd/extra/httpd-info.conf
/etc/httpd/extra/httpd-languages.conf
/etc/httpd/extra/httpd-manual.conf
/etc/httpd/extra/httpd-mpm.conf
/etc/httpd/extra/httpd-multilang-errordoc.conf
/etc/httpd/extra/httpd-ssl.conf
/etc/httpd/extra/httpd-userdir.conf
/etc/httpd/extra/httpd-vhosts.conf
/etc/httpd/httpd.conf
/etc/httpd/magic
/etc/httpd/mime.types
/etc/httpd/original/extra/httpd-autoindex.conf
/etc/httpd/original/extra/httpd-dav.conf
/etc/httpd/original/extra/httpd-default.conf
/etc/httpd/original/extra/httpd-info.conf
/etc/httpd/original/extra/httpd-languages.conf
/etc/httpd/original/extra/httpd-manual.conf
/etc/httpd/original/extra/httpd-mpm.conf
/etc/httpd/original/extra/httpd-multilang-errordoc.conf
/etc/httpd/original/extra/httpd-ssl.conf
/etc/httpd/original/extra/httpd-userdir.conf
/etc/httpd/original/extra/httpd-vhosts.conf
/etc/httpd/original/httpd.conf
/modules/mod_fastcgi.so
/modules/mod_rpaf.so
/usr/bin/apr-1-config
/usr/bin/apu-1-config
/usr/include/ap_compat.h
/usr/include/ap_config.h
/usr/include/ap_config_auto.h
/usr/include/ap_config_layout.h
/usr/include/ap_listen.h
/usr/include/ap_mmn.h
/usr/include/ap_mpm.h
/usr/include/ap_provider.h
/usr/include/ap_regex.h
/usr/include/ap_regkey.h
/usr/include/ap_release.h
/usr/include/apr.h
/usr/include/apr_allocator.h
/usr/include/apr_anylock.h
/usr/include/apr_atomic.h
/usr/include/apr_base64.h
/usr/include/apr_buckets.h
/usr/include/apr_crypto.h
/usr/include/apr_date.h
/usr/include/apr_dbd.h
/usr/include/apr_dbm.h
/usr/include/apr_dso.h
/usr/include/apr_env.h
/usr/include/apr_errno.h
/usr/include/apr_file_info.h
/usr/include/apr_file_io.h
/usr/include/apr_fnmatch.h
/usr/include/apr_general.h
/usr/include/apr_getopt.h
/usr/include/apr_global_mutex.h
/usr/include/apr_hash.h
/usr/include/apr_hooks.h
/usr/include/apr_inherit.h
/usr/include/apr_ldap.h
/usr/include/apr_ldap_init.h
/usr/include/apr_ldap_option.h
/usr/include/apr_ldap_rebind.h
/usr/include/apr_ldap_url.h
/usr/include/apr_lib.h
/usr/include/apr_md4.h
/usr/include/apr_md5.h
/usr/include/apr_memcache.h
/usr/include/apr_mmap.h
/usr/include/apr_network_io.h
/usr/include/apr_optional.h
/usr/include/apr_optional_hooks.h
/usr/include/apr_poll.h
/usr/include/apr_pools.h
/usr/include/apr_portable.h
/usr/include/apr_proc_mutex.h
/usr/include/apr_queue.h
/usr/include/apr_random.h
/usr/include/apr_reslist.h
/usr/include/apr_ring.h
/usr/include/apr_rmm.h
/usr/include/apr_sdbm.h
/usr/include/apr_sha1.h
/usr/include/apr_shm.h
/usr/include/apr_signal.h
/usr/include/apr_strings.h
/usr/include/apr_strmatch.h
/usr/include/apr_support.h
/usr/include/apr_tables.h
/usr/include/apr_thread_cond.h
/usr/include/apr_thread_mutex.h
/usr/include/apr_thread_pool.h
/usr/include/apr_thread_proc.h
/usr/include/apr_thread_rwlock.h
/usr/include/apr_time.h
/usr/include/apr_uri.h
/usr/include/apr_user.h
/usr/include/apr_uuid.h
/usr/include/apr_version.h
/usr/include/apr_want.h
/usr/include/apr_xlate.h
/usr/include/apr_xml.h
/usr/include/apu.h
/usr/include/apu_errno.h
/usr/include/apu_version.h
/usr/include/apu_want.h
/usr/include/fdqueue.h
/usr/include/http_config.h
/usr/include/http_connection.h
/usr/include/http_core.h
/usr/include/http_log.h
/usr/include/http_main.h
/usr/include/http_protocol.h
/usr/include/http_request.h
/usr/include/http_vhost.h
/usr/include/httpd.h
/usr/include/mod_auth.h
/usr/include/mod_cgi.h
/usr/include/mod_core.h
/usr/include/mod_dav.h
/usr/include/mod_dbd.h
/usr/include/mod_include.h
/usr/include/mod_log_config.h
/usr/include/mod_proxy.h
/usr/include/mod_rewrite.h
/usr/include/mod_ssl.h
/usr/include/mod_status.h
/usr/include/mpm.h
/usr/include/mpm_common.h
/usr/include/mpm_default.h
/usr/include/os.h
/usr/include/pod.h
/usr/include/scoreboard.h
/usr/include/unixd.h
/usr/include/util_cfgtree.h
/usr/include/util_charset.h
/usr/include/util_ebcdic.h
/usr/include/util_filter.h
/usr/include/util_ldap.h
/usr/include/util_md5.h
/usr/include/util_script.h
/usr/include/util_time.h
/usr/include/util_xml.h
/usr/lib64/apr-util-1/apr_dbd_pgsql-1.so
/usr/lib64/apr-util-1/apr_dbd_pgsql.a
/usr/lib64/apr-util-1/apr_dbd_pgsql.la
/usr/lib64/apr-util-1/apr_dbd_pgsql.so
/usr/lib64/apr-util-1/apr_dbd_sqlite3-1.so
/usr/lib64/apr-util-1/apr_dbd_sqlite3.a
/usr/lib64/apr-util-1/apr_dbd_sqlite3.la
/usr/lib64/apr-util-1/apr_dbd_sqlite3.so
/usr/lib64/apr.exp
/usr/lib64/aprutil.exp
/usr/lib64/libapr-1.a
/usr/lib64/libapr-1.la
/usr/lib64/libapr-1.so
/usr/lib64/libapr-1.so.0
/usr/lib64/libapr-1.so.0.4.6
/usr/lib64/libaprutil-1.a
/usr/lib64/libaprutil-1.la
/usr/lib64/libaprutil-1.so
/usr/lib64/libaprutil-1.so.0
/usr/lib64/libaprutil-1.so.0.4.1
/usr/lib64/pkgconfig/apr-1.pc
/usr/lib64/pkgconfig/apr-util-1.pc
/usr/libexec/httpd.exp
/usr/sbin/ab
/usr/sbin/apachectl
/usr/sbin/apxs
/usr/sbin/checkgid
/usr/sbin/dbmmanage
/usr/sbin/envvars
/usr/sbin/envvars-std
/usr/sbin/htcacheclean
/usr/sbin/htdbm
/usr/sbin/htdigest
/usr/sbin/htpasswd
/usr/sbin/httpd
/usr/sbin/httxt2dbm
/usr/sbin/logresolve
/usr/sbin/rotatelogs
/usr/share/build/apr_rules.mk
/usr/share/build/config.nice
/usr/share/build/config_vars.mk
/usr/share/build/instdso.sh
/usr/share/build/library.mk
/usr/share/build/libtool
/usr/share/build/ltlib.mk
/usr/share/build/make_exports.awk
/usr/share/build/make_var_export.awk
/usr/share/build/mkdir.sh
/usr/share/build/program.mk
/usr/share/build/rules.mk
/usr/share/build/special.mk
/usr/share/cgi-bin/printenv
/usr/share/cgi-bin/test-cgi
/usr/share/error/HTTP_BAD_GATEWAY.html.var
/usr/share/error/HTTP_BAD_REQUEST.html.var
/usr/share/error/HTTP_FORBIDDEN.html.var
/usr/share/error/HTTP_GONE.html.var
/usr/share/error/HTTP_INTERNAL_SERVER_ERROR.html.var
/usr/share/error/HTTP_LENGTH_REQUIRED.html.var
/usr/share/error/HTTP_METHOD_NOT_ALLOWED.html.var
/usr/share/error/HTTP_NOT_FOUND.html.var
/usr/share/error/HTTP_NOT_IMPLEMENTED.html.var
/usr/share/error/HTTP_PRECONDITION_FAILED.html.var
/usr/share/error/HTTP_REQUEST_ENTITY_TOO_LARGE.html.var
/usr/share/error/HTTP_REQUEST_TIME_OUT.html.var
/usr/share/error/HTTP_REQUEST_URI_TOO_LARGE.html.var
/usr/share/error/HTTP_SERVICE_UNAVAILABLE.html.var
/usr/share/error/HTTP_UNAUTHORIZED.html.var
/usr/share/error/HTTP_UNSUPPORTED_MEDIA_TYPE.html.var
/usr/share/error/HTTP_VARIANT_ALSO_VARIES.html.var
/usr/share/error/README
/usr/share/error/contact.html.var
/usr/share/error/include/bottom.html
/usr/share/error/include/spacer.html
/usr/share/error/include/top.html
/usr/share/htdocs/index.html
/usr/share/icons/README
/usr/share/icons/README.html
/usr/share/icons/a.gif
/usr/share/icons/a.png
/usr/share/icons/alert.black.gif
/usr/share/icons/alert.black.png
/usr/share/icons/alert.red.gif
/usr/share/icons/alert.red.png
/usr/share/icons/apache_pb.gif
/usr/share/icons/apache_pb.png
/usr/share/icons/apache_pb2.gif
/usr/share/icons/apache_pb2.png
/usr/share/icons/apache_pb2_ani.gif
/usr/share/icons/back.gif
/usr/share/icons/back.png
/usr/share/icons/ball.gray.gif
/usr/share/icons/ball.gray.png
/usr/share/icons/ball.red.gif
/usr/share/icons/ball.red.png
/usr/share/icons/binary.gif
/usr/share/icons/binary.png
/usr/share/icons/binhex.gif
/usr/share/icons/binhex.png
/usr/share/icons/blank.gif
/usr/share/icons/blank.png
/usr/share/icons/bomb.gif
/usr/share/icons/bomb.png
/usr/share/icons/box1.gif
/usr/share/icons/box1.png
/usr/share/icons/box2.gif
/usr/share/icons/box2.png
/usr/share/icons/broken.gif
/usr/share/icons/broken.png
/usr/share/icons/burst.gif
/usr/share/icons/burst.png
/usr/share/icons/c.gif
/usr/share/icons/c.png
/usr/share/icons/comp.blue.gif
/usr/share/icons/comp.blue.png
/usr/share/icons/comp.gray.gif
/usr/share/icons/comp.gray.png
/usr/share/icons/compressed.gif
/usr/share/icons/compressed.png
/usr/share/icons/continued.gif
/usr/share/icons/continued.png
/usr/share/icons/dir.gif
/usr/share/icons/dir.png
/usr/share/icons/diskimg.gif
/usr/share/icons/diskimg.png
/usr/share/icons/down.gif
/usr/share/icons/down.png
/usr/share/icons/dvi.gif
/usr/share/icons/dvi.png
/usr/share/icons/f.gif
/usr/share/icons/f.png
/usr/share/icons/folder.gif
/usr/share/icons/folder.open.gif
/usr/share/icons/folder.open.png
/usr/share/icons/folder.png
/usr/share/icons/folder.sec.gif
/usr/share/icons/folder.sec.png
/usr/share/icons/forward.gif
/usr/share/icons/forward.png
/usr/share/icons/generic.gif
/usr/share/icons/generic.png
/usr/share/icons/generic.red.gif
/usr/share/icons/generic.red.png
/usr/share/icons/generic.sec.gif
/usr/share/icons/generic.sec.png
/usr/share/icons/hand.right.gif
/usr/share/icons/hand.right.png
/usr/share/icons/hand.up.gif
/usr/share/icons/hand.up.png
/usr/share/icons/icon.sheet.gif
/usr/share/icons/icon.sheet.png
/usr/share/icons/image1.gif
/usr/share/icons/image1.png
/usr/share/icons/image2.gif
/usr/share/icons/image2.png
/usr/share/icons/image3.gif
/usr/share/icons/image3.png
/usr/share/icons/index.gif
/usr/share/icons/index.png
/usr/share/icons/layout.gif
/usr/share/icons/layout.png
/usr/share/icons/left.gif
/usr/share/icons/left.png
/usr/share/icons/link.gif
/usr/share/icons/link.png
/usr/share/icons/movie.gif
/usr/share/icons/movie.png
/usr/share/icons/p.gif
/usr/share/icons/p.png
/usr/share/icons/patch.gif
/usr/share/icons/patch.png
/usr/share/icons/pdf.gif
/usr/share/icons/pdf.png
/usr/share/icons/pie0.gif
/usr/share/icons/pie0.png
/usr/share/icons/pie1.gif
/usr/share/icons/pie1.png
/usr/share/icons/pie2.gif
/usr/share/icons/pie2.png
/usr/share/icons/pie3.gif
/usr/share/icons/pie3.png
/usr/share/icons/pie4.gif
/usr/share/icons/pie4.png
/usr/share/icons/pie5.gif
/usr/share/icons/pie5.png
/usr/share/icons/pie6.gif
/usr/share/icons/pie6.png
/usr/share/icons/pie7.gif
/usr/share/icons/pie7.png
/usr/share/icons/pie8.gif
/usr/share/icons/pie8.png
/usr/share/icons/portal.gif
/usr/share/icons/portal.png
/usr/share/icons/ps.gif
/usr/share/icons/ps.png
/usr/share/icons/quill.gif
/usr/share/icons/quill.png
/usr/share/icons/right.gif
/usr/share/icons/right.png
/usr/share/icons/screw1.gif
/usr/share/icons/screw1.png
/usr/share/icons/screw2.gif
/usr/share/icons/screw2.png
/usr/share/icons/script.gif
/usr/share/icons/script.png
/usr/share/icons/small/back.gif
/usr/share/icons/small/back.png
/usr/share/icons/small/binary.gif
/usr/share/icons/small/binary.png
/usr/share/icons/small/binhex.gif
/usr/share/icons/small/binhex.png
/usr/share/icons/small/blank.gif
/usr/share/icons/small/blank.png
/usr/share/icons/small/broken.gif
/usr/share/icons/small/broken.png
/usr/share/icons/small/burst.gif
/usr/share/icons/small/burst.png
/usr/share/icons/small/comp1.gif
/usr/share/icons/small/comp1.png
/usr/share/icons/small/comp2.gif
/usr/share/icons/small/comp2.png
/usr/share/icons/small/compressed.gif
/usr/share/icons/small/compressed.png
/usr/share/icons/small/continued.gif
/usr/share/icons/small/continued.png
/usr/share/icons/small/dir.gif
/usr/share/icons/small/dir.png
/usr/share/icons/small/dir2.gif
/usr/share/icons/small/dir2.png
/usr/share/icons/small/doc.gif
/usr/share/icons/small/doc.png
/usr/share/icons/small/forward.gif
/usr/share/icons/small/forward.png
/usr/share/icons/small/generic.gif
/usr/share/icons/small/generic.png
/usr/share/icons/small/generic2.gif
/usr/share/icons/small/generic2.png
/usr/share/icons/small/generic3.gif
/usr/share/icons/small/generic3.png
/usr/share/icons/small/image.gif
/usr/share/icons/small/image.png
/usr/share/icons/small/image2.gif
/usr/share/icons/small/image2.png
/usr/share/icons/small/index.gif
/usr/share/icons/small/index.png
/usr/share/icons/small/key.gif
/usr/share/icons/small/key.png
/usr/share/icons/small/movie.gif
/usr/share/icons/small/movie.png
/usr/share/icons/small/patch.gif
/usr/share/icons/small/patch.png
/usr/share/icons/small/ps.gif
/usr/share/icons/small/ps.png
/usr/share/icons/small/rainbow.gif
/usr/share/icons/small/rainbow.png
/usr/share/icons/small/sound.gif
/usr/share/icons/small/sound.png
/usr/share/icons/small/sound2.gif
/usr/share/icons/small/sound2.png
/usr/share/icons/small/tar.gif
/usr/share/icons/small/tar.png
/usr/share/icons/small/text.gif
/usr/share/icons/small/text.png
/usr/share/icons/small/transfer.gif
/usr/share/icons/small/transfer.png
/usr/share/icons/small/unknown.gif
/usr/share/icons/small/unknown.png
/usr/share/icons/small/uu.gif
/usr/share/icons/small/uu.png
/usr/share/icons/sound1.gif
/usr/share/icons/sound1.png
/usr/share/icons/sound2.gif
/usr/share/icons/sound2.png
/usr/share/icons/sphere1.gif
/usr/share/icons/sphere1.png
/usr/share/icons/sphere2.gif
/usr/share/icons/sphere2.png
/usr/share/icons/tar.gif
/usr/share/icons/tar.png
/usr/share/icons/tex.gif
/usr/share/icons/tex.png
/usr/share/icons/text.gif
/usr/share/icons/text.png
/usr/share/icons/transfer.gif
/usr/share/icons/transfer.png
/usr/share/icons/unknown.gif
/usr/share/icons/unknown.png
/usr/share/icons/up.gif
/usr/share/icons/up.png
/usr/share/icons/uu.gif
/usr/share/icons/uu.png
/usr/share/icons/uuencoded.gif
/usr/share/icons/uuencoded.png
/usr/share/icons/world1.gif
/usr/share/icons/world1.png
/usr/share/icons/world2.gif
/usr/share/icons/world2.png
/usr/share/man/man1/dbmmanage.1.gz
/usr/share/man/man1/htdbm.1.gz
/usr/share/man/man1/htdigest.1.gz
/usr/share/man/man1/htpasswd.1.gz
/usr/share/man/man1/httxt2dbm.1.gz
/usr/share/man/man8/ab.8.gz
/usr/share/man/man8/apachectl.8.gz
/usr/share/man/man8/apxs.8.gz
/usr/share/man/man8/htcacheclean.8.gz
/usr/share/man/man8/httpd.8.gz
/usr/share/man/man8/logresolve.8.gz
/usr/share/man/man8/rotatelogs.8.gz
/usr/share/man/man8/suexec.8.gz

%changelog
