Name:		node
Version:	v0.10.15
Release:	1%{?dist}
Summary:	nodejs

Group:		Hisoku
License:	No
URL:		http://hisoku.ronny.tw/
Source0:	node-v0.10.15.tar.gz
# http://nodejs.org/dist/v0.10.15/node-v0.10.15.tar.gz
BuildRoot:	%(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

%description


%prep
%setup -q

%build
./configure 
make %{?_smp_mflags}


%install
rm -rf %{buildroot}
make install DESTDIR=%{buildroot}


%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc
/usr/local/bin/node
/usr/local/bin/npm
/usr/local/lib/dtrace/node.d
/usr/local/lib/node_modules/npm/.npmignore
/usr/local/lib/node_modules/npm/.tern-project
/usr/local/lib/node_modules/npm/AUTHORS
/usr/local/lib/node_modules/npm/LICENSE
/usr/local/lib/node_modules/npm/Makefile
/usr/local/lib/node_modules/npm/README.md
/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp
/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp.cmd
/usr/local/lib/node_modules/npm/bin/npm
/usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/lib/node_modules/npm/bin/npm.cmd
/usr/local/lib/node_modules/npm/bin/read-package-json.js
/usr/local/lib/node_modules/npm/cli.js
/usr/local/lib/node_modules/npm/configure
/usr/local/lib/node_modules/npm/doc/api/npm-bin.md
/usr/local/lib/node_modules/npm/doc/api/npm-bugs.md
/usr/local/lib/node_modules/npm/doc/api/npm-commands.md
/usr/local/lib/node_modules/npm/doc/api/npm-config.md
/usr/local/lib/node_modules/npm/doc/api/npm-deprecate.md
/usr/local/lib/node_modules/npm/doc/api/npm-docs.md
/usr/local/lib/node_modules/npm/doc/api/npm-edit.md
/usr/local/lib/node_modules/npm/doc/api/npm-explore.md
/usr/local/lib/node_modules/npm/doc/api/npm-help-search.md
/usr/local/lib/node_modules/npm/doc/api/npm-init.md
/usr/local/lib/node_modules/npm/doc/api/npm-install.md
/usr/local/lib/node_modules/npm/doc/api/npm-link.md
/usr/local/lib/node_modules/npm/doc/api/npm-load.md
/usr/local/lib/node_modules/npm/doc/api/npm-ls.md
/usr/local/lib/node_modules/npm/doc/api/npm-outdated.md
/usr/local/lib/node_modules/npm/doc/api/npm-owner.md
/usr/local/lib/node_modules/npm/doc/api/npm-pack.md
/usr/local/lib/node_modules/npm/doc/api/npm-prefix.md
/usr/local/lib/node_modules/npm/doc/api/npm-prune.md
/usr/local/lib/node_modules/npm/doc/api/npm-publish.md
/usr/local/lib/node_modules/npm/doc/api/npm-rebuild.md
/usr/local/lib/node_modules/npm/doc/api/npm-restart.md
/usr/local/lib/node_modules/npm/doc/api/npm-root.md
/usr/local/lib/node_modules/npm/doc/api/npm-run-script.md
/usr/local/lib/node_modules/npm/doc/api/npm-search.md
/usr/local/lib/node_modules/npm/doc/api/npm-shrinkwrap.md
/usr/local/lib/node_modules/npm/doc/api/npm-start.md
/usr/local/lib/node_modules/npm/doc/api/npm-stop.md
/usr/local/lib/node_modules/npm/doc/api/npm-submodule.md
/usr/local/lib/node_modules/npm/doc/api/npm-tag.md
/usr/local/lib/node_modules/npm/doc/api/npm-test.md
/usr/local/lib/node_modules/npm/doc/api/npm-uninstall.md
/usr/local/lib/node_modules/npm/doc/api/npm-unpublish.md
/usr/local/lib/node_modules/npm/doc/api/npm-update.md
/usr/local/lib/node_modules/npm/doc/api/npm-version.md
/usr/local/lib/node_modules/npm/doc/api/npm-view.md
/usr/local/lib/node_modules/npm/doc/api/npm-whoami.md
/usr/local/lib/node_modules/npm/doc/api/npm.md
/usr/local/lib/node_modules/npm/doc/cli/npm-adduser.md
/usr/local/lib/node_modules/npm/doc/cli/npm-bin.md
/usr/local/lib/node_modules/npm/doc/cli/npm-bugs.md
/usr/local/lib/node_modules/npm/doc/cli/npm-build.md
/usr/local/lib/node_modules/npm/doc/cli/npm-bundle.md
/usr/local/lib/node_modules/npm/doc/cli/npm-cache.md
/usr/local/lib/node_modules/npm/doc/cli/npm-completion.md
/usr/local/lib/node_modules/npm/doc/cli/npm-config.md
/usr/local/lib/node_modules/npm/doc/cli/npm-dedupe.md
/usr/local/lib/node_modules/npm/doc/cli/npm-deprecate.md
/usr/local/lib/node_modules/npm/doc/cli/npm-docs.md
/usr/local/lib/node_modules/npm/doc/cli/npm-edit.md
/usr/local/lib/node_modules/npm/doc/cli/npm-explore.md
/usr/local/lib/node_modules/npm/doc/cli/npm-help-search.md
/usr/local/lib/node_modules/npm/doc/cli/npm-help.md
/usr/local/lib/node_modules/npm/doc/cli/npm-init.md
/usr/local/lib/node_modules/npm/doc/cli/npm-install.md
/usr/local/lib/node_modules/npm/doc/cli/npm-link.md
/usr/local/lib/node_modules/npm/doc/cli/npm-ls.md
/usr/local/lib/node_modules/npm/doc/cli/npm-outdated.md
/usr/local/lib/node_modules/npm/doc/cli/npm-owner.md
/usr/local/lib/node_modules/npm/doc/cli/npm-pack.md
/usr/local/lib/node_modules/npm/doc/cli/npm-prefix.md
/usr/local/lib/node_modules/npm/doc/cli/npm-prune.md
/usr/local/lib/node_modules/npm/doc/cli/npm-publish.md
/usr/local/lib/node_modules/npm/doc/cli/npm-rebuild.md
/usr/local/lib/node_modules/npm/doc/cli/npm-restart.md
/usr/local/lib/node_modules/npm/doc/cli/npm-rm.md
/usr/local/lib/node_modules/npm/doc/cli/npm-root.md
/usr/local/lib/node_modules/npm/doc/cli/npm-run-script.md
/usr/local/lib/node_modules/npm/doc/cli/npm-search.md
/usr/local/lib/node_modules/npm/doc/cli/npm-shrinkwrap.md
/usr/local/lib/node_modules/npm/doc/cli/npm-star.md
/usr/local/lib/node_modules/npm/doc/cli/npm-stars.md
/usr/local/lib/node_modules/npm/doc/cli/npm-start.md
/usr/local/lib/node_modules/npm/doc/cli/npm-stop.md
/usr/local/lib/node_modules/npm/doc/cli/npm-submodule.md
/usr/local/lib/node_modules/npm/doc/cli/npm-tag.md
/usr/local/lib/node_modules/npm/doc/cli/npm-test.md
/usr/local/lib/node_modules/npm/doc/cli/npm-uninstall.md
/usr/local/lib/node_modules/npm/doc/cli/npm-unpublish.md
/usr/local/lib/node_modules/npm/doc/cli/npm-update.md
/usr/local/lib/node_modules/npm/doc/cli/npm-version.md
/usr/local/lib/node_modules/npm/doc/cli/npm-view.md
/usr/local/lib/node_modules/npm/doc/cli/npm-whoami.md
/usr/local/lib/node_modules/npm/doc/cli/npm.md
/usr/local/lib/node_modules/npm/doc/files/npm-folders.md
/usr/local/lib/node_modules/npm/doc/files/npmrc.md
/usr/local/lib/node_modules/npm/doc/files/package.json.md
/usr/local/lib/node_modules/npm/doc/misc/npm-coding-style.md
/usr/local/lib/node_modules/npm/doc/misc/npm-config.md
/usr/local/lib/node_modules/npm/doc/misc/npm-developers.md
/usr/local/lib/node_modules/npm/doc/misc/npm-disputes.md
/usr/local/lib/node_modules/npm/doc/misc/npm-faq.md
/usr/local/lib/node_modules/npm/doc/misc/npm-index.md
/usr/local/lib/node_modules/npm/doc/misc/npm-registry.md
/usr/local/lib/node_modules/npm/doc/misc/npm-scripts.md
/usr/local/lib/node_modules/npm/doc/misc/removing-npm.md
/usr/local/lib/node_modules/npm/doc/misc/semver.md
/usr/local/lib/node_modules/npm/html/doc/README.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-bin.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-bugs.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-commands.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-config.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-deprecate.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-docs.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-edit.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-explore.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-help-search.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-init.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-install.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-link.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-load.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-ls.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-outdated.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-owner.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-pack.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-prefix.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-prune.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-publish.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-rebuild.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-restart.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-root.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-run-script.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-search.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-shrinkwrap.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-start.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-stop.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-submodule.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-tag.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-test.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-uninstall.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-unpublish.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-update.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-version.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-view.html
/usr/local/lib/node_modules/npm/html/doc/api/npm-whoami.html
/usr/local/lib/node_modules/npm/html/doc/api/npm.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-adduser.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-bin.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-bugs.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-build.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-bundle.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-cache.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-completion.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-config.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-dedupe.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-deprecate.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-docs.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-edit.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-explore.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-help-search.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-help.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-init.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-install.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-link.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-ls.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-outdated.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-owner.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-pack.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-prefix.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-prune.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-publish.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-rebuild.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-restart.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-rm.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-root.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-run-script.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-search.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-shrinkwrap.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-star.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-stars.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-start.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-stop.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-submodule.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-tag.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-test.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-uninstall.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-unpublish.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-update.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-version.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-view.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm-whoami.html
/usr/local/lib/node_modules/npm/html/doc/cli/npm.html
/usr/local/lib/node_modules/npm/html/doc/files/npm-folders.html
/usr/local/lib/node_modules/npm/html/doc/files/npm-global.html
/usr/local/lib/node_modules/npm/html/doc/files/npm-json.html
/usr/local/lib/node_modules/npm/html/doc/files/npmrc.html
/usr/local/lib/node_modules/npm/html/doc/files/package.json.html
/usr/local/lib/node_modules/npm/html/doc/index.html
/usr/local/lib/node_modules/npm/html/doc/misc/npm-coding-style.html
/usr/local/lib/node_modules/npm/html/doc/misc/npm-config.html
/usr/local/lib/node_modules/npm/html/doc/misc/npm-developers.html
/usr/local/lib/node_modules/npm/html/doc/misc/npm-disputes.html
/usr/local/lib/node_modules/npm/html/doc/misc/npm-faq.html
/usr/local/lib/node_modules/npm/html/doc/misc/npm-index.html
/usr/local/lib/node_modules/npm/html/doc/misc/npm-registry.html
/usr/local/lib/node_modules/npm/html/doc/misc/npm-scripts.html
/usr/local/lib/node_modules/npm/html/doc/misc/removing-npm.html
/usr/local/lib/node_modules/npm/html/doc/misc/semver.html
/usr/local/lib/node_modules/npm/html/docfoot-script.html
/usr/local/lib/node_modules/npm/html/docfoot.html
/usr/local/lib/node_modules/npm/html/dochead.html
/usr/local/lib/node_modules/npm/html/favicon.ico
/usr/local/lib/node_modules/npm/html/index.html
/usr/local/lib/node_modules/npm/html/static/style.css
/usr/local/lib/node_modules/npm/html/static/webfonts/23242D_3_0.eot
/usr/local/lib/node_modules/npm/html/static/webfonts/23242D_3_0.ttf
/usr/local/lib/node_modules/npm/html/static/webfonts/23242D_3_0.woff
/usr/local/lib/node_modules/npm/lib/adduser.js
/usr/local/lib/node_modules/npm/lib/bin.js
/usr/local/lib/node_modules/npm/lib/bugs.js
/usr/local/lib/node_modules/npm/lib/build.js
/usr/local/lib/node_modules/npm/lib/cache.js
/usr/local/lib/node_modules/npm/lib/completion.js
/usr/local/lib/node_modules/npm/lib/config.js
/usr/local/lib/node_modules/npm/lib/dedupe.js
/usr/local/lib/node_modules/npm/lib/deprecate.js
/usr/local/lib/node_modules/npm/lib/docs.js
/usr/local/lib/node_modules/npm/lib/edit.js
/usr/local/lib/node_modules/npm/lib/explore.js
/usr/local/lib/node_modules/npm/lib/faq.js
/usr/local/lib/node_modules/npm/lib/get.js
/usr/local/lib/node_modules/npm/lib/help-search.js
/usr/local/lib/node_modules/npm/lib/help.js
/usr/local/lib/node_modules/npm/lib/init.js
/usr/local/lib/node_modules/npm/lib/install.js
/usr/local/lib/node_modules/npm/lib/link.js
/usr/local/lib/node_modules/npm/lib/ls.js
/usr/local/lib/node_modules/npm/lib/npm.js
/usr/local/lib/node_modules/npm/lib/outdated.js
/usr/local/lib/node_modules/npm/lib/owner.js
/usr/local/lib/node_modules/npm/lib/pack.js
/usr/local/lib/node_modules/npm/lib/prefix.js
/usr/local/lib/node_modules/npm/lib/prune.js
/usr/local/lib/node_modules/npm/lib/publish.js
/usr/local/lib/node_modules/npm/lib/rebuild.js
/usr/local/lib/node_modules/npm/lib/restart.js
/usr/local/lib/node_modules/npm/lib/root.js
/usr/local/lib/node_modules/npm/lib/run-script.js
/usr/local/lib/node_modules/npm/lib/search.js
/usr/local/lib/node_modules/npm/lib/set.js
/usr/local/lib/node_modules/npm/lib/shrinkwrap.js
/usr/local/lib/node_modules/npm/lib/star.js
/usr/local/lib/node_modules/npm/lib/stars.js
/usr/local/lib/node_modules/npm/lib/start.js
/usr/local/lib/node_modules/npm/lib/stop.js
/usr/local/lib/node_modules/npm/lib/submodule.js
/usr/local/lib/node_modules/npm/lib/substack.js
/usr/local/lib/node_modules/npm/lib/tag.js
/usr/local/lib/node_modules/npm/lib/test.js
/usr/local/lib/node_modules/npm/lib/unbuild.js
/usr/local/lib/node_modules/npm/lib/uninstall.js
/usr/local/lib/node_modules/npm/lib/unpublish.js
/usr/local/lib/node_modules/npm/lib/update.js
/usr/local/lib/node_modules/npm/lib/utils/completion.sh
/usr/local/lib/node_modules/npm/lib/utils/completion/file-completion.js
/usr/local/lib/node_modules/npm/lib/utils/completion/installed-deep.js
/usr/local/lib/node_modules/npm/lib/utils/completion/installed-shallow.js
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js
/usr/local/lib/node_modules/npm/lib/utils/fetch.js
/usr/local/lib/node_modules/npm/lib/utils/find-prefix.js
/usr/local/lib/node_modules/npm/lib/utils/gently-rm.js
/usr/local/lib/node_modules/npm/lib/utils/is-git-url.js
/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js
/usr/local/lib/node_modules/npm/lib/utils/link.js
/usr/local/lib/node_modules/npm/lib/utils/tar.js
/usr/local/lib/node_modules/npm/lib/version.js
/usr/local/lib/node_modules/npm/lib/view.js
/usr/local/lib/node_modules/npm/lib/visnup.js
/usr/local/lib/node_modules/npm/lib/whoami.js
/usr/local/lib/node_modules/npm/lib/xmas.js
/usr/local/lib/node_modules/npm/man/man1/npm-README.1
/usr/local/lib/node_modules/npm/man/man1/npm-adduser.1
/usr/local/lib/node_modules/npm/man/man1/npm-bin.1
/usr/local/lib/node_modules/npm/man/man1/npm-bugs.1
/usr/local/lib/node_modules/npm/man/man1/npm-build.1
/usr/local/lib/node_modules/npm/man/man1/npm-bundle.1
/usr/local/lib/node_modules/npm/man/man1/npm-cache.1
/usr/local/lib/node_modules/npm/man/man1/npm-completion.1
/usr/local/lib/node_modules/npm/man/man1/npm-config.1
/usr/local/lib/node_modules/npm/man/man1/npm-dedupe.1
/usr/local/lib/node_modules/npm/man/man1/npm-deprecate.1
/usr/local/lib/node_modules/npm/man/man1/npm-docs.1
/usr/local/lib/node_modules/npm/man/man1/npm-edit.1
/usr/local/lib/node_modules/npm/man/man1/npm-explore.1
/usr/local/lib/node_modules/npm/man/man1/npm-help-search.1
/usr/local/lib/node_modules/npm/man/man1/npm-help.1
/usr/local/lib/node_modules/npm/man/man1/npm-init.1
/usr/local/lib/node_modules/npm/man/man1/npm-install.1
/usr/local/lib/node_modules/npm/man/man1/npm-link.1
/usr/local/lib/node_modules/npm/man/man1/npm-ls.1
/usr/local/lib/node_modules/npm/man/man1/npm-outdated.1
/usr/local/lib/node_modules/npm/man/man1/npm-owner.1
/usr/local/lib/node_modules/npm/man/man1/npm-pack.1
/usr/local/lib/node_modules/npm/man/man1/npm-prefix.1
/usr/local/lib/node_modules/npm/man/man1/npm-prune.1
/usr/local/lib/node_modules/npm/man/man1/npm-publish.1
/usr/local/lib/node_modules/npm/man/man1/npm-rebuild.1
/usr/local/lib/node_modules/npm/man/man1/npm-restart.1
/usr/local/lib/node_modules/npm/man/man1/npm-rm.1
/usr/local/lib/node_modules/npm/man/man1/npm-root.1
/usr/local/lib/node_modules/npm/man/man1/npm-run-script.1
/usr/local/lib/node_modules/npm/man/man1/npm-search.1
/usr/local/lib/node_modules/npm/man/man1/npm-shrinkwrap.1
/usr/local/lib/node_modules/npm/man/man1/npm-star.1
/usr/local/lib/node_modules/npm/man/man1/npm-stars.1
/usr/local/lib/node_modules/npm/man/man1/npm-start.1
/usr/local/lib/node_modules/npm/man/man1/npm-stop.1
/usr/local/lib/node_modules/npm/man/man1/npm-submodule.1
/usr/local/lib/node_modules/npm/man/man1/npm-tag.1
/usr/local/lib/node_modules/npm/man/man1/npm-test.1
/usr/local/lib/node_modules/npm/man/man1/npm-uninstall.1
/usr/local/lib/node_modules/npm/man/man1/npm-unpublish.1
/usr/local/lib/node_modules/npm/man/man1/npm-update.1
/usr/local/lib/node_modules/npm/man/man1/npm-version.1
/usr/local/lib/node_modules/npm/man/man1/npm-view.1
/usr/local/lib/node_modules/npm/man/man1/npm-whoami.1
/usr/local/lib/node_modules/npm/man/man1/npm.1
/usr/local/lib/node_modules/npm/man/man3/npm-bin.3
/usr/local/lib/node_modules/npm/man/man3/npm-bugs.3
/usr/local/lib/node_modules/npm/man/man3/npm-commands.3
/usr/local/lib/node_modules/npm/man/man3/npm-config.3
/usr/local/lib/node_modules/npm/man/man3/npm-deprecate.3
/usr/local/lib/node_modules/npm/man/man3/npm-docs.3
/usr/local/lib/node_modules/npm/man/man3/npm-edit.3
/usr/local/lib/node_modules/npm/man/man3/npm-explore.3
/usr/local/lib/node_modules/npm/man/man3/npm-help-search.3
/usr/local/lib/node_modules/npm/man/man3/npm-init.3
/usr/local/lib/node_modules/npm/man/man3/npm-install.3
/usr/local/lib/node_modules/npm/man/man3/npm-link.3
/usr/local/lib/node_modules/npm/man/man3/npm-load.3
/usr/local/lib/node_modules/npm/man/man3/npm-ls.3
/usr/local/lib/node_modules/npm/man/man3/npm-outdated.3
/usr/local/lib/node_modules/npm/man/man3/npm-owner.3
/usr/local/lib/node_modules/npm/man/man3/npm-pack.3
/usr/local/lib/node_modules/npm/man/man3/npm-prefix.3
/usr/local/lib/node_modules/npm/man/man3/npm-prune.3
/usr/local/lib/node_modules/npm/man/man3/npm-publish.3
/usr/local/lib/node_modules/npm/man/man3/npm-rebuild.3
/usr/local/lib/node_modules/npm/man/man3/npm-restart.3
/usr/local/lib/node_modules/npm/man/man3/npm-root.3
/usr/local/lib/node_modules/npm/man/man3/npm-run-script.3
/usr/local/lib/node_modules/npm/man/man3/npm-search.3
/usr/local/lib/node_modules/npm/man/man3/npm-shrinkwrap.3
/usr/local/lib/node_modules/npm/man/man3/npm-start.3
/usr/local/lib/node_modules/npm/man/man3/npm-stop.3
/usr/local/lib/node_modules/npm/man/man3/npm-submodule.3
/usr/local/lib/node_modules/npm/man/man3/npm-tag.3
/usr/local/lib/node_modules/npm/man/man3/npm-test.3
/usr/local/lib/node_modules/npm/man/man3/npm-uninstall.3
/usr/local/lib/node_modules/npm/man/man3/npm-unpublish.3
/usr/local/lib/node_modules/npm/man/man3/npm-update.3
/usr/local/lib/node_modules/npm/man/man3/npm-version.3
/usr/local/lib/node_modules/npm/man/man3/npm-view.3
/usr/local/lib/node_modules/npm/man/man3/npm-whoami.3
/usr/local/lib/node_modules/npm/man/man3/npm.3
/usr/local/lib/node_modules/npm/man/man5/npm-folders.5
/usr/local/lib/node_modules/npm/man/man5/npm-global.5
/usr/local/lib/node_modules/npm/man/man5/npm-json.5
/usr/local/lib/node_modules/npm/man/man5/npmrc.5
/usr/local/lib/node_modules/npm/man/man5/package.json.5
/usr/local/lib/node_modules/npm/man/man7/npm-coding-style.7
/usr/local/lib/node_modules/npm/man/man7/npm-config.7
/usr/local/lib/node_modules/npm/man/man7/npm-developers.7
/usr/local/lib/node_modules/npm/man/man7/npm-disputes.7
/usr/local/lib/node_modules/npm/man/man7/npm-faq.7
/usr/local/lib/node_modules/npm/man/man7/npm-index.7
/usr/local/lib/node_modules/npm/man/man7/npm-registry.7
/usr/local/lib/node_modules/npm/man/man7/npm-scripts.7
/usr/local/lib/node_modules/npm/man/man7/removing-npm.7
/usr/local/lib/node_modules/npm/man/man7/semver.7
/usr/local/lib/node_modules/npm/node_modules/abbrev/LICENSE
/usr/local/lib/node_modules/npm/node_modules/abbrev/README.md
/usr/local/lib/node_modules/npm/node_modules/abbrev/lib/abbrev.js
/usr/local/lib/node_modules/npm/node_modules/abbrev/package.json
/usr/local/lib/node_modules/npm/node_modules/ansi/.npmignore
/usr/local/lib/node_modules/npm/node_modules/ansi/README.md
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/beep/index.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/clear/index.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/cursorPosition.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/imgcat/index.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/imgcat/yoshi.png
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/progress/index.js
/usr/local/lib/node_modules/npm/node_modules/ansi/examples/starwars.js
/usr/local/lib/node_modules/npm/node_modules/ansi/lib/ansi.js
/usr/local/lib/node_modules/npm/node_modules/ansi/lib/newlines.js
/usr/local/lib/node_modules/npm/node_modules/ansi/package.json
/usr/local/lib/node_modules/npm/node_modules/archy/README.markdown
/usr/local/lib/node_modules/npm/node_modules/archy/index.js
/usr/local/lib/node_modules/npm/node_modules/archy/package.json
/usr/local/lib/node_modules/npm/node_modules/block-stream/LICENCE
/usr/local/lib/node_modules/npm/node_modules/block-stream/README.md
/usr/local/lib/node_modules/npm/node_modules/block-stream/bench/block-stream-pause.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/bench/block-stream.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/bench/dropper-pause.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/bench/dropper.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js
/usr/local/lib/node_modules/npm/node_modules/block-stream/package.json
/usr/local/lib/node_modules/npm/node_modules/child-process-close/README.md
/usr/local/lib/node_modules/npm/node_modules/child-process-close/index.js
/usr/local/lib/node_modules/npm/node_modules/child-process-close/package.json
/usr/local/lib/node_modules/npm/node_modules/chmodr/LICENSE
/usr/local/lib/node_modules/npm/node_modules/chmodr/README.md
/usr/local/lib/node_modules/npm/node_modules/chmodr/chmodr.js
/usr/local/lib/node_modules/npm/node_modules/chmodr/package.json
/usr/local/lib/node_modules/npm/node_modules/chownr/LICENCE
/usr/local/lib/node_modules/npm/node_modules/chownr/README.md
/usr/local/lib/node_modules/npm/node_modules/chownr/chownr.js
/usr/local/lib/node_modules/npm/node_modules/chownr/package.json
/usr/local/lib/node_modules/npm/node_modules/cmd-shim/.npmignore
/usr/local/lib/node_modules/npm/node_modules/cmd-shim/LICENSE
/usr/local/lib/node_modules/npm/node_modules/cmd-shim/README.md
/usr/local/lib/node_modules/npm/node_modules/cmd-shim/index.js
/usr/local/lib/node_modules/npm/node_modules/cmd-shim/package.json
/usr/local/lib/node_modules/npm/node_modules/editor/README.markdown
/usr/local/lib/node_modules/npm/node_modules/editor/example/beep.json
/usr/local/lib/node_modules/npm/node_modules/editor/example/edit.js
/usr/local/lib/node_modules/npm/node_modules/editor/index.js
/usr/local/lib/node_modules/npm/node_modules/editor/package.json
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/.npmignore
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/LICENCE
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/README.md
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/bundle.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/dir-tar.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/dir.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/example.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/ig-tar.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/example/tar.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/.npmignore
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/LICENSE
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/README.md
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/example/basic.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/package.json
/usr/local/lib/node_modules/npm/node_modules/fstream-npm/package.json
/usr/local/lib/node_modules/npm/node_modules/fstream/.npmignore
/usr/local/lib/node_modules/npm/node_modules/fstream/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/fstream/LICENSE
/usr/local/lib/node_modules/npm/node_modules/fstream/README.md
/usr/local/lib/node_modules/npm/node_modules/fstream/examples/filter-pipe.js
/usr/local/lib/node_modules/npm/node_modules/fstream/examples/pipe.js
/usr/local/lib/node_modules/npm/node_modules/fstream/examples/reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/examples/symlink-write.js
/usr/local/lib/node_modules/npm/node_modules/fstream/fstream.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/abstract.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/collect.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/file-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/file-writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/get-type.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/link-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/link-writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/proxy-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/proxy-writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/socket-reader.js
/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js
/usr/local/lib/node_modules/npm/node_modules/fstream/package.json
/usr/local/lib/node_modules/npm/node_modules/glob/.npmignore
/usr/local/lib/node_modules/npm/node_modules/glob/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/glob/LICENSE
/usr/local/lib/node_modules/npm/node_modules/glob/README.md
/usr/local/lib/node_modules/npm/node_modules/glob/examples/g.js
/usr/local/lib/node_modules/npm/node_modules/glob/examples/usr-local.js
/usr/local/lib/node_modules/npm/node_modules/glob/glob.js
/usr/local/lib/node_modules/npm/node_modules/glob/package.json
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/.npmignore
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/LICENSE
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/README.md
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/package.json
/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js
/usr/local/lib/node_modules/npm/node_modules/inherits/LICENSE
/usr/local/lib/node_modules/npm/node_modules/inherits/README.md
/usr/local/lib/node_modules/npm/node_modules/inherits/inherits.js
/usr/local/lib/node_modules/npm/node_modules/inherits/package.json
/usr/local/lib/node_modules/npm/node_modules/ini/LICENSE
/usr/local/lib/node_modules/npm/node_modules/ini/README.md
/usr/local/lib/node_modules/npm/node_modules/ini/ini.js
/usr/local/lib/node_modules/npm/node_modules/ini/package.json
/usr/local/lib/node_modules/npm/node_modules/init-package-json/README.md
/usr/local/lib/node_modules/npm/node_modules/init-package-json/default-input.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/example.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/init-package-json.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/.npmignore
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/README.md
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/index.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/npm-init/README.md
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/npm-init/init-input.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/npm-init/init.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/npm-init/package.json
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/example/substack-input.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/package.json
/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js
/usr/local/lib/node_modules/npm/node_modules/init-package-json/package.json
/usr/local/lib/node_modules/npm/node_modules/lockfile/LICENSE
/usr/local/lib/node_modules/npm/node_modules/lockfile/README.md
/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js
/usr/local/lib/node_modules/npm/node_modules/lockfile/package.json
/usr/local/lib/node_modules/npm/node_modules/lru-cache/.npmignore
/usr/local/lib/node_modules/npm/node_modules/lru-cache/AUTHORS
/usr/local/lib/node_modules/npm/node_modules/lru-cache/LICENSE
/usr/local/lib/node_modules/npm/node_modules/lru-cache/README.md
/usr/local/lib/node_modules/npm/node_modules/lru-cache/lib/lru-cache.js
/usr/local/lib/node_modules/npm/node_modules/lru-cache/package.json
/usr/local/lib/node_modules/npm/node_modules/lru-cache/s.js
/usr/local/lib/node_modules/npm/node_modules/minimatch/LICENSE
/usr/local/lib/node_modules/npm/node_modules/minimatch/README.md
/usr/local/lib/node_modules/npm/node_modules/minimatch/minimatch.js
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/LICENSE
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/README.md
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/bench.js
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/package.json
/usr/local/lib/node_modules/npm/node_modules/minimatch/node_modules/sigmund/sigmund.js
/usr/local/lib/node_modules/npm/node_modules/minimatch/package.json
/usr/local/lib/node_modules/npm/node_modules/mkdirp/.npmignore
/usr/local/lib/node_modules/npm/node_modules/mkdirp/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/mkdirp/LICENSE
/usr/local/lib/node_modules/npm/node_modules/mkdirp/README.markdown
/usr/local/lib/node_modules/npm/node_modules/mkdirp/examples/pow.js
/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js
/usr/local/lib/node_modules/npm/node_modules/mkdirp/package.json
/usr/local/lib/node_modules/npm/node_modules/node-gyp/.jshintrc
/usr/local/lib/node_modules/npm/node_modules/node-gyp/.npmignore
/usr/local/lib/node_modules/npm/node_modules/node-gyp/LICENSE
/usr/local/lib/node_modules/npm/node_modules/node-gyp/README.md
/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi
/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/.npmignore
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/AUTHORS
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/DEPS
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/LICENSE
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/MANIFEST
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/OWNERS
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/PRESUBMIT.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/codereview.settings
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/data/win/large-pdb-shim.cc
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp.bat
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_dummy.c
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyptest.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSNew.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSProject.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSToolFile.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSUserFile.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSUtil.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSVersion.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/SCons.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/easy_xml.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/easy_xml_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/__init__.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/android.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/dump_dependency_json.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/eclipse.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/gypd.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/gypsh.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja_test.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/scons.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/mac_tool.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/msvs_emulation.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/ninja_syntax.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/sun_tool.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/win_tool.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xml_fix.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylintrc
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/samples/samples
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/samples/samples.bat
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/setup.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/README
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/Xcode/README
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/Xcode/Specifications/gyp.pbfilespec
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/Xcode/Specifications/gyp.xclangspec
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/README
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/gyp-tests.el
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/gyp.el
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/run-unit-tests.sh
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/testdata/media.gyp
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs/testdata/media.gyp.fontified
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/graphviz.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_gyp.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_sln.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_vcproj.py
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/clean.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/list.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/rebuild.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/remove.js
/usr/local/lib/node_modules/npm/node_modules/node-gyp/package.json
/usr/local/lib/node_modules/npm/node_modules/nopt/.npmignore
/usr/local/lib/node_modules/npm/node_modules/nopt/LICENSE
/usr/local/lib/node_modules/npm/node_modules/nopt/README.md
/usr/local/lib/node_modules/npm/node_modules/nopt/bin/nopt.js
/usr/local/lib/node_modules/npm/node_modules/nopt/examples/my-program.js
/usr/local/lib/node_modules/npm/node_modules/nopt/lib/nopt.js
/usr/local/lib/node_modules/npm/node_modules/nopt/package.json
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/README.md
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/index.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/star.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/stars.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/tag.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/unpublish.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/upload.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/README.md
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/couch-login.js
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login/package.json
/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/package.json
/usr/local/lib/node_modules/npm/node_modules/npm-user-validate/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npm-user-validate/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/npm-user-validate/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npm-user-validate/README.md
/usr/local/lib/node_modules/npm/node_modules/npm-user-validate/npm-user-validate.js
/usr/local/lib/node_modules/npm/node_modules/npm-user-validate/package.json
/usr/local/lib/node_modules/npm/node_modules/npmconf/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npmconf/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npmconf/README.md
/usr/local/lib/node_modules/npm/node_modules/npmconf/config-defs.js
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/.npmignore
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/LICENCE
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/index.js
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/node_modules/proto-list/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/node_modules/proto-list/README.md
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/node_modules/proto-list/package.json
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/node_modules/proto-list/proto-list.js
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/package.json
/usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/readme.markdown
/usr/local/lib/node_modules/npm/node_modules/npmconf/npmconf.js
/usr/local/lib/node_modules/npm/node_modules/npmconf/package.json
/usr/local/lib/node_modules/npm/node_modules/npmlog/LICENSE
/usr/local/lib/node_modules/npm/node_modules/npmlog/README.md
/usr/local/lib/node_modules/npm/node_modules/npmlog/example.js
/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js
/usr/local/lib/node_modules/npm/node_modules/npmlog/package.json
/usr/local/lib/node_modules/npm/node_modules/once/LICENSE
/usr/local/lib/node_modules/npm/node_modules/once/README.md
/usr/local/lib/node_modules/npm/node_modules/once/once.js
/usr/local/lib/node_modules/npm/node_modules/once/package.json
/usr/local/lib/node_modules/npm/node_modules/opener/LICENSE.txt
/usr/local/lib/node_modules/npm/node_modules/opener/README.md
/usr/local/lib/node_modules/npm/node_modules/opener/opener.js
/usr/local/lib/node_modules/npm/node_modules/opener/package.json
/usr/local/lib/node_modules/npm/node_modules/osenv/LICENSE
/usr/local/lib/node_modules/npm/node_modules/osenv/README.md
/usr/local/lib/node_modules/npm/node_modules/osenv/osenv.js
/usr/local/lib/node_modules/npm/node_modules/osenv/package.json
/usr/local/lib/node_modules/npm/node_modules/read-installed/LICENSE
/usr/local/lib/node_modules/npm/node_modules/read-installed/README.md
/usr/local/lib/node_modules/npm/node_modules/read-installed/package.json
/usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js
/usr/local/lib/node_modules/npm/node_modules/read-package-json/LICENSE
/usr/local/lib/node_modules/npm/node_modules/read-package-json/README.md
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/.npmignore
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/AUTHORS
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/LICENSE
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/README.md
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/extract_description.js
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/typos.json
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/node_modules/github-url-from-git/.npmignore
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/node_modules/github-url-from-git/History.md
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/node_modules/github-url-from-git/Makefile
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/node_modules/github-url-from-git/Readme.md
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/node_modules/github-url-from-git/index.js
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/node_modules/github-url-from-git/package.json
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/node_modules/github-url-from-git/test.js
/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/package.json
/usr/local/lib/node_modules/npm/node_modules/read-package-json/package.json
/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js
/usr/local/lib/node_modules/npm/node_modules/read/.npmignore
/usr/local/lib/node_modules/npm/node_modules/read/LICENCE
/usr/local/lib/node_modules/npm/node_modules/read/README.md
/usr/local/lib/node_modules/npm/node_modules/read/example/example.js
/usr/local/lib/node_modules/npm/node_modules/read/lib/read.js
/usr/local/lib/node_modules/npm/node_modules/read/node_modules/mute-stream/LICENSE
/usr/local/lib/node_modules/npm/node_modules/read/node_modules/mute-stream/README.md
/usr/local/lib/node_modules/npm/node_modules/read/node_modules/mute-stream/mute.js
/usr/local/lib/node_modules/npm/node_modules/read/node_modules/mute-stream/package.json
/usr/local/lib/node_modules/npm/node_modules/read/package.json
/usr/local/lib/node_modules/npm/node_modules/read/rs.js
/usr/local/lib/node_modules/npm/node_modules/request/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/README.md
/usr/local/lib/node_modules/npm/node_modules/request/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/aws-sign/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/aws-sign/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/aws-sign/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/aws-sign/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/cookie-jar/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/cookie-jar/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/cookie-jar/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/cookie-jar/jar.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/cookie-jar/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/cookie-jar/tests/run.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/cookie-jar/tests/test-cookie.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/cookie-jar/tests/test-cookiejar.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/forever-agent/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/forever-agent/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/forever-agent/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/forever-agent/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/License
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/Readme.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/lib/form_data.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node-form-data.sublime-project
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node-form-data.sublime-workspace
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/async/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/async/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/async/component.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/async/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/License
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/Readme.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/License
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/Readme.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/sftp-config.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/example/usage.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/images/hawk.png
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/images/logo.png
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/lib/browser.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/lib/client.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/lib/crypto.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/lib/server.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/lib/utils.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/images/boom.png
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/images/hoek.png
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/lib/escape.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/node_modules/hoek/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/boom/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/images/hoek.png
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/lib/escape.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/hoek/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/examples/offset.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/examples/time.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/Makefile
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/images/hoek.png
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/lib/escape.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/node_modules/hoek/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/sntp/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/.dir-locals.el
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/http_signing.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/parser.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/signer.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/util.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/verify.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/lib/ber/errors.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/lib/ber/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/lib/ber/reader.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/lib/ber/types.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/lib/ber/writer.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/lib/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/tst/ber/reader.test.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1/tst/ber/writer.test.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/assert-plus/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/assert-plus/assert.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/assert-plus/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/CHANGELOG
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/README
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/README.old
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/ctf.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/ctio.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/ctype.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/man/man3ctype/ctio.3ctype
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tools/jsl.conf
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tools/jsstyle
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/float.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/int.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/psinfo.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/struct.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/tst.fail.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/tst.float.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/tst.int.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/tst.psinfo.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/tst.struct.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/tst.typedef.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctf/typedef.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/float/tst.rfloat.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/float/tst.wfloat.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/int/tst.64.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/int/tst.rint.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/int/tst.wbounds.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/int/tst.wint.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/uint/tst.64.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/uint/tst.roundtrip.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/uint/tst.ruint.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctio/uint/tst.wuint.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctype/tst.basicr.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctype/tst.basicw.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctype/tst.char.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctype/tst.endian.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctype/tst.oldwrite.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctype/tst.readSize.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctype/tst.structw.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/tst/ctype/tst.writeStruct.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/json-stringify-safe/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/json-stringify-safe/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/json-stringify-safe/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/json-stringify-safe/stringify.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/json-stringify-safe/test.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/mime/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/mime/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/mime/mime.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/mime/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/mime/test.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/mime/types/mime.types
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/mime/types/node.types
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/LICENSE.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/benchmark/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/benchmark/bench.gnu
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/benchmark/bench.sh
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/benchmark/benchmark-native.c
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/benchmark/benchmark.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/uuid.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/oauth-sign/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/oauth-sign/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/oauth-sign/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/oauth-sign/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/oauth-sign/test.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/qs/.gitmodules
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/qs/.npmignore
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/qs/Readme.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/qs/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/qs/package.json
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/LICENSE
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/README.md
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/package.json
/usr/local/lib/node_modules/npm/node_modules/request/package.json
/usr/local/lib/node_modules/npm/node_modules/request/tests/googledoodle.jpg
/usr/local/lib/node_modules/npm/node_modules/request/tests/run.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/server.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/squid.conf
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.cnf
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.crl
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.crt
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.csr
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.key
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/ca.srl
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.cnf
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.crt
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.csr
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/ca/server.key
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/npm-ca.crt
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/test.crt
/usr/local/lib/node_modules/npm/node_modules/request/tests/ssl/test.key
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-basic-auth.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-body.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-defaults.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-digest-auth.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-emptyBody.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-errors.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-follow-all-303.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-follow-all.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-form.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-hawk.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-headers.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-http-signature.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-httpModule.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-https-strict.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-https.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-localAddress.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-oauth.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-onelineproxy.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-params.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-piped-redirect.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-pipes.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-pool.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-protocol-changing-redirect.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-proxy.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-qs.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-redirect.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-s3.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-timeout.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-toJSON.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/test-tunnel.js
/usr/local/lib/node_modules/npm/node_modules/request/tests/unicycle.jpg
/usr/local/lib/node_modules/npm/node_modules/retry/.npmignore
/usr/local/lib/node_modules/npm/node_modules/retry/License
/usr/local/lib/node_modules/npm/node_modules/retry/Makefile
/usr/local/lib/node_modules/npm/node_modules/retry/Readme.md
/usr/local/lib/node_modules/npm/node_modules/retry/equation.gif
/usr/local/lib/node_modules/npm/node_modules/retry/example/dns.js
/usr/local/lib/node_modules/npm/node_modules/retry/index.js
/usr/local/lib/node_modules/npm/node_modules/retry/lib/retry.js
/usr/local/lib/node_modules/npm/node_modules/retry/lib/retry_operation.js
/usr/local/lib/node_modules/npm/node_modules/retry/package.json
/usr/local/lib/node_modules/npm/node_modules/rimraf/AUTHORS
/usr/local/lib/node_modules/npm/node_modules/rimraf/LICENSE
/usr/local/lib/node_modules/npm/node_modules/rimraf/README.md
/usr/local/lib/node_modules/npm/node_modules/rimraf/bin.js
/usr/local/lib/node_modules/npm/node_modules/rimraf/package.json
/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js
/usr/local/lib/node_modules/npm/node_modules/semver/.npmignore
/usr/local/lib/node_modules/npm/node_modules/semver/LICENSE
/usr/local/lib/node_modules/npm/node_modules/semver/Makefile
/usr/local/lib/node_modules/npm/node_modules/semver/README.md
/usr/local/lib/node_modules/npm/node_modules/semver/bin/semver
/usr/local/lib/node_modules/npm/node_modules/semver/foot.js
/usr/local/lib/node_modules/npm/node_modules/semver/head.js
/usr/local/lib/node_modules/npm/node_modules/semver/package.json
/usr/local/lib/node_modules/npm/node_modules/semver/r.js
/usr/local/lib/node_modules/npm/node_modules/semver/semver.browser.js
/usr/local/lib/node_modules/npm/node_modules/semver/semver.browser.js.gz
/usr/local/lib/node_modules/npm/node_modules/semver/semver.js
/usr/local/lib/node_modules/npm/node_modules/semver/semver.min.js
/usr/local/lib/node_modules/npm/node_modules/semver/semver.min.js.gz
/usr/local/lib/node_modules/npm/node_modules/sha/.npmignore
/usr/local/lib/node_modules/npm/node_modules/sha/LICENSE
/usr/local/lib/node_modules/npm/node_modules/sha/README.md
/usr/local/lib/node_modules/npm/node_modules/sha/index.js
/usr/local/lib/node_modules/npm/node_modules/sha/package.json
/usr/local/lib/node_modules/npm/node_modules/slide/LICENSE
/usr/local/lib/node_modules/npm/node_modules/slide/README.md
/usr/local/lib/node_modules/npm/node_modules/slide/index.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map-ordered.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js
/usr/local/lib/node_modules/npm/node_modules/slide/lib/slide.js
/usr/local/lib/node_modules/npm/node_modules/slide/package.json
/usr/local/lib/node_modules/npm/node_modules/tar/.npmignore
/usr/local/lib/node_modules/npm/node_modules/tar/.travis.yml
/usr/local/lib/node_modules/npm/node_modules/tar/LICENCE
/usr/local/lib/node_modules/npm/node_modules/tar/README.md
/usr/local/lib/node_modules/npm/node_modules/tar/examples/extracter.js
/usr/local/lib/node_modules/npm/node_modules/tar/examples/reader.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/buffer-entry.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/entry-writer.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/entry.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/extract.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/global-header-writer.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/header.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/pack.js
/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js
/usr/local/lib/node_modules/npm/node_modules/tar/package.json
/usr/local/lib/node_modules/npm/node_modules/tar/tar.js
/usr/local/lib/node_modules/npm/node_modules/uid-number/LICENCE
/usr/local/lib/node_modules/npm/node_modules/uid-number/README.md
/usr/local/lib/node_modules/npm/node_modules/uid-number/get-uid-gid.js
/usr/local/lib/node_modules/npm/node_modules/uid-number/package.json
/usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js
/usr/local/lib/node_modules/npm/node_modules/which/LICENSE
/usr/local/lib/node_modules/npm/node_modules/which/README.md
/usr/local/lib/node_modules/npm/node_modules/which/bin/which
/usr/local/lib/node_modules/npm/node_modules/which/package.json
/usr/local/lib/node_modules/npm/node_modules/which/which.js
/usr/local/lib/node_modules/npm/package.json
/usr/local/lib/node_modules/npm/scripts/clean-old.sh
/usr/local/lib/node_modules/npm/scripts/doc-build.sh
/usr/local/lib/node_modules/npm/scripts/index-build.js
/usr/local/lib/node_modules/npm/scripts/install.sh
/usr/local/lib/node_modules/npm/scripts/release.sh
/usr/local/lib/node_modules/npm/scripts/relocate.sh
/usr/local/share/man/man1/node.1

%changelog
