#!/usr/bin/env php
<?php

// 處理 MachineStatus 的資料，如果遇到沒有更新資料、CPU 過高、硬碟快滿等狀況
// 就要寄信警告
include(__DIR__ . '/../../webdata/init.inc.php');

$messages = array();
foreach (Machine::search(1) as $machine) {
    $machine_status = $machine->statuses->order('updated_at DESC')->first();

    // 看看十分鐘內有沒有記錄
    if (!$machine_status or (time() - $machine_status->updated_at > 600)) {
        $messages[] = array($machine, "超過十分鐘沒有回傳記錄了, 上次時間：" . date('c', $machine->updated_at));
        continue;
    }

    // 處理 CPU Loads
    if (!$loads = $machine_status->getLoads()) {
        $messages[] = array($machine, "無法正確取得 cpu load");
    } else {
        if ($loads[0] > 3) {
            $messages[] = array($machine, "CPU Loading 過高: " . $loads[0]);
            // TODO: 要回傳 process list
        }
    }

    // 處理硬碟 quota
    if (!$disk_infos = $machine_status->getDiskInfos()) {
        $messages[] = array($machine, "無法正確取得硬碟資訊");
    } else {
        foreach ($disk_infos as $disk_info) {
            if ($disk_info->disk_capacity and trim($disk_info->disk_capacity, '%') > 70) {
                $messages[] = array($machine, "硬碟 {$disk_info->mount_point} 使用空間超過 70%: " . $disk_info->disk_capacity);
            }
            if ($disk_info->inode_capacity and trim($disk_info->inode_capacity, '%') > 70) {
                $messages[] = array($machine, "iNode {$disk_info->mount_point} 使用空間超過 70%: " . $disk_info->inode_capacity);
            }
        }
    }
}

if ($messages) {
    $content = '';
    foreach ($messages as $message) {
        $content .= long2ip($message[0]->ip) . ' ' . $message[1] . "\n";
    }
    Hisoku::alert("Middle2 警告: " . date('Y/m/d H:i:s'), $content);
}
