#!/usr/bin/env php
<?php

// 處理 MachineStatus 的資料，如果遇到沒有更新資料、CPU 過高、硬碟快滿等狀況
// 就要寄信警告
include(__DIR__ . '/../../webdata/init.inc.php');

// 先睡 20 秒，這樣可以等各機器的資料傳好，比較即時判斷
sleep(20);

$cache = new Pix_Cache;

$messages = array();
foreach (Machine::search(1) as $machine) {
    $machine_status = $machine->statuses->order('updated_at DESC')->first();

    // 看看十分鐘內有沒有記錄
    if (!$machine_status or (time() - $machine_status->updated_at > 600)) {
        $messages[] = array($machine, "超過十分鐘沒有回傳記錄了, 上次時間：" . date('c', $machine_status->updated_at));
        continue;
    }

    // 處理 CPU Loads
    if (!$loads = $machine_status->getLoads()) {
        $messages[] = array($machine, "無法正確取得 cpu load", $machine_status);
    } else {
        if ($loads[0] > 4) {
            $messages[] = array($machine, "CPU Loading 過高: " . $loads[0], $machine_status);
        }
    }

    // 處理硬碟 quota
    if (!$disk_infos = $machine_status->getDiskInfos()) {
        $messages[] = array($machine, "無法正確取得硬碟資訊", $machine_status);
    } else {
        foreach ($disk_infos as $disk_info) {
            if ($disk_info->disk_capacity and trim($disk_info->disk_capacity, '%') > 90) {
                $messages[] = array($machine, "硬碟 {$disk_info->mount_point} 使用空間超過 90%: " . $disk_info->disk_capacity, $machine_status);
            } elseif ($disk_info->disk_capacity and trim($disk_info->disk_capacity, '%') > 80) {
                // 一小時只噴一次，以免被信件灌爆
                $cache_key = "MachineStatus:{$machine->machine_id}:diskover80-sent";
                $last_sent = $cache->get($cache_key);
                if (!$last_sent or time() - $last_sent > 3600) {
                    $messages[] = array($machine, "硬碟 {$disk_info->mount_point} 使用空間超過 80%: " . $disk_info->disk_capacity, $machine_status);
                    $cache->set($cache_key, time());
                }
            }

            if ($disk_info->inode_capacity and trim($disk_info->inode_capacity, '%') > 90) {
                $messages[] = array($machine, "iNode {$disk_info->mount_point} 使用空間超過 90%: " . $disk_info->inode_capacity, $machine_status);
            } elseif ($disk_info->inode_capacity and trim($disk_info->inode_capacity, '%') > 80) {
                // 一小時只噴一次，以免被信件灌爆
                $cache_key = "MachineStatus:{$machine->machine_id}:inodeover80-sent";
                $last_sent = $cache->get($cache_key);
                if (!$last_sent or time() - $last_sent > 3600) {
                    $messages[] = array($machine, "iNode {$disk_info->mount_point} 使用空間超過 80%: " . $disk_info->inode_capacity, $machine_status);
                    $cache->set($cache_key, time());
                }
            }
        }
    }
}

if ($messages) {
    $content = '';
    foreach ($messages as $message) {
        $content .= sprintf("%s (%s) %s\n", long2ip($message[0]->ip), $message[0]->groups, $message[1]);
        if ($status = $message[2]) {
            $content .= "https://middle2.com/admin/machinelog/{$status->machine_id}/{$status->updated_at}\n";
        }
    }
    Hisoku::alert("Middle2 警告: " . date('Y/m/d H:i:s'), $content);
}
