#!/usr/bin/env php
<?php

include(__DIR__ . '/../webdata/init.inc.php');

function error($message)
{
    error_log($message);
}

function main()
{
    if (!getenv('SSH_ORIGINAL_COMMAND')) {
        return error('There is no SSH_ORIGINAL_COMMAND env');
    }

    $command = getenv('SSH_ORIGINAL_COMMAND');
    list($method) = explode(' ', $command, 2);
    switch ($method) {
    case 'init': // init $nodes_count
        list(, $nodes_count) = explode(' ', $command, 2);
        $nodes_count = intval($nodes_count);
        if (!$nodes_count) {
            die("invalid nodes_count\n");
        }

        $view = new Pix_Partial(__DIR__ . '/../webdata/views');
        for ($i = 1; $i <= $nodes_count; $i ++) {
            exec("cp --preserve=mode,ownership,timestamps --recursive /srv/chroot/template /srv/chroot/{$i}");
            // comment Listen 80
            exec("sed -i 's/^Listen 80$/#Listen 80/' /srv/chroot/{$i}/etc/httpd/conf/httpd.conf");
            if (!file_exists("/srv/chroot/{$i}/srv/web")) {
                mkdir("/srv/chroot/{$i}/srv/web");
            }
            $vhost_conf = $view->partial('config/apache-vhost.conf.phtml', array('port' => 20000 + $i, 'id' => $i));
            file_put_contents("/srv/chroot/{$i}/etc/httpd/conf.d/node.conf", $vhost_conf);
        }
        break;

    case 'clone':
        list(, $project, $id) = explode(' ', getenv('SSH_ORIGINAL_COMMAND'));
        if (!$id) {
            die("invalid $id");
        }
        exec("rm -rf /srv/chroot/{$id}/srv/web");
        exec("git clone git@" . GIT_SERVER . ":{$project}.git /srv/chroot/{$id}/srv/web");
        break;
    }
    return;
}

main();
