#!/usr/bin/env php
<?php

include(__DIR__ . '/../webdata/init.inc.php');

if (count($_SERVER['argv']) < 2) {
    die('Usage: get-nodes-by-domain domain' . PHP_EOL);
}

$domain = strval($_SERVER['argv'][1]);

// TODO: support custom domain
list($request_host, $request_port) = explode(':', $domain);
if (!preg_match('#(.*)\.hisoku\.ronny\.tw$#', $request_host, $matches)) {
    die('unknwon domain: ' . $request_host. PHP_EOL);
}

$project_name = $matches[1];
if (!$project = Project::find_by_name($project_name)) {
    die('unknwon domain: ' . $request_host. PHP_EOL);
}

// find current
$nodes = WebNode::search(array('project_id' => $project->id, 'commit' => $project->commit));
if (count($nodes)) {
    foreach ($nodes as $node) {
        echo long2ip($node->ip) . ':' . $node->port . "\n";
    }
    exit;
}

// TODO: check deploying

$choosed_nodes = array();
while (true) {
    $free_nodes_count = count(WebNode::search(array('project_id' => 0)));
    if (!$free_nodes_count) {
        die('no free nodes' . PHP_EOL);
    }

    if (!$random_node = WebNode::search(array('project_id' => 0))->offset(rand(0, $free_nodes_count - 1))->first()) {
        continue;
    }

    $random_node->update(array('project_id' => $project->id, 'commit' => $project->commit));

    $node_id = $random_node->port - 20000;
    $ip = long2ip($random_node->ip);
    exec("ssh deploy@{$ip} clone {$project->name} {$node_id}");
    
    $choosed_nodes[] = $random_node;

    if (count($choosed_nodes) >= 1) {
        break;
    }
}

foreach ($choosed_nodes as $node) {
    echo long2ip($node->ip) . ':' . $node->port . "\n";
}
