#!/usr/bin/env php
<?php

include(__DIR__ . '/../webdata/init.inc.php');

$ips = array();
for ($i = 1; $i < count($_SERVER['argv']); $i ++) {
    foreach (Hisoku::getIPsByGroup($_SERVER['argv'][$i]) as $ip) {
        $ips[$ip] = true;
    }
}
echo implode(' ', array_keys($ips));
