#!/usr/bin/env php
<?php

include(__DIR__ . '/../webdata/init.inc.php');

$fp = fopen('php://stdin', 'r');
$content = '';
while (false !== ($line = fgets($fp))) {
    $content .= $line;
}
list($oldrev, $newrev, $refname) = explode(' ', trim($content));

// {id}.git
$path = basename(getcwd());
if (!preg_match('#^(\d+)\.git$#', $path, $matches)) {
    // FIXME
    error_log('invalid path name: ' . $path);
    exit;
}
if (!$project = Project::find(intval($matches[1]))) {
    // FIXME
    error_log('invalid project id: ' . $matches[1]);
    exit;
}

// TODO: deploy to webnode
$project->update(array('commit' => $newrev));

error_log('deploy finished. visit http://' . $project->getFirstDomain() . '/');
