#!/usr/bin/env php
<?php

include(__DIR__ . '/../webdata/init.inc.php');

function error($message)
{
    error_log($message);
    die();
}

function main()
{
    if (!getenv('SSH_ORIGINAL_COMMAND')) {
        return error('There is no SSH_ORIGINAL_COMMAND env');
    }

    $command = getenv('SSH_ORIGINAL_COMMAND');
    list($method) = explode(' ', $command, 2);
    switch ($method) {
    case 'reload-apache': // init $nodes_count
        exec('apachectl graceful');
        break;

    case 'restart-php-fpm':
        list(, $id) = explode(' ', getenv('SSH_ORIGINAL_COMMAND'));
        if (!$id = intval($id)) {
            error('invalid id: ' . $id);
        }
        if (file_exists("/srv/deploy/{$id}.pid")) {
            exec('kill ' . intval(file_get_contents("/srv/deploy/{$id}.pid")));
        }
        exec("php-fpm -y /srv/deploy/etc/{$id}.conf");
        if (!file_exists("/srv/chroot/{$id}/dev/null")) {
            exec("mknod /srv/chroot/{$id}/dev/null c 1 3");
            exec("mknod /srv/chroot/{$id}/dev/random c 1 8");
            exec("mknod /srv/chroot/{$id}/dev/urandom c 1 9");
            exec("chmod 666 /srv/chroot/{$id}/dev/*");
        }
        exec("mkdir -p /srv/chroot/{$id}/usr/local/apache2/logs/fastcgi/dynamic");
	exec("chown www-user /srv/chroot/{$id}/usr/local/apache2/logs/");
        exec("chroot --userspec=10003:99 /srv/chroot/{$id}/ /usr/local/apache2/bin/apachectl start");
        break;

    case 'reload-php-fpm':
        list(, $id) = explode(' ', getenv('SSH_ORIGINAL_COMMAND'));
        if (!$id = intval($id)) {
            error('invalid id: ' . $id);
        }
        if (file_exists("/srv/deploy/{$id}.pid")) {
            exec('kill -s SIGUSR2 ' . intval(file_get_contents("/srv/deploy/{$id}.pid")));
        } else {
            exec("php-fpm -y /srv/deploy/etc/{$id}.conf");
        }
        exec("chroot --userspec=10003:99 /srv/chroot/{$id}/ /usr/local/apache2/bin/apachectl graceful");
        break;

    }
    return;
}

main();
