#!/usr/bin/env php
<?php
include(__DIR__ . '/../webdata/init.inc.php');

if ('git' !== getenv('USER')) {
    die('git user only' . PHP_EOL);
}

$public_key = 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAv5o3c0ukue9lZKTqJhSKM1uH3CGLUUNVT1XKQB3WN+IxOOWQw8l5Sr9ipZ2wRVHE3NLY/jSgg6w8VjW1Ig9gwtquGpdbjEDLBRZYQZwtzVtgN5q8+isxIUpfUlJikd86hmMN4QF0VVRkQq8VLkVLN8xkatmeyXcAXZSrrDjP02CXe+W25MjHR+qsLJAc0COT9c+2Q30tU1mA3CKKuMoacQstijdiwJvgyiNWcAlejBQnTU7JnnzcKQxVTRCjtvlItYjuWRbzqho+nc5/fOQukn5w7uES0sceEUcnkzX2u7h2uM3u77S93FeQKQO/u+IvszX3EpVxBd7aw+Stg87nAw== root@ip-10-146-23-10';

$deploy_keys = array(
    'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCz/uP56Ud1nLKysJ8CiO7VCSJq57Q0vGHrEDK26UU6z3cPHHQ3i/DYE8N9rygD0zCh/5kIaHlP7BxPdDGo2KkcsJuZm6mRRvd0qzDsj7ZVjr5WbKn1ffwbJJWZG5P+K5bYotRuIPs+yumqMz7NHMTfQ0GAbEKhmAJI0rmfHOpLbKkPiEIQzzhuGHS38ecvljVnYpEjSBDJBNlef0ei6xFveWfPRXHu+DPvnCUiwVAD3NdnOoaWV0sb1NmdYgqPG4mkvHHFxy5VkhRqTyZodjrVrle48V7F+7qMAU+y35TAQWgvk7ZOvmyDuaD64ThSuzJ96g4+cxv15VjLG038qpUH root@ip-10-0-0-159',
    'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3NZO/df+cUjv7B29srHW4BgRcMUHoxo0mb4By8pAQqA7Jrm2xHSR0m2lWC7DORiiS5Ov47qDBxqDSHavAuIqpFM83PXteuyQ2j3WrSaAMUNO80eZKFAC6/7i1lLsOwfaSw7n72GDVO17YzMshZGymnDWSm204Hp90g1UlJP16hNIKKeO5h8izkvVFM3mhLEdcwlzWOtfnWEv4cGffNWiv2yO6VnMCqrSLu2FWTMhCx347JxnM3PgKfT6TDmeTvku8wNomkjTqstdA08AYMo8rA8xzIutyalqkjjItgMFWX4nFltMgC2QeCxWBGWgOpcDF3ZFngnc3giB7oshvvEJV root@ip-10-0-0-121',
);


$content = '### generated at ' . date('Y/m/d H:i:s') . "\n";
$content .= "# deploy-keys\n";
foreach ($deploy_keys as $deploy_key) {
    $content .= 'command="/srv/code/hisoku/scripts/deploy-key-archive-only",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' . $deploy_key . "\n";
}
$content .= "# update-keys\n";
$content .= 'command="/srv/code/hisoku/scripts/update-keys",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' . $public_key . "\n";
$content .= "# user keys\n";
foreach (UserKey::search(1) as $user_key) {
    $content .= 'command="/srv/code/hisoku/scripts/ssh-serve ' . $user_key->user->name . '",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' . $user_key->key_body . "\n";
}

file_put_contents(getenv('HOME') . '/.ssh/authorized_keys', $content);
