#!/usr/bin/env php
<?php
include(__DIR__ . '/../webdata/init.inc.php');

if ('git' !== getenv('USER')) {
    die('git user only' . PHP_EOL);
}

$public_key = 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAv5o3c0ukue9lZKTqJhSKM1uH3CGLUUNVT1XKQB3WN+IxOOWQw8l5Sr9ipZ2wRVHE3NLY/jSgg6w8VjW1Ig9gwtquGpdbjEDLBRZYQZwtzVtgN5q8+isxIUpfUlJikd86hmMN4QF0VVRkQq8VLkVLN8xkatmeyXcAXZSrrDjP02CXe+W25MjHR+qsLJAc0COT9c+2Q30tU1mA3CKKuMoacQstijdiwJvgyiNWcAlejBQnTU7JnnzcKQxVTRCjtvlItYjuWRbzqho+nc5/fOQukn5w7uES0sceEUcnkzX2u7h2uM3u77S93FeQKQO/u+IvszX3EpVxBd7aw+Stg87nAw== root@ip-10-146-23-10';

$deploy_keys = array(
    'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1o2xYPGHNkpdmNs9WTWrTcspE4Zt+YCEPyyq13maBUAWkCvS2Gm2bAiagXFkzHic8DRIcGL9amO43G7IzJtvCn98zacCPCgzGJni6UIGIK+43uGiCFm4yWsq2EollAwGmJB7K9rSnmqksUYjagkv45US+4K9A4xvWtLSaRK/8E2B9uCPAt21OMIbgWY6cnVpaAwp2IMNHVqBUer3h7+tTQDBXyCYFqXwRMQ35mS2UYxDCgUC13QG1ARxkhoXFqR2C1D6yAahmkLqpwL/iyVP2nbgjyraTxBOF9+QWGr4r8ILoiNBa6ZXkshd/vFmzNKnaTf0klPkRNrB1GlaV0ypOQ== root@ip-10-0-0-98',
    'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu6SKu0B64NBcWK9G2gl7rtSvCvfGmF3LT1UXF+sRChv8bEjHJHwOQmkOwYnCRN6wdfawq0HT3bZ7YpXwiJhmqrAHdR1xAhKgwqHiCJAZdbKTXgyQV/duCGaJYx/AeeRbA3nEM19fsC7BcuGe5qvg1/W+PqqBApKU5wHpfYy0ZGo/D64vpPb2oLranOGDm+ZxOmw/JAh4kTnsYkc57TPJPLZ2z3eRyAfx2sYHIGOr0mUK7F5X2x5PS3Hs1o/My6bxnJ1yHdvFcuF/wJuMUWtx/tLXlFidRuqwb6+cH5uOoZCykIB32Rpa8ZuDpCg+/t3z4nwnE8nEXvwAo+Fb5e5zXQ== root@ip-10-0-0-104',
);


$content = '### generated at ' . date('Y/m/d H:i:s') . "\n";
$content .= "# deploy-keys\n";
foreach ($deploy_keys as $deploy_key) {
    $content .= 'command="/srv/code/hisoku/scripts/deploy-key-archive-only",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' . $deploy_key . "\n";
}
$content .= "# update-keys\n";
$content .= 'command="/srv/code/hisoku/scripts/update-keys",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' . $public_key . "\n";
$content .= "# user keys\n";
foreach (UserKey::search(1) as $user_key) {
    $content .= 'command="/srv/code/hisoku/scripts/ssh-serve ' . $user_key->user->name . '",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' . $user_key->key_body . "\n";
}

file_put_contents(getenv('HOME') . '/.ssh/authorized_keys', $content);
