#!/usr/bin/php
<?php

include(__DIR__ . '/../webdata/init.inc.php');

// 回傳這台機器的 uptime, cpu load, disk, maximum process 等資訊
$ret = new StdClass;
$ret->hostname = gethostname();
$ret->uname = trim(`uname -a`);

// 硬碟資訊
$disks = array();

$df_result = explode("\n", trim(`df -P -a`));
for ($i = 1; $i < count($df_result); $i ++) {
    $rows = preg_split('/\s+/', trim($df_result[$i]));
    $columns = array('id', 'disk_total', 'disk_usage', 'disk_available', 'disk_capacity', 'mount_point');

    $disks[$rows[0]] = array_combine($columns, $rows);
}

$df_result = explode("\n", trim(`df -P -i`));
for ($i = 1; $i < count($df_result); $i ++) {
    $rows = preg_split('/\s+/', trim($df_result[$i]));
    $columns = array('id', 'inode_total', 'inode_usage', 'inode_available', 'inode_capacity', 'mount_point');

    $disks[$rows[0]] = array_merge($disks[$rows[0]], array_combine($columns, $rows));
}
$ret->disk = array_values($disks);

// cpu 資訊
if ($ret->process = trim(`top -w 200 -b -n 1 -c`)) {
} else if ($ret->process = trim(`top -b -n 1 -c`)) {
}
$ret->dmesg = trim(`dmesg | tail -n 100`);

// memory info
$ret->memory = new StdClass;
foreach (explode("\n", trim(file_get_contents('/proc/meminfo'))) as $line) {
    list($key, $value) = array_map('trim', explode(':', $line));
    $ret->memory->{$key} = $value;
}

// TODO: 增加 firewall 是否有正常跑起來的資訊
$curl = curl_init('https://' . getenv('MAINPAGE_DOMAIN') . '/api/updatemachinestatus');
curl_setopt($curl, CURLOPT_POSTFIELDS, 'status=' . urlencode(json_encode($ret, JSON_UNESCAPED_UNICODE)));
curl_exec($curl);
curl_close($curl);
