#!/usr/bin/env php
<?php
include(__DIR__ . '/../webdata/init.inc.php');

if ('git' !== getenv('USER')) {
    die('git user only' . PHP_EOL);
}

$public_keys = array(
    'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDH32ZXsqqw/t4w0YHJhsfdSaNQNmUBQj/aEzBKbqW4mNRY3CsEshtg95HZk2Lyo9KDP1g0ZRftilsXwHgFla80NJbIzP3UpSaNKembGPJmirXjyQNzar6ho3GpQP84ZGrYQW6sPUtHYY3XPEs6H7SOTTWSNZ757IEiIUaRglfZzwxe8lOxc5YxAQ6HL4XJNRd0mbdogdr3zIIY++WNylRQ0M+omHmsA+soD5AJBiCEy3BsS5IOc/k4nxCuDeLu15LcxC3SG5EFi1OTZ+eA2y0h/WmSoKF2ybwxgGTX5VLbwlqiStaqJqLMavE0bi+TzkUBzr8tEbgeo6v+DqWrg1cF www@m2',
);

$deploy_keys = array(
    'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAMZhu7K5LIT1ncCgCy1cU5MHfMb1Jfi6PnSruhLyjHMUy4GMWc4pFlHHftzeMMIIHU3CgTB462ELDCze93OW33TxTjEXZ8lIzIU+ZIwDufyer+/7vRd9lqtRozTNZq+v9BvJJsjChdxkiG8OLITNXMXqtbKynPEbE7QDEdWFGAHWCqUZabGrw4rd4jzTX0jxGh0wREUl9S+dctoIZAFGcQmpLEIjsxQnWuGh88KbhCNHwkzgVepbwn1i8AeXEjpKHepcVprEdd3BSZu53RMvOjzPppVgSfvaVauZvJPUSyAwSbMrZ67tJ98yfGsINDu048VtlXG8i2FRyJv20b2PX root@m2-lb',
    'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt0m5zhw6XJCQ3UsUgnf1SmkU9MdOwGX086Oc1TjLNJQRdndMP4DObN51pBn2ASLMNGxe/MNg8cjyINtgOYjqXbAR0WcF6dH9C80lFOU/gfh+ajZy14+BhSMYpmLUaNW0wEcYuHuoDm/z99MGozAju05AuGg6Msqxde5IxiCuOz3B/Jz7aGItt2FCWFyAveifsc3Ib6zCnULG6xPZ78Z2YGx9m3oHlPvmwLMqiey0LsXG/IB6IkUl22C0CFg7y4MqQXWgPjyctfmYZJYyfnf4P7EZosk1jcXLaFTl9h1cLgOcg6Fke4w4VGAgfSdsd8DPrsvpAbKR2aegxgRvkqw0v root@m2-nodes-1',
);


$content = '### generated at ' . date('Y/m/d H:i:s') . "\n";
$content .= "# deploy-keys\n";
foreach ($deploy_keys as $deploy_key) {
    $content .= 'command="/srv/code/hisoku/scripts/deploy-key-archive-only",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' . $deploy_key . "\n";
}
$content .= "# update-keys\n";
foreach ($public_keys as $public_key) {
    $content .= 'command="/srv/code/hisoku/scripts/update-keys",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' . $public_key . "\n";
}
$content .= "# user keys\n";
foreach (UserKey::search(1) as $user_key) {
    $content .= "command=\"/srv/code/hisoku/scripts/ssh-serve {$user_key->user->name} {$user_key->id}\",no-port-forwarding,no-X11-forwarding,no-agent-forwarding {$user_key->key_body}\n";
}

file_put_contents(getenv('HOME') . '/.ssh/authorized_keys', $content);
