<?php
$database_hosts = Hisoku::getMysqlServers();
$this->body_tags = array('data-target' => '.bs-docs-sidebar', 'data-spy' => 'scroll');
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<?= $this->partial('/admin/header.phtml', $this) ?>
<?php foreach ($database_hosts as $database_host) { ?>
<h1><?= $this->escape($database_host) ?></h1>
<?php
$link = new mysqli($database_host, getenv('MYSQL_USERDB_USER'), getenv('MYSQL_USERDB_PASS'));
$res = $link->query("SELECT `table_schema`, SUM(`data_length` + `index_length`) AS `size`, SUM(`table_rows`) AS `rows`, COUNT(*) AS `tables` FROM information_schema.TABLES GROUP BY table_schema");
$db_sizes = array();
while ($row = $res->fetch_assoc()) {
    if (strpos($row['table_schema'], 'user_') !== 0) {
        continue;
    }
    $db_sizes[$row['table_schema']] = $row['size'];
    $db_rows[$row['table_schema']] = $row['rows'];
    $db_tables[$row['table_schema']] = $row['tables'];
}
$res->free_result();

$res = $link->query("SHOW DATABASES LIKE 'user_%'");
$databases = array();
while ($row = $res->fetch_row()) {
    $databases[] = $row[0];
}
usort($databases, function($db1, $db2) use ($db_sizes) {
    return $db_sizes[$db2] - $db_sizes[$db1];
});

$res->free_result();
?>
<table class="table">
    <tr>
        <td>Database</td>
        <td>Project</td>
        <td>Usage</td>
        <td>Tables</td>
        <td>Rows(~)</td>
    </tr>
    <?php foreach ($databases as $db) { ?>
    <?php list(, $user) = explode('_', $db); ?>
    <tr>
        <td><?= $this->escape($db) ?></td>
        <td>
            <?php if ($user and $project = Project::search(array('name' => $user))->first()) { ?>
            <a href="/admin/project/<?= $project->id ?>" title="<?= $this->escape($project->getEAV('note')) ?>"><?= $project->name ?></a>
            <?php } ?>
        </td>
        <td class="usage" data-value="<?= intval($db_sizes[$db]) ?>"><?= number_format(intval($db_sizes[$db])) ?></td>
        <td><?= intval($db_tables[$db]) ?></td>
        <td><?= number_format(intval($db_rows[$db])) ?></td>
    </tr>
    <?php } ?>
</table>
<hr>
<?php } ?>
<script>
var usage_format = 'full';
$('.usage').click(function(){
    usage_format = ('full' == usage_format) ? 'simple' : 'full';

    $('.usage').each(function(){
        var value = $(this).attr('data-value');
        if (usage_format == 'full') {
            var rgx = /(\d+)(\d{3})/;
            while (rgx.test(value)) {
                value = value.replace(rgx, '$1' + ',' + '$2');
            }
            $(this).text(value);
        } else {
            if (value < 1024) {
                $(this).text(value);
            } else if (value < 1024 * 1024) {
                $(this).text(Math.floor(value / 1024.0) + 'KB');
            } else if (value < 1024 * 1024 * 1024) {
                $(this).text(Math.floor(value / 1024.0 / 1024) + 'MB');
            } else {
                $(this).text(Math.floor(value / 1024.0 / 1024 / 1024) + 'GB');
            }
        }
    });
});
</script>
<?= $this->partial('/common/footer.phtml', $this) ?>
