<?= $this->partial('/common/header.phtml', $this) ?>
<?= $this->partial('/admin/header.phtml', $this) ?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 bs-docs-sidebar">
            <!--Sidebar content-->
            <ul class="nav nav-list affix bs-docs-sidenav">
                <?php foreach (Machine::getMachinesByGroup('elastic') as $machine) { ?>
                <li>
                <a href="#node-<?= $this->escape($machine->machine_id) ?>">
                    <i class="icon-chevron-right"></i>
                    <?= $this->escape($machine->name) ?>
                </a>
                </li>
                <?php } ?>
            </ul>
        </div>
        <div class="span10">
            <!--Body content-->
            <?php foreach (Machine::getMachinesByGroup('elastic') as $machine) { ?>
            <div id="node-<?= $this->escape($machine->machine_id) ?>">
                <h3><?= $this->escape($machine->name) ?></h3>
<?php
Elastic::login('https://elastic-2.middle2.com:9200', getenv('ELASTIC_ADMIN_USER'), getenv('ELASTIC_ADMIN_PASSWORD')); // TODO: change url
$indices = Elastic::esQuery('/_cat/indices?format=json');
?>
            <table class="table">
                <thead>
                    <tr>
                        <th>Index</th>
                        <th>Health</th>
                        <th>status</th>
                        <th>docs.count</th>
                        <th>docs.deleted</th>
                        <th>store.size</th>
                        <th>pri.store.size</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach (Elastic::getUsers() as $user_data) { ?>
                <?php $prefix = rtrim($user_data->prefix, '*') ?>
                <tr>
                    <td colspan="7">
                        <h2>User: <?= $this->escape($user_data->user_name) ?>, Prefix: <?= $this->escape($prefix) ?></h2></td>
                </tr>
                <?php foreach ($indices as $index) { ?>
                    <?php if (strpos($index->index, $prefix) !== 0) { continue; } ?>
                    <tr>
                        <td><a target="_blank" href="/admin/elasticindex/?machine=<?= urlencode($machine->machine_id) ?>&index=<?= urlencode($index->index) ?>"><?= $this->escape(str_replace($prefix, '', $index->index)) ?></a></td>
                        <td><?= $this->escape($index->health) ?></td>
                        <td><?= $this->escape($index->status) ?></td>
                        <td><?= $this->escape($index->{'docs.count'}) ?></td>
                        <td><?= $this->escape($index->{'docs.deleted'}) ?></td>
                        <td><?= $this->escape($index->{'store.size'}) ?></td>
                        <td><?= $this->escape($index->{'pri.store.size'}) ?></td>
                    </tr>
                    <?php } ?>
                <?php } ?>
                </tbody>
            </table>
            <?php } ?>
        </div>
    </div>
</div>
<script><!--
//--></script>
<?= $this->partial('/common/footer.phtml', $this) ?>
