<?php
$grouped_nodes = WebNode::getGroupedNodes();
$this->body_tags = array('data-target' => '.bs-docs-sidebar', 'data-spy' => 'scroll');
$this->title = 'NodeServers Info :: ';
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<?= $this->partial('/admin/header.phtml', $this) ?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 bs-docs-sidebar">
            <!--Sidebar content-->
            <ul class="nav nav-list affix bs-docs-sidenav">
                <?php foreach ($grouped_nodes as $ip => $nodes) { ?>
                <li>
                <a href="#node-<?= $ip ?>">
                    <i class="icon-chevron-right"></i>
                    <?= long2ip($ip) ?>(<?= count($nodes) ?>)
                </a>
                </li>
                <?php } ?>
            </ul>
        </div>
        <div class="span10">
            <!--Body content-->
            <?php foreach ($grouped_nodes as $ip => $nodes) { ?>
            <div id="node-<?= $ip ?>">
                <h3><?= long2ip($ip) ?>(<?= count($nodes) ?>)</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <td>port</td>
                            <td>project</td>
                            <td>admins</td>
                            <td>status</td>
                            <td>start at</td>
                            <td>access at</td>
                            <td>action</td>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($nodes as $node) { ?>
                    <tr>
                        <td><?= $node->port ?></td>
                        <?php if (WebNode::STATUS_SERVICE == $node->status) { ?>
                        <td>
                            <?php if ($project = $node->getServiceProject()) { ?>
                            <a href="/project/detail/<?= $project->name ?>" title="<?= $this->escape($project->getEAV('note')) ?>"><?= $project->name ?></a>
                            <?php } ?>
                        </td>
                        <td>
                            <?= 'memcache' ?>
                        </td>
                        <td>Service</td>
                        <td>
                            <?= $this->partial('helper/counttime.phtml', array('time' => $node->start_at)) ?>
                        </td>
                        <td>
                        </td>
                        <?php } else { ?>
                        <td>
                            <?php if ($node->project) { ?>
                            <a href="/project/detail/<?= $node->project->name ?>" title="<?= $this->escape($node->project->getEAV('note')) ?>"><?= $node->project->name ?></a>
                            <?php } ?>
                        </td>
                        <td><!-- admins -->
                            <?php if ($node->project) { ?>
                            <?= $this->escape(implode(',', User::search(1)->searchIn('id', $node->project->members->search(array('is_admin' => 1))->toArray('user_id'))->toArray('name'))) ?>
                            <?php } ?>
                        </td>
                        <td><?= $this->escape($node->getStatusWord()) ?></td>
                        <td>
                            <?php if ($node->project) { ?>
                            <?= $this->partial('helper/counttime.phtml', array('time' => $node->start_at)) ?>
                            <?php } ?>
                        </td>
                        <td>
                            <?php if ($node->project) { ?>
                            <?= $this->partial('helper/counttime.phtml', array('time' => $node->getAccessAt())) ?>
                            <?php } ?>
                        </td>
                        <?php } ?>
                        <td>
                            <button class="btn btn-danger post-link confirm" data-confirm="確定要刪除 <?= long2ip($node->ip) ?> 的 port <?= $node->port ?> ?" data-link="/admin/nodeserverdeleteport/<?= urlencode(long2ip($node->ip)) ?>/<?= $node->port - 20000 ?>">Delete</button>
                            <?php if (WebNode::STATUS_STOP == $node->status) { ?>
                            <button class="btn post-link confirm" data-confirm="確定要打開 <?= long2ip($node->ip) ?> 的 port <?= $node->port ?> ?" data-link="/admin/nodeserverreleaseport/<?= urlencode(long2ip($node->ip)) ?>/<?= $node->port - 20000 ?>">Start</button>
                            <?php } elseif (WebNode::STATUS_UNUSED != $node->status) { ?>
                            <button class="btn post-link confirm" data-confirm="確定要放出 <?= long2ip($node->ip) ?> 的 port <?= $node->port ?> ?" data-link="/admin/nodeserverreleaseport/<?= urlencode(long2ip($node->ip)) ?>/<?= $node->port - 20000 ?>">Release</button>
                            <button class="btn post-link confirm" data-confirm="確定要暫停 <?= long2ip($node->ip) ?> 的 port <?= $node->port ?> ?" data-link="/admin/nodeserverstopport/<?= urlencode(long2ip($node->ip)) ?>/<?= $node->port - 20000 ?>">Stop</button>
                            <?php } else { ?>
                            <button class="btn post-link confirm" data-confirm="確定要暫停 <?= long2ip($node->ip) ?> 的 port <?= $node->port ?> ?" data-link="/admin/nodeserverstopport/<?= urlencode(long2ip($node->ip)) ?>/<?= $node->port - 20000 ?>">Stop</button>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <h4>New port</h4>
                <form method="post" action="/admin/nodeserveraddport/<?= urlencode(long2ip($ip)) ?>/" class="form-nodeserveraddport">
                    <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
                    20000 + <input type="text" name="port">
                    <button type="submit">New port</button>
                </form>
            </div>
            <hr>
            <?php } ?>
            <form method="post" action="/admin/nodeserveraddport/" class="form-nodeserveraddport-withhost">
                <input type="hidden" name="sToken" value="<?= Hisoku::getStoken() ?>">
                IP: <input type="text" name="ip"><br>
                Port: 20000 + <input type="text" name="port">
                <button type="submit">New port</button>
            </form>
        </div>
    </div>
</div>
<script><!--
$('.form-nodeserveraddport').submit(function(e){
    var form = $(this);
    form.attr('action', form.attr('action') + form.find('input[name="port"]').val());
});
$('.form-nodeserveraddport-withhost').submit(function(e){
    var form = $(this);
    form.attr('action', form.attr('action') + form.find('input[name="ip"]').val() + '/' + form.find('input[name="port"]').val());
});
//--></script>
<?= $this->partial('/common/footer.phtml', $this) ?>
