<?php
$body_append = '';
if ($this->body_tags) {
    foreach ($this->body_tags as $k => $v) {
        $body_append .= ' ' . $this->escape($k) . '="' . $this->escape($v) . '"';
    }
}
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Hisoku</title>
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css" rel="stylesheet">
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"></script>
</head>
<body<?= $body_append ?>>
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="/">Hisoku</a>
        <ul class="nav">
            <?php if ($guest = Hisoku::getLoginUser()) { ?>
            <li><a href="/"><?= $this->escape($guest->name) ?></a></li>
            <li><a href="/index/logout">Logout</a></li>
            <?php if ($guest->isAdmin()) { ?>
            <li><a href="/admin">Admin</a></li>
            <?php } ?>
            <li><a href="/phpMyAdmin" target="_blank">phpMyAdmin</a></li>
            <?php } else { ?>
            <li>
            <form method="post" action="/index/login" class="navbar-form">
                <input type="text" name="user" placeholder="email">
                <input type="password" name="password" placeholder="password">
                <button type="submit">Login</button>
                <a href="/register.php">Signup</a>
            </form>
            </li>
            <?php } ?>
        </ul>
    </div>
</div>
<div class="container">
